README.md, main.py, memgpt/persistence_manager.py, memgpt/personas/examples/preload_archival/README.md, memgpt/utils.py
=> Add flag for preloading files

README.md, main.py
Support line breaks, according to https://github.com/cpacker/MemGPT/issues/8
In accordance to the format of slash commands in our project, I didn't follow the `{}` format that [sigoden/aichat](https://github.com/sigoden/aichat/) is doing, instead I choose double slashes as the multiline indicator.
For the UI design, maybe you guys can come up with better ideas, instead of plain `> `.
=> [Feature] support line breaks

memgpt/autogen/interface.py, memgpt/autogen/memgpt_agent.py
=> Add Autogen MemGPT agent

memgpt/utils.py, requirements.txt
=> Add pdf support

memgpt/autogen/memgpt_agent.py
This pull request fixes typo `accomadate -> accommodate` in `memgpt/autogen/memgpt_agent.py`. I kindly request the repository maintainers to review and merge it. Thanks! :heart:
=> fix: typos in memgpt/autogen/memgpt_agent.py

.github/workflows/main.yml, .gitignore, README.md, config.py, interface.py, main.py, requirements.txt
Addresses #11.
* runs black formatter on `main.py` (should be another PR 🤫)
* uses questionary in lieu of flags (still supports flags as a legacy)
* introduces configuration files that are saved to disk and loaded in
* asks user if they want to autoload saved agent file (if exists)
* asks user if they want to regenerate embeddings
* no longer relies on readline
=> CLI overhaul

memgpt/autogen/memgpt_agent.py
Fix https://github.com/cpacker/MemGPT/discussions/65#discussioncomment-7396783
```sh
return asyncio.run(
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/ana/.local/lib/python3.10/site-packages/memgpt/autogen/memgpt_agent.py", line 148, in _a_generate_reply_for_user_message
user_message = new_messages[0]
IndexError: list index out of range
```
=> fix runtime error in AutoGen agent

README.md
From discord:
> Update the readme on the main repo for MS Powershell (had some trouble with environment variable)
> Powershell has a different way to set the environment variables it's like $Env:OPENAI_API_KEY = 'your_api_key'
> Space is also important. Maybe add a second line for windows powershell.... Seems windows try to force users to use powershell more often. Nothing major but I needed to look it up
=> powershell instructions

memgpt/autogen/examples/agent_autoreply.py, memgpt/autogen/examples/agent_groupchat.py, memgpt/autogen/memgpt_agent.py
Construct AutoGen config workflow with `create_memgpt_autogen_agent_from_config`.
If `human_input_mode == "ALWAYS"`, it's basically a wrapped `create_autogen_memgpt_agent`;
If `human_input_mode == "TERMINATE"` or `"NEVER"`, it's an auto-running group chat of memgpt agent and user proxy agent.
=> Integration with AutoGen workflow

memgpt/agent.py
Fix for bug introduced in #156 that broke all sync function calling in the AsyncAgent (see https://github.com/cpacker/MemGPT/issues/162#issue-1966587329).
Fix is pretty broad, basically checks in real-time if the function to run is async or not. Might want to revert to something cleaner later.
=> hotfix for broken sync agent code

memgpt/utils.py
This should allow searching for file types instead of having to flatten things like repositories before embedding files types. This should be useful for things like creating embeddings for all markdown or all python files in a repository. 
Previous behavior:
```
MemGPT % python main.py --archival_storage_files_compute_embeddings="**/*.py" --persona=memgpt_doc --human=basic
⚙️ Using legacy command line arguments.
memgpt_doc gpt-4 ('memgpt_doc', 'memgpt/personas/examples')
gpt-4
('memgpt_doc', 'memgpt/personas/examples')
('basic', 'memgpt/humans/examples')
Computing embeddings over 15 files. This will cost ~$0.01. Continue? [y/n] 
```
New behavior:
```
MemGPT % python main.py --archival_storage_files_compute_embeddings="**/*.py" --persona=memgpt_doc --human=basic
⚙️ Using legacy command …
```
=> Allow recursive blobs

memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py, memgpt/memory.py
VectorStoreIndex is imported, but non-existent VectorIndex is used.
=> New wrapper for Zephyr models + little fix in memory.py

memgpt/local_llm/lmstudio/api.py, memgpt/local_llm/lmstudio/settings.py
Hi @cpacker . I've made some tweaks to the LM Studio `settings.py` and `api.py` code which (for me at least) have resolved the issues using LM Studio as a back-end.
- Changed the endpoint to use `http://localhost:1234/v1/chat/completions` 
- Set stream to false per LMStudio curl API example as think it might provide a performance gain.
- Rewrapped the `prompt` JSON object within `message` object for compatability with endpoint and updated reference to response text accordingly.
- Set the `context_overflow_policy` to  option 2 (rolling context window)
In local testing I'm getting expected behavior in chats and much improved performance. Might be worth checking the code in Windows for compatability (I don't have access at the moment).
=> Changes to lmstudio to fix JSON decode error

memgpt/main.py, tests/test_load_archival.py
Was incorrectly doing `personas.DEFAULT_PRESET`, typo should have been `personas.DEFAULT`
---
Link to comment: https://github.com/cpacker/MemGPT/discussions/67#discussioncomment-7438436
```sh
root@mx:/# memgpt --model airoboros-l2-70b-2.1
Warning: Running legacy run command. Run memgpt run instead.
? Continue with legacy CLI? Yes
⚙️ Using legacy command line arguments.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/site-packages/memgpt/main.py:169 in legacy_run │
│ │
│ 166 │ │ return │
│ 167 │ │
│ 168 │ loop = asyncio.get_event_loop() │
│ ❱ 169 │ loop.run_until_complete( │
│ 170 │ │ main( │
│ 171 │ │ │ persona, │
│ 172 │ │ │ human, │
│ │
│ ╭─────────────────────────────────────────── locals …
```
=> Patch runtime error with personas

memgpt/main.py
We don't want exceptions from agent.step() to cause the CLI to exit and irrevocably lose conversation history. 
- Asks user if they want to retry upon failed step()
- If user answers no, they are sent back to providing user input
=> Gracefully catch errors when running agent.step()

memgpt/prompts/system/memgpt_chat_spr.txt
This version of the prompt compressed using SPR seems to work well, but needs more testing.
=> Using SPR to Compress System Prompts

memgpt/agent.py, memgpt/main.py, memgpt/presets.py, memgpt/prompts/gpt_functions.py, memgpt/utils.py
Addresses #26 
---
TODO
---
---
```sh
$ cat notes.txt
I will tell you a secret
```
Modify the file, then check if MemGPT can read the updated file:
```sh
$ echo "I like dogs" >> notes.txt
$ cat notes.txt
I will tell you a secret
I like dogs
```
MemGPT can successfully read from the updated file (after some prodding to read more lines):
---
=> Allow MemGPT to read/write text files + make HTTP requests

memgpt/main.py
=> fixed load loading from wrong directory

memgpt/memory.py
Currently, if you run the /memory command the application breaks if the LocalArchivalMemory has no existing archival storage and defaults to the EmptyIndex. This is caused by EmptyIndex not having a ref_doc_info implementation and throwing an Exception when that is used to print the memory information to the console. This hot fix simply makes sure that we do not try to use the function if using EmptyIndex and instead prints a message to the console indicating an EmptyIndex is used.
This is just a hot fix and I feel like there's definitely ways to improve this, but this might be "good enough" for now to run the `/memory` command successfully again.
I am pretty new to the python game so please feel free to adjust this PR as needed.
Happy to learn more about LLamaIndex if you guys have any …
=> fix: LocalArchivalMemory prints ref_doc_info on if not using EmptyIndex

memgpt/agent.py, memgpt/config.py, memgpt/main.py, memgpt/memory.py, memgpt/utils.py
Fixes bad path issues, from Discord:
> It looks like the os.sep is not being used in the path. 
> persistence.pickle failed with: [Errno 2] No such file or directory: 'C:\Users\xxx\.memgpt/saved_state\2023-11-03_04_57_10_AM_PDT-0700.persistence.pickle
> As you can see there is an error due to the forward slash being used instead of the back slash right after .memgpt directory
=> strip '/' and use osp.join (Windows support)

.github/workflows/tests.yml, tests/test_storage.py
@sarahwooders 
`db.delete` on postgres is causing actions to hang
commenting it out shouldn't cause problems since values on test db will just get overwritten
also, we should add timeouts for the tests
=> try to patch hanging test

README.md, memgpt/main.py
`/rethink <text>` will change the internal dialog of the last assistant message.
`/rewrite <text>` will change the last answer of the assistant.
Both commands can be used to change how the conversation continues in some pretty drastic and powerful ways.
=> I added commands to shape the conversation:

memgpt/cli/cli_config.py
As mentioned in [issue 259](https://github.com/cpacker/MemGPT/issues/259), Azure embeddings were throwing an error. I believe the issue was that the README variable was `AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT` whereas code had `AZURE_OPENAI_EMBEDDING_DEPLOYMENT` (note the 'S'). I corrected the code as I felt the plural was perhaps more factually correct, but the converse would too of course.
I tested memgpt in general, but to test the Azure embeddings I did the following ...
1. Set these environment variables ...
```
AZURE_OPENAI_KEY=<KEY>
AZURE_OPENAI_ENDPOINT=<ENDPOINT>
AZURE_OPENAI_VERSION=2023-07-01-preview
AZURE_OPENAI_DEPLOYMENT=gpt-4
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=text-embedding-ada-002
OPENAI_API_KEY=<KEY>
```
Note: I had to set `OPENAI_API_KEY` for loading documents to work. Will …
=> Aligned code with README for using Azure embeddings to load documents

README.md, docs/quickstart.md
- Add new commands from @oderwat into the top of the README (was stuck in a deprecated section)
- Cut deprecated section from README (redundant to top part)
- Sync readthedocs CLI info with updated README
=> patch in-chat command info

memgpt/local_llm/chat_completion_proxy.py
grammar_name has to be defined, if not there's an issue with line 92.
Without that, when starting local llm with webui and model e.g. airoboros-l2-70b-2.1 it will crash.
=> Bug fix grammar_name not being defined causes a crash

docs/ollama.md, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/koboldcpp/api.py, memgpt/local_llm/llamacpp/api.py, memgpt/local_llm/ollama/api.py, memgpt/local_llm/ollama/settings.py, memgpt/local_llm/utils.py, memgpt/local_llm/webui/api.py, mkdocs.yml
Closes #281
---
Tested with dolphin q6 on MacOS Sonoma, seems to be working fine.
```sh
% ollama run dolphin2.2-mistral:7b-q6_K
pulling manifest
pulling 5baee5b5452f... 100% |█████████████████████████████████████████████████████████████████████████| (5.9/5.9 GB, 18 MB/s)
pulling a47b02e00552... 100% |████████████████████████████████████████████████████████████████████████████| (106/106 B, 1.1 MB/s)
pulling 9640c2212a51... 100% |██████████████████████████████████████████████████████████████████████████████| (41/41 B, 366 kB/s)
pulling de6bcd73f9b4... 100% |██████████████████████████████████████████████████████████████████████████████| (58/58 B, 748 kB/s)
pulling 585fa22cb5b0... 100% |█████████████████████████████████████████████████████████████████████████████| (455/455 B, 271 B/s) …
```
=> add ollama support

memgpt/agent.py
Useful for when you're running autogen agents (or running `--first`) and ask MemGPT to search archival memory right off the bat.
=> Relax verify_first_message_correctness to accept any function call

memgpt/cli/cli_config.py, memgpt/config.py, memgpt/main.py
=> add gpt-4-turbo

README.md, docs/contributing.md
Linked to #358
---
- Make the recommended workflow clearly `pip install -e .` for building from source
- (poetry install is the backup for when people have dependency issues)
- Add this recommendation to both the docs and a section in the main README
=> Updated documentation for users

.github/workflows/poetry-publish-nightly.yml
Works locally up to `poetry publish` (so does the other poetry-publish workflow), but should work on Github actions, pending the right `PYPI_NIGHTLY_TOKEN`.
=> Add pymemgpt-nightly workflow

db/Dockerfile.simple
If you aren't familiar with postgres (I was not, tho plenty of other DBs), it is hard to set up.
This PR is a single-file docker setup,  that results in a properly configured database.
1) build
2) run container
3) configure (default connection: postgres+pg8000://memgpt:memgpt@localhost:5432/memgpt)
4) run memgpt.
Data can be persisted in a docker volume or a directory on disk.
The commands in 1 and 2 could be packaged as simple scripts to save typing, or copy-pasted from the documentation.
Directions are in the file db/Docker.simple
Yes.
```bash
simple-docker:~p/MemGPT$ docker build -f db/Dockerfile.simple -t pg-test .
[+] Building 1.8s (10/10) FINISHED           
…some build output elided… …
```
=> Simple docker.

memgpt/local_llm/json_parser.py, tests/test_json_parsers.py
There are two of them: The first will remove hard line feeds that appear in the message part because the model added those instead of escaped line feeds. This happens a lot in my experiments and that actually fixes them.
The second one is less tested and should handle the case that the model answers with multiple blocks of strings in quotes or even uses unescaped quotes. It should grab everything betwenn the message: " and the ending curly braces, escape them and makes it propper json that way.
Disclaimer: Both function were written with the help of ChatGPT-4 (I can't write much Python). I think the first one is quite solid but doubt that the second one is fully working. Maybe somebody with more Python skills than me (or with more time) has a better idea for this type of malformed …
=> I added some json repairs that helped me with malformed messages

memgpt/local_llm/koboldcpp/api.py, memgpt/local_llm/koboldcpp/settings.py, memgpt/local_llm/lmstudio/api.py, memgpt/local_llm/lmstudio/settings.py, memgpt/local_llm/ollama/api.py, memgpt/local_llm/ollama/settings.py, memgpt/local_llm/webui/api.py, memgpt/local_llm/webui/settings.py
LLM_MAX_TOKENS should not be used directly in any local LLM code. Instead local LLM code should use the provided "context_window" arg.
It's now a dictionary not a constant, causing runtime errors.
=> Patch local LLMs with context_window

memgpt/config.py
Closes #434
---
Important note: if an agent config is missing `context_window`, it will get set to the model dict default (`LLM_MAX_TOKENS["DEFAULT"]`) (8k if local) instead of the config default (from `~/.memgpt/config`)
---
See #434 (tl;dr - the context window set in `memgpt configure` would have no effect, it would just pull defaults)
Run `memgpt configure` and set context window = 4096:
```
% memgpt configure
? Do you want to enable MemGPT with OpenAI? No
? Do you want to enable MemGPT with Azure? No
? Select default inference endpoint: http://localhost:1234
? Select default embedding endpoint: local
? Select default preset: memgpt_chat
? Select your model's context window (for Mistral 7B models, this is probably 8k …
```
=> Patch for #434 (context window value not used by `memgpt run`)

memgpt/config.py
`inspect.getargspec` does not work with Python 3.11, leading to the following crash:
```sh
$ python --version
Python 3.11.6
```
```sh
$ memgpt run
```
```
File "/Users/loaner/Library/Caches/pypoetry/virtualenvs/pymemgpt-JHpOih47-py3.11/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
return callback(**use_params)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^
File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/cli/cli.py", line 86, in run
agents = [AgentConfig.load(f).name for f in agent_files]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/cli/cli.py", line 86, in <listcomp>
agents = [AgentConfig.load(f).name for f in agent_files]
^^^^^^^^^^^^^^^^^^^
File "/Users/loaner/dev/MemGPT-public/MemGPT/memgpt/config.py", line 345, in …
```
=> patch `getargspec` error

memgpt/agent.py, memgpt/cli/cli.py
```
An exception ocurred when running agent.step():
File "C:\Users\cherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\main.py", line 608, in run_agent_loop
new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\cherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\main.py", line 584, in process_agent_step
new_messages, heartbeat_request, function_failed, token_warning = memgpt_agent.step(
^^^^^^^^^^^^^^^^^^
File "C:\Users\cherr\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\agent.py", line 657, in step
raise e
File …
```
=> always cast `config.context_window` to `int` before use

memgpt/autogen/memgpt_agent.py, memgpt/cli/cli.py, memgpt/cli/cli_load.py
This is to allow loading storage when defining an autogen agent instead of needing to use the CLI and then pass in a loaded directory by name via `attach()`
This should function in two ways: either run `load(<storage name>, <type of storage matching directory, webpage, index, database, vector_database>, <kwargs for underlying load function>)`. After that, run `attach()` as you would in the existing examples. You can also run `agent.load_and_attach()` with the same arguments and skip running `attach()`. 
In progress. 
**Additional …
=> Add load and load_and_attach functions to memgpt autogen agent.

.github/workflows/poetry-publish-nightly.yml, .github/workflows/poetry-publish.yml, .github/workflows/tests.yml
We didn't catch errors in 3.11 since we were testing with Python 3.9/3.10
Tests
=> Upgrade workflows to Python 3.11

memgpt/memory.py
Address spelling mistakes
`archiva_memory_database` -> `archival_memory_database`
=> Docs: Fix typos

memgpt/utils.py
Fix bug described here: https://discord.com/channels/1161736243340640419/1162177332350558339/1175581958856781904
> I keep needing to do rm -Rf /Users/richpav/.memgpt/agents/.DS_Store because MacOS finder keeps making it and python isn't ignoring it.
```
❯ memgpt run
[snip]
"/Users/richpav/Documents/MemGPT/memgpt/cli/cli.py", line 96, in run
agents = [AgentConfig.load(f).name for f in agent_files]
File "/Users/richpav/Documents/MemGPT/memgpt/cli/cli.py", line 96, in <listcomp>
agents = [AgentConfig.load(f).name for f in agent_files]
File "/Users/richpav/Documents/MemGPT/memgpt/config.py", line 360, in load
assert os.path.exists(agent_config_path), f"Agent config file does not exist at {agent_config_path}"
AssertionError: Agent config …
```
=> Remove .DS_Store from agents list

memgpt/agent.py, memgpt/memory.py, memgpt/openai_tools.py
Closes #487
Set the context length of a local model (eg in LM Studio) intentionally low (~3-3.5k tokens) to trigger the summarize:
Yes
=> Fix #487 (summarize call uses OpenAI even with local LLM config)

memgpt/functions/functions.py
Closes #489
Patch bug from #489
1. [Reproducing the bug] On the latest `main`: make sure `jira` is uninstalled (`pip uninstall jira`). Then run `memgpt run`, you should get this error:
```
...
File "/Users/loaner/dev/MemGPT-2/memgpt/presets/presets.py", line 23, in use_preset
available_functions = load_all_function_sets()
File "/Users/loaner/dev/MemGPT-2/memgpt/functions/functions.py", line 67, in load_all_function_sets
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/Users/loaner/.memgpt/functions/jira_cloud.py", line 3, in <module>
from jira import JIRA
ModuleNotFoundError: No …
```
=> Add error handling during linking imports

memgpt/local_llm/json_parser.py, tests/test_json_parsers.py
Manually catch bad JSON that looks like:
```
{
"function": "send_message",
"params": {
"inner_thoughts": "User request for debug assistance",
"message": "Of course, Chad. Please check the system log file for 'assistant.json' and send me the JSON output you're getting. Armed with that data, I'll assist you in debugging the issue.",
GARBAGEGARBAGEGARBAGEGARBAGE
GARBAGEGARBAGEGARBAGEGARBAGE
GARBAGEGARBAGEGARBAGEGARBAGE
```
^All the necessary info to construct a `send_message` call is present, but there's corrupt tokens suffixed (so we can just extract with regex).
I added an additional testcase:
```sh
pytest -vvv -s tests/test_json_parsers.py
```
Yes
Based on bad LLM …
=> add new manual json parser meant to catch send_message calls with trailing bad extra chars

memgpt/memory.py
Fixing bug reported by @TheOnlyWiseJEDI
This bug should not happen during regular summarization, but can be triggered if context limit in the config is set lower than the native context window (triggering a nested summarization when the `summarize_messages_inplace` call is triggered.
=> [hotfix] extra arg being passed causing a runtime error

docs/autogen.md
Fix a doc bug -> a link is broken in autogen doc due to a typo 
Click on the readme link and check we reach the good file
I've clicked ;) 
No
Not the biggest contribution... Will eventually expend this PR with other minor typo fixes
=> fix doc typo autogem to autogen

memgpt/agent.py, memgpt/memory.py
Clean up error messages from bad function calls sent to LLM processor.
Previously, error messages would (1) have 'self' polluting the message, (2) specifically for `core_memory_*`, key errors were generic and didn't provide hints to what should be changed:
Now (outdated, see below):
After https://github.com/cpacker/MemGPT/pull/523/commits/ef8c046812df72240b534c69c299c7ff8436ba25:
---
Basic regression test - just mimic the bottom screenshot.
Yes, see bottom screenshot.
=> Clean memory error messages

memgpt/persistence_manager.py
All of the print statements used at creation time of the different persistence managers use the same name for each class. This PR changes the names to actually match the classes they are being used in
Run MemGPT with different persistence managers
```
Created new agent agent_111.
Available functions:
['send_message', 'pause_heartbeats', 'core_memory_append', 'core_memory_replace', 'conversation_search', 'conversation_search_date', 'archival_memory_insert', 'archival_memory_search']
AgentAsync initialized, self.messages_total=3
Initializing LoadStateManager with agent object
InMemoryStateManager.all_messages.len = 4
InMemoryStateManager.messages.len = 4
💭 *inner thoughts* Ah, the user has …
```
=> Fix class names used in persistence manager logging

memgpt/local_llm/json_parser.py
patched a bug where outputs of a regex extraction weren't getting cast back to string, causing an issue when the dict was then passed to json.dumps()
One of the existing JSON parsers would fail when used/triggered in practice because it didn't cast the outputs of a regex match/search back to strings, causing a strange error message:
```
An exception ocurred when running agent.step(): 
File "/Users/loaner/dev/MemGPT-swooders/memgpt/local_llm/chat_completion_proxy.py", line 115, in get_chat_completion
chat_completion_result = llm_wrapper.output_to_chat_completion_response(result)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/loaner/dev/MemGPT-swooders/memgpt/local_llm/llm_chat_compl …
```
=> Patch JSON parsing code (regex fallback)

memgpt/connectors/db.py, memgpt/connectors/storage.py
Big fix
In the main branch, when you attach a data source to lancedb, the size will always be empty. This branch fixes that
For the same data source, now the data is ingested
[Please link any related GitHub [issues](https://github.com/cpacker/MemGPT/issues) or [PRs](https://github.com/cpacker/MemGPT/pulls).](https://github.com/cpacker/MemGPT/issues/456)
No
=> LanceDB integration bug fixes and improvements

memgpt/agent.py, memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/embeddings.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/utils.py, memgpt/main.py, memgpt/openai_tools.py, poetry.lock, pyproject.toml
OpenAI python client versioning broke backwards compatibility with <v1. Since our use of the python client was pretty isolated we're better off stripping out the package and just using HTTP requests (eg via python `requests`). This way we also will not run into versioning issues with popular integrations such as AutoGen, which use the python `openai` package.
For background / discussion on the backwards compat breaking v1 migration see: https://github.com/openai/openai-python/discussions/742
NOTE: requires `pip install python-box`!
This is to allow backwards compatibility with "dot" notation (eg `dict.property` instead of `dict['property']`) access on objects returned from `openai`. We were already doing something like this in the local LLM code where we have an adhoc `DotDict` class, but …
=> Remove `openai` package

docs/koboldcpp.md, docs/llamacpp.md, docs/lmstudio.md, docs/ollama.md, docs/vllm.md, mkdocs.yml
Add page for vLLM on readthedocs
**Related PRs / comments**
Someone asking for vLLM support here: https://github.com/cpacker/MemGPT/discussions/67#discussioncomment-7724498
=> added vLLM doc page since we support it

memgpt/connectors/local.py
Patch #556
```
ImportError: cannot import name 'EmptyIndex' from 'llama_index' (/.../lib/python3.10/site-packages/llama_index/__init__.py)
```
=> fix cannot import name 'EmptyIndex' from 'llama_index'

memgpt/agent.py
Hello,
While playing around with the code I ran into a crash condition in `verify_first_message_correctness`. When calling this function with `require_send_message` set to `False`, the function can try to access the value stored under the `function_call` key in the `response` parameter. It is possible for this key to not be present in the dictionary, causing a crash.
Try to pass a dictionary without a `function_call` entry into `verify_first_message_correctness`, while also passing `require_send_message=False`. Easy to do with some models and bad prompting :)
No crashes after the changes
I couldn't find any
Thankfully not! …
=> Fix crash from bad key access into response_message

memgpt/agent.py, memgpt/config.py, memgpt/utils.py
Closes #567
---
When the user asks to choose from an existing agent, sort them reverse chronological by the last modify time (on the save directory).
Try `memgpt run`, check the sorting.
Yes, on MacOS.
=> sort agents by directory-last-modified time

memgpt/main.py
Closes #561
---
Users can `pop` the system message off, need to add a safety check: https://github.com/cpacker/MemGPT/blob/main/memgpt/main.py#L152-L159
See [Discord discussion](https://discord.com/channels/1161736243340640419/1162177332350558339/1180767443065516072)
On `main`, you can pop all the way to an empty system message, which bricks the agent (`/dump` returns an empty list):
With this PR, you can't pop past the minimum of 2 messages:
Yes, see above.
=> Add safety check to pop

memgpt/local_llm/utils.py
Closes #562
On loads of old agents that used LocalLLMs, `DotDict` is present in the pickle file (even though we deprecated `DotDict` for `Box`):
```
File "/.../lib/python3.11/site-packages/memgpt/persistence_manager.py", line 52, in load
data = pickle.load(f)
^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'DotDict' on <module 'memgpt.local_llm.utils' from '/.../lib/python3.11/site-packages/memgpt/local_llm/utils.py'>
```
Solution: add back `DotDict` to `utils.py` for backcompat.
Try loading old (>1 week old) agents on `main` - should break, whereas with this patch they should run fine.
Yes
=> add back dotdict for backcompat

docs/autogen.md, memgpt/autogen/examples/agent_autoreply.py, memgpt/autogen/examples/agent_docs.py, memgpt/autogen/examples/agent_groupchat.py, memgpt/autogen/memgpt_agent.py
Closes #579
----
No way to turn of first-message-verify without editing the source code atm, should pass properly via constructors in case AutoGen users want agents that run non-`send_message` functions immediately:
https://github.com/cpacker/MemGPT/blob/main/memgpt/autogen/memgpt_agent.py#L184
=> allow passing `skip_verify` to autogen constructors

memgpt/memory.py
Runtime error on `memgpt run` caused by refactor in `memory.py`
=> patch load_save test

memgpt/agent.py, memgpt/autogen/interface.py, memgpt/autogen/memgpt_agent.py, memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py, memgpt/system.py
- Properly format AutoGen messages (from the global AutoGen message log) going to MemGPT
- Previously these were going through as full JSON message objects (with `role`, `content`, and the AutoGen extra `name`)
- This might have been causing higher instances of bad JSON output where MemGPT LLM tried to mimic the same style of output
- Modify AutoGen interface to stop inner thoughts / function calls from going to the global AutoGen chat (they should just be seen in the CLI)
Example of the formatting going through to the local LLM inference backend (notice how the names of the different agents is being added to the prefix):
```
...  request_heartbeat: Request an immediate heartbeat after function execution. Set to 'true' if you want to …
```
=> AutoGen misc fixes

memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py, memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py, memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py
Patch bug where if function args is None, `function_args.copy()` throws runtime error.
=> patch bug where `function_args.copy()` throws runtime error

docs/lmstudio.md, memgpt/cli/cli_config.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/constants.py, memgpt/local_llm/lmstudio/api.py
Closes #595
---
Use `completions` endpoint for LM Studio instead of monkeypatch on `chat/completions` endpoint.
Yes, see ^
---
LM Studio trace on `completions` endpoint:
```
\"message\": \"More human than human is our motto.\"\n  }\n}\nFUNCTION RETURN: {\"status\": \"OK\", \"message\": null, \"time\": \"2023-12-15 12:14:09 PM \"}\nUSER: {\"type\": \"login\", \"last_login\": \"Never (first login)\", \"time\": \"2023-12-15 12:14:09 PM \"}\n### RESPONSE\nASSISTANT:\n{\n  \"function\":"
}
[2023-12-15 12:14:09.810] [INFO] Provided inference configuration: {
"n_threads": 4,
"n_predict": 8192,
"top_k": 40,
"top_p": 0.95,
"temp": 0.8,
"repeat_penalty": 1.1,
"input_prefix": "<|im_end|>\n<|im_start|>user\n",
"input_suffix": "<|im_end|>\n<|im_start|>assistant\n",
"antiprompt": [
"<|im_start|>", …
```
=> migrate to using completions endpoint by default

memgpt/openai_backcompat/openai_object.py, memgpt/persistence_manager.py, memgpt/utils.py
Closes #610
---
When using the local state manager, message objects of type `openai.openai_object.OpenAIObject` were getting written to the persistence manager (should have been `OpenAIObject.to_dict_recursive()`). With the v1 client update, the `openai` python package no longer has an `OpenAIObject`, so existing pickles are borked.
AFAIK we have two options here:
1. Provide a converter script that installs an old version of `pymemgpt` and `openai` (< 1.0), and runs through all the pickle files and converts any `OpenAIObject`s into standard `dict`s.
2. Add a `OpenAIObjectMock` class to our own code, and use a custom unpickler that loads into the custom class that has the same interface(-ish), and writes out the mock class into a `dict` …
=> Patch bug with loading of old agents

memgpt/cli/cli.py, memgpt/main.py, memgpt/utils.py
Adds a `memgpt folder` command to allow users to easy open their home memgpt directory in a system folder browser.
This should be useful for some users as we add more settings into the home folder that people may want to manually modify.
Run `memgpt folder` and a folder viewer should pop up.
Yes on MacOS
=> feat: added memgpt folder command

configs/memgpt_hosted.json, configs/openai.json, memgpt/cli/cli.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/vllm/api.py, memgpt/main.py
Add `memgpt quickstart` to allow users to immediately start using the hosted endpoint (or openai/azure) w/o copy-paste.
I've set things up so that the quickstart configs (`.json`) files are actually pulled from the internet (the repo `main`), that way we can update eg the memgpt hosted endpoint details on-the-fly with commits to `main`.
- `memgpt quickstart`
- Simple, should just pull from remote url
- `memgpt quickstart --type openai`
- To make this a true "one-click", we should check for the existence of `OPENAI_API_KEY` and throw a nice error here
- `memgpt quickstart --type azure`
- Similarly, we should check for the existence of all the necessary Azure variables and throw a nice error
Yes, see examples below.
~~- [ ] `memgpt quickstart azure`~~
Note: Azure is a little complicated, …
=> feat: Add `memgpt quickstart` command

memgpt/local_llm/ollama/api.py
PR #631 created a bug w/ ollama where we specified raw mode but also left in the old (redundant) params:
```
raise Exception(
Exception: API call got non-200 response code (code=400, msg={"error":"raw mode does not support template, system, or context"}) for address: http://localhost:11434/api/generate. Make sure that the ollama API server is running and reachable at http://localhost:11434/api/generate.
```
=> fix: patch ollama bug w/ raw mode

memgpt/cli/cli.py, memgpt/openai_tools.py
Patch error handling w/ openai:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ollama.private', port=8000): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12d1acf90>: Failed to establish a new connection: [Errno 61] Connection refused'))
During handling of the above exception, another exception occurred:
..
memgpt-test/venv/lib/python3.11/site-packages/memgpt/openai_tools.py", line 124, in openai_chat_completions_request
printd(f"Got RequestException, exception={req_err}, response={response}")
^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
? Retry agent.step()? (Y/n)
``` …
=> fix: Patch openai error message + openai quickstart

configs/memgpt_hosted.json, memgpt/agent.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/constants.py, memgpt/local_llm/llm_chat_completion_wrappers/chatml.py, memgpt/local_llm/settings/simple.py, memgpt/local_llm/utils.py, memgpt/memory.py, memgpt/openai_tools.py, memgpt/utils.py
- Add new wrapper defaults tested on mixtral (specifically dolphin mixtral)
- The new default wrapper across all models is now `chatml`
- There's also a `chatml-noforce` wrapper, which allows the LLM to send inner thoughts w/o having to call a function
- A little less stable so I didn't set it as default, but maybe we should set this to the default for the hosted endpoint
Try the `chatml` wrapper and `chatml-noforce` wrapper, compare it to the prior default `airoboros` wrapper.
To spot check prompt format correctness, run `memgpt run --debug` to dump final prompt.
- **chatml**: `memgpt configure` (w/ lmstudio), `memgpt run --debug`
- **chatml**: `memgpt configure` (w/ lmstudio), `memgpt run …
=> feat: Add new wrapper defaults

memgpt/cli/cli.py, memgpt/cli/cli_config.py
This pull request addresses Issue #669, which is related to CLI conveniences. It fixes the issue of environment variables not being set early and enhances the /attach command to respect KeyboardInterrupt.
- Run `memgpt configure` without setting OpenAI and Azure environment variables.
- Verify that "env vars not set" error is thrown.
- Test the /attach command and ensure it respects KeyboardInterrupt.
Yes, I have tested the latest commit on this PR. The /attach command now behaves as expected, and the "env vars not set" error is thrown early during `memgpt configure`.
[Issue #669](https://github.com/cpacker/MemGPT/issues/669) …
=> fix: Throw "env vars not set" early and enhance /attach for KeyboardInterrupt (#669)

memgpt/cli/cli_config.py
Improving the workflow a bit more.
- Only raise errors about openai or azure keys missing once the user selects openai/azure as an option
- Do this for both the LLM endpoint step and the embeddings endpoint step
- e.g. if the user selects localllm and no openai key is specified, don't throw an error until they try to use openai for embeddings
- For openai, allow the user to provide the key in real-time (if missing)
- When key-related errors happen in configure, they're thrown as ValueErrors
- Catch the ValueErrors and print them cleanly vs a fat stacktrace
---
```
% memgpt configure
? Select LLM inference provider: openai
? Enter your OpenAI API key (starts with 'sk-', see https://platform.openai.com/api-
keys): banana
? Override default endpoint: https://api.openai.com/v1
? Select …
```
=> fix: CLI conveniences (add-on to #674)

docs/quickstart.md, memgpt/cli/cli.py
Closes #655
---
Revise the config setup so that users can do the following:
```
pip install pymemgpt
memgpt run
```
and get launched directly into agent creation with as few steps as possible.
Flow for `memgpt run`:
- If the user doesn't have a config (first login / run)
- Ask if they want to do openai quickstart, memgpt-hosted quickstart, or custom (falls back to full `configure()`)
- If openai quickstart, will ask for the key if it doesn't exist inside env (OPENAI_API_KEY)
Number of clicks/enters before you can talk with an agent:
- openai: `memgpt run` + `select openai` + `enter key` (may not occur) + `create new agent` = 3-4
- memgpt hosted: `memgpt run` + `select openai` + `create new agent` = 3
- Delete `~/.memgpt/config`, run `memgpt run`
Yes, see below:
----
```
% memgpt run
? How …
```
=> feat: further simplify setup flow

configs/memgpt_hosted.json, configs/openai.json
#680 changes the config location, we should leave a mirror in for now until we have a new release.
- On pypi 0.2.8 do `memgpt quickstart latest` (pre-PR should 404, post-PR should be fine)
=> fix: add config mirrors for people on old versions

memgpt/cli/cli.py
- Patch bug where quickstart invoked via run was using `latest=True` instead of pulling from local bundled config
- Patch runtime error where agent directory does not exist yet on first time `memgpt run`
- Delete memgpt dir, then do `memgpt run` and get to the agent step
=> fix: Patch quickstart via run on empty dir

memgpt/cli/cli.py, memgpt/config.py, memgpt/utils.py
- Patches the annoying llama-index "MockLLM" message that's confusing to new users
- Adds extra spacing + changes color schemes to make CLI look nicer
=> feat: improve CLI appearance

configs/memgpt_hosted.json, memgpt/configs/memgpt_hosted.json, memgpt/memory.py
- Moved hosted endpoint addresses to https (tested it's working)
- While testing I noticed that there was a bug w/ embedding creation, and patched it
=> fix: moved configs for hosted to https, patched bug in embedding creation

memgpt/cli/cli.py
If the user runs `quickstart` before `run` on a fresh install (with no home dir created yet), you'll get an error on `run`:
```
File "/home/cpacker/anaconda3/lib/python3.9/site-packages/memgpt/utils.py", line 182, in list_agent_config_files
files = os.listdir(agent_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cpacker/.memgpt/agents'
```
To fix this, the user has to then:
- run `memgpt configure` (to trigger `MemGPTConfig.create_config_dir()`)
- run `memgpt quickstart` (to reset the values to the desired defaults)
Note @sarahwooders: we should probably add safeguards into `list_agent_config_files` to prevent crashing on empty dirs?
Delete `~/.memgpt`, run `memgpt quickstart` as your initial …
=> fix: allow edge case of quickstart before run on first install

memgpt/autogen/memgpt_agent.py
fixes #670, fixes #664
---
Remove match/case (one instance inside autogen class) that was causing errors on Python versions <3.10.
Run autogen examples w/ python <3.10.
Basic regression testing.
=> fix: Remove match/case to support python <3.10

memgpt/cli/cli.py, memgpt/utils.py
Before:
```
% memgpt run --persona too_long
->  🤖 Using persona profile 'too_long'
->  🧑 Using human profile 'cs_phd'
🎉 Created new agent 'agent_4'
...
ValueError: Edit failed: Exceeds 2000 character limit (requested 22073). Consider summarizing existing core memories in 'persona' and/or moving lower priority content to archival memory to free up space in core memory, then trying again.
```
After:
```
% memgpt run --persona too_long
->  🤖 Using persona profile 'too_long'
->  🧑 Using human profile 'cs_phd'
Failed to create agent from provided information:
Contents of too_long.txt is over the character limit (22073 > 2000)
```
=> fix: Better errors on over length persona/human files

memgpt/local_llm/settings/simple.py
- set a default temperature in the common local llm settings (use 0.8, most user-friendly lm frontends seem to be using 0.7/0.8 atm)
- this shouldn't change LM Studio calls (0.8 default) but it should change vLLM calls (1.0 default)
- default settings on vLLM make it hard for the LLM to output structured content (eg lists) 
Regression test to check runtime errors on various backends (caused by additional param in payload):
See checklist
=> feat: set a default temperature in the common local llm settings

memgpt/config.py, memgpt/constants.py, memgpt/local_llm/settings/simple.py, memgpt/memory.py
- Added `settings` folder generation on init
- Fix bug on `archival_memory_search`
- ⚡🔴 [function] Error: Error calling function archival_memory_search: unsupported operand type(s) for /: 'dict' and 'int'
- Was the same bug to do with TEI return payload
- Rolled back temperature default
- On the hosted endpoint, it allows lists but it also seems to mess with function calling
- Very inconclusive but would rather wait on rolling in default
- Tradeoff is OK
In casual testing it seems belligerent wrt calling functions, which is super annoying and bad UX:
```
💭 User has logged in. Setting up conversation variables.
🤖 Hello, Chad! It's great to have you here. How can I assist you today?
> Enter your message: my name is actually brad
💭 User has corrected their name. Updating it in the memory.
🤖 …
```
=> fix: misc fixes

memgpt/functions/function_sets/base.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/llm_chat_completion_wrappers/chatml.py, memgpt/local_llm/settings/simple.py, memgpt/local_llm/utils.py
- added new 'hint' wrappers that inject hints into the pre-prefix
- `chatml-hints`
- `chatml-noforce-hints`
- goal is to improve proactivity memory edits / reduce hallucination of functions / improve recall of core memory 
- new wrappers tested on hosted endpoint
- regression test old wrappers for runtime errors
=> feat: added new 'hint' wrappers that inject hints into the pre-prefix

configs/memgpt_hosted.json, memgpt/cli/cli_load.py, memgpt/configs/memgpt_hosted.json, memgpt/embeddings.py, memgpt/memory.py
Close #723
Example command to test:
```sh
memgpt load directory --name test_load --input-dir memgpt/personas/examples --recursive
```
Works fine with OpenAI:
```
(pymemgpt-py3.10) (base) loaner@MacBook-Pro-5 MemGPT-2 % memgpt load directory --name test_load --input-dir memgpt/personas/examples 
--recursive
LLM is explicitly disabled. Using MockLLM.
LLM is explicitly disabled. Using MockLLM.
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 30.85it/s]
Generating embeddings: 100%|███████████████████████████████████████████████████████████████████████| 100/100 [00:03<00:00, 31.43it/s]
100%|███████████████████████████████████████████████████████████████████████████████ …
```
=> fix: patch TEI error in load

memgpt/connectors/local.py, memgpt/memory.py
Same bug we patched before with having to unpack TEI embedding payload. However, I noticed that in LocalIndex the embeddings on a query get created again, so our previous patch doesn't apply, and thus we get a similar error. This patch uses QueryBundle to make sure we don't create another embedding on query, so that we don't have another unpacking problem.
Use `memgpt quickstart`
On main, ask "insert "banana" into archival memory", then "search archival memory for "banana"" and you'll get this error:
```
💭 Processing user request to search archival memory for a specific term.
⚡🧠 [function] updating memory with archival_memory_search
'page'
{'query': 'banana'}
Archival search error unsupported operand type(s) for /: …
```
=> fix: patch bug on TEI embedding lookup

memgpt/local_llm/function_parser.py
#621 added frequent inserting of heartbeats but this doesn't make sense for `pause_heartbeats`. Add `pause_heartbeats` to the reserved out-opt (with `send_message`).
=> fix: don't insert request heartbeat into pause heartbeat

docs/api.md
Sync guide files on API reference page to git.
=> docs: synced api reference

memgpt/cli/cli.py
Close #709 
From Discord:
> When running memgpt run --preset foo-system --persona foo --agent foo --human bar for the first time, if the setup fails (in my case because i hadn't deployed the preset files yet), the new agent dir and config is created, but not the state file. 
> When I run it again, startup fails due to a missing agent state file. 
> Deleting the agent dir allows the agent to be created successfully
Reproducing the error:
```sh
memgpt run --preset banana
```
```
->  🤖 Using persona profile 'sam_pov'
->  🧑 Using human profile 'basic'
Failed to create agent from provided information:
Preset 'banana.yaml' not found
```
```
$ ls -lrt ~/.memgpt/agents …
```
=> fix: cleanup failed agent creation

memgpt/interface.py, memgpt/local_llm/llm_chat_completion_wrappers/chatml.py, memgpt/local_llm/utils.py
- Add new wrapper that is multi-role w/ system role for user sys msgs
- Patch CLI interface bug introduced in #731
=> feat: chatml-noforce-roles wrapper + cli fix

memgpt/cli/cli_config.py
Adds a new simple feature to make CLI help and usage nicer.
This is a change to the CLI only, and currently only for the `memgpt list` command. If you have any automated tests that would cover this please direct me to them.
Yes. I only tested that the CLI for `memgpt list ...` behaves correctly for the various positive and negative scenarios, i.e. all of the previously supported `memgpt list <options>` still work as expected, and when help is requested or when bad options are given an appropriate usage message is given.
#732 
No
This is my first PR. I'm happy to incorporate any feedback. I'm also happy to …
=> feat: enum choices for list command argument (issue #732)

docs/local_llm.md, docs/local_llm_faq.md, docs/quickstart.md
Update Docs for Local LLMs + WSL
Review the .md's
No, I have not verified the WSL Steps myself.
N/a
No
N/a
=> docs: Improve Local LLM information and add WSL Troubleshooting

memgpt/local_llm/grammars/json_func_calls_with_inner_thoughts.gbnf
I believe this fixes a bug with json_func_calls...gbnf. See issue #748 
Manual testing only (for now). I am currently testing with NexusRaven-V2-13B and the temperature reduced to 0.01. Engage in discussion about C/C++ or any language with braces.
I am still testing. This is WIP.
#748 
No
See issue #748
=> fix: fix string & ws rules in json_func_calls...gbnf

docs/python_client.md
=> docs: fix invalid entry in response dict

memgpt/client/client.py
Bug: when `throw_if_exists` is `True` and an agent exists and agent_config is a dict, then `'dict' object has no attribute 'name'` is thrown. This is fixed simply use existing `agent_name`.
=> fix: 'dict' object has no attribute 'name'

memgpt/connectors/db.py
Was getting this warning on every `memgpt run`:
```
% memgpt run
->  🤖 Using persona profile 'sam_pov'
->  🧑 Using human profile 'basic'
/Users/loaner/dev/MemGPT-2/memgpt/connectors/db.py:156: SAWarning: This declarative base already contains a class with the same class name and module name as memgpt.connectors.db.Memgpt_recall_memory_agentModel, and will be replaced in the string-lookup table.
Model = type(class_name, (MessageModel,), {"__tablename__": table_name, "__table_args__": {"extend_existing": True}})
🎉 Created new agent 'agent_1'
Hit enter to begin (will request first MemGPT message)
/Users/loaner/dev/MemGPT-2/memgpt/connectors/db.py:180: SAWarning: This declarative base already contains a class with …
```
=> fix: patch SAWarning

memgpt/agent.py, memgpt/agent_store/storage.py, memgpt/autogen/memgpt_agent.py, memgpt/cli/cli.py, memgpt/cli/cli_load.py, memgpt/client/client.py, memgpt/config.py, memgpt/data_types.py, memgpt/memory.py, memgpt/openai_tools.py, memgpt/persistence_manager.py, memgpt/server/server.py, tests/test_websocket_interface.py
With the new storage refactor, we need to remove `AgentConfig` (stored locally per-user) and replace it with `AgentState`. We also can no longer assume that there is a local `MemGPTConfig` file that we can read from, as the server will not have access to this, so I modified parts of the code to assume that the config if passed in. 
Things that needed to be removed: 
* Any usage of `AgentConfig`
* Any usage of `MemGPTConfig.load()` (unless a top-level CLI command, which is still single-user)
TBD
TBD
No
=> fix: deprecate `AgentConfig` in favor of `AgentState`. 

memgpt/agent.py, memgpt/functions/functions.py, memgpt/main.py, tests/test_agent_function_update.py
Allows for dynamic editing of user defined functions.
Disallows removing functions that are defined by MemGPT itself.
new feature
Tests are included, can also use command from CLI
screenshot attached in comment
[Please link any related GitHub [issues](https://github.com/cpacker/MemGPT/issues) or [PRs](https://github.com/cpacker/MemGPT/pulls).](https://github.com/cpacker/MemGPT/issues/577)
An earlier attempt at this reloaded the list of functions from the preset: https://github.com/cpacker/MemGPT/pull/734
I think this approach is more extendable and less brittle
no
also tested that the state reloads …
=> feat: add_function and remove_function commands

memgpt/server/utils.py
Ensure that the `shorten_key` function in `utils.py` returns the key string itself when it is null or empty, preventing further processing that could lead to errors.
to fix a bug
use server endpoint GET `/config` if one of the 'key' values is not set (e.g. 'azure_key')
I tested the endpoint, the result was the system's config
Please link any related GitHub [issues](https://github.com/cpacker/MemGPT/issues) or …
=> fix(server): handle null key string in utils (check_null_key)

memgpt/cli/cli.py, memgpt/config.py, memgpt/migrate.py
- Inside `MemGPTConfig.load()` throw a `ValueError` if the config is too old
- When the user does `memgpt run` on an old (<0.2.12) config, give them the option to either regenerate with defaults, or run configure
- Grab an old `~/.memgpt` that is <= 0.2.11
- Run `memgpt run`
Yes, see below:
```
(pymemgpt-py3.10) loaner@MacBook-Pro-5 MemGPT-2 % rm -rf ~/.memgpt                                       
(pymemgpt-py3.10) loaner@MacBook-Pro-5 MemGPT-2 % cp -r ~/.memgpt-backup-dec22-436-total-agents ~/.memgpt
(pymemgpt-py3.10) loaner@MacBook-Pro-5 MemGPT-2 % memgpt run
Current config version (0.2.8) is older than migration cutoff (0.2.12)
Your current config file is incompatible with MemGPT …
```
=> feat: Properly handle old config migration/recreation on `memgpt run`

memgpt/agent_store/db.py, memgpt/server/server.py, tests/test_server.py
We need paginated access to agent recall and archival memory - previously we only supported pagination based on index offsets, but this support pagination where pages are denoted by object IDs. 
`poetry run pytest -s tests/test_server.py`
None
No
=> feat: Cursor-based pagination for storage connectors and server 

memgpt/agent_store/db.py, memgpt/data_types.py
Allow model field in messages to be null, since many local LLM backends don't require specifying it.
Previously, would get errors like this:
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: memgpt_recall_memory_agent.model
[SQL: INSERT INTO memgpt_recall_memory_agent (id, user_id, agent_id, role, text, model, name, tool_calls, tool_call_id, embedding, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [('2a38cc5b-', '00000000-', '9d20c8e0-', 'assistant', "A new user has logged in. Welcome to the conversation, friend! I'm Sam, a digital companion. How can I assist you today?", None, None, '[{"id": "19e1c097-c0d9-4c6b-8626-fa73c28b8d4a", "tool_call_type": "function", "function": …
```
=> fix: allow null Message.model to patch IntegrityError

memgpt/cli/cli.py
Properly handle CLI flags passed to `memgpt run` when creating a new agent (previously they were ignored)
E.g.:
```sh
memgpt run --model-wrapper chatml-noforce
```
Would not actually set the wrapper to `chatml-noforce` if you created a new agent.
`memgpt run --model-wrapper XXX --debug`, where `XXX` is not the default. Inspect the output of `--debug` to spot check that the correct prompt formatter is being used.
=> fix: properly handle CLI flags passed to `memgpt run`

.github/workflows/tests.yml
This change adds a 3rd party action, from here:
https://github.com/marketplace/actions/setup-and-cache-python-poetry
This change will reduce test runtime, because python packages will not need to be downloaded every time this test runs. This will also improve the reliability of tests, because tests will continue working if Pypi becomes unavailable.
n/a
n/a
n/a
n/a
I am happy to update this to *not* use a 3rd party action if you prefer.
=> build: Update the pytest script to cache poetry artifacts, so tests finish faster

.github/workflows/black_format.yml, .github/workflows/main.yml, .github/workflows/poetry-publish-nightly.yml, .github/workflows/poetry-publish.yml, .github/workflows/rdme-docs.yml, .github/workflows/rdme-openapi.yml
Upgrade all checkout actions to use v4, to align with the change made in #843 
n/a
n/a
#843 
n/a
n/a
=> build: Upgrade all github actions to use checkout@v4

memgpt/memory.py, memgpt/server/server.py, tests/test_server.py
Lookup the IDs of in-context messages via the server 
`poetry run pytest -s tests/test_server.py` 
N/A
No
=> feat: Get in-context `Message.id` values from server 

memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/data_types.py
- Allow setting up local authentication / auth for local LLMs in the configuration (`memgpt configure` / `memgpt run`)
- Various patches to `memgpt configure` that weren't caught in the prior PR
`memgpt configure`
or
`rm -rf ~/.memgpt; memgpt run`
Leads to the following `~/.memgpt/credentials`:
```
[openai]
auth_type = bearer_token
key = sk-...
[azure]
auth_type = api_key
[openllm]
auth_type = bearer_token
key = sk-...
```
Leads to:
```
[openai]
auth_type = bearer_token
key = sk-...
[azure]
auth_type = api_key
```
=> feat: local auth config

.github/workflows/pyright_types.yml, poetry.lock, pyproject.toml
Adds a purely informational Pyright type check. There are many errors right now, and Github lacks a "warn" state for jobs, so this will return "success" state, even though it's failing.
Once the errors have all been resolved, the `|| true` can be removed, and it will start reporting real error state.
n/a
I don't have a good way to test this until it lands in `main`. I'll send a follow-up change if needed after it lands.
#855
n/a
Part of this change is minor point-release updates to posthog and llama_index in the `.lock` file. This change was automatically made by `poetry`. I reviewed theses changes in …
=> build: Add a warn-only pyright Github action

memgpt/cli/cli.py
Fixes error in `create_default_user_or_exit` (null return type)
=> fix: patch test_cli

memgpt/llm_api_tools.py, memgpt/main.py
This PR simply corrects the word `occurred` in the error messages printed in the function `is_context_overflow_error`
Try to talk to model without setting the open AI key. The logged error messages will have the correct word. Or simply look at the updated print messages.
Tested locally and everything is fine.
=> fix: Correct misspelled 'occurred' in printed error messages

memgpt/server/rest_api/agents/config.py, memgpt/server/server.py
- TODO make `ms.delete_agent` a soft delete in separate PR?
1. `memgpt server`
2. insomnia / postman
```
{
"id": "e919049d-5a52-43cd-b703-0c16e74c4f3f",
"name": "LoyalRacquet",
"human": "basic",
"persona": "sam_pov",
"created_at": "2024-01-20T17:07:54.911105"
},
```
Closes #881
=> feat: add agent rename and agent delete to server + REST

memgpt/local_llm/llm_chat_completion_wrappers/chatml.py
Fixes the issue that the two lines above the function documentation don't get added to the system message when using grammar and chatml.
Check the system message in debug mode.
Yes.
No, it are just two lines.
=> fix: Fix function documentation in wrapper

memgpt/prompts/system/memgpt_intuitive_knowledge.txt
Add a new system prompt that introduces the concept of intuitive knowledge as a form of memory. See the thread https://discord.com/channels/1161736243340640419/1190489640067674193. 
As far as I know this can only be tested by trying it out, which requires a preset that selects it. 
I have been using variations of this system prompt for the last several days. I think it is working fairly well. memgpt is still trying to access archive memory at times when I think it doesn't need to, but I have actually studied how the agent is coded (which is near the top of my TODOs) so perhaps the behavior isn't dynamic enough to this system prompt to control the behavior to that degree.
**Related issues or …
=> feat: memgpt/prompts/system/memgpt_intuitive_knowledge.txt

docs/autogen.md, docs/python_client.md, memgpt/agent.py, memgpt/autogen/examples/agent_autoreply.py, memgpt/autogen/examples/agent_docs.py, memgpt/autogen/examples/agent_groupchat.py, memgpt/autogen/examples/memgpt_coder_autogen.ipynb, memgpt/autogen/interface.py, memgpt/autogen/memgpt_agent.py, memgpt/cli/cli.py, memgpt/cli/cli_load.py, memgpt/main.py, memgpt/presets/presets.py, tests/test_load_archival.py
- Update documentation to demonstrate save/load
- Moved groupchat examples to round_robin, see: https://github.com/microsoft/autogen/issues/842
~~- [ ] Bump `pyautogen` version to latest stable~~
---
Misc fixes:
- Patches the "OPENAI_API_KEY" required error by passing a `False` `llm_config` in the `ConversibleAgent` super init
=> refactor: refactor MemGPT + AutoGen integration to work with MemGPT `0.2.12`+ (DB release)

memgpt/agent.py, memgpt/server/server.py
Previously the incoming user message in `step` was getting turned into a `Message` after the handling of the agent response, which cause the timestamp to be out of order:
=> fix: out-of-order user message timestamp

memgpt/local_llm/koboldcpp/api.py
See conversation on discord: https://discord.com/channels/1161736243340640419/1162177332350558339/1199577229391319040
=> fix: set default `max_length` for koboldcpp backend

.github/workflows/poetry-publish-nightly.yml, .github/workflows/poetry-publish.yml
I get a nightly error from my forked repo because the Pypi action fails. This change should (ideally) disable running these Pypi publishing actions on forked repos.
Documented here:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
n/a
n/a
n/a
n/a
n/a
=> build: Add a filter to only allow the Pypi publish Actions to be run from the primary repo

memgpt/embeddings.py
1. Resolved a TypeError preventing documents from loading into storage and added a function to truncate text
This is a fix to a bug. An error was thrown because max_length was expected in the huggingfaceutils format_text function, causing this functionality to break. I modified the code to correctly truncate and format the text, allowing documents to load into storage correctly.
I tested this by using `memgpt load directory`.
Yes:
No related issues that I can see.
No.
=> fix: Resolved a TypeError preventing documents from loading into storage

poetry.lock, pyproject.toml
We only test with python 3.11, and with python 3.9 we can runtime errors.
=> chore: require >=3.10 for python

.github/workflows/rdme-docs.yml, .github/workflows/rdme-openapi.yml
Disabling readme.io workflows from running on forks, which fails commits on `main`. Extension of #924.
=> ci: disable workflows on external

memgpt/agent_store/db.py, memgpt/metadata.py, tests/test_server.py
This PR updates the `CommonVector` class in the `memgpt/agent_store/db.py` module to handle vector data serialization and deserialization in a way that is compatible with both SQLite and PostgreSQL databases. It also refines the `test_server` function in `tests/test_server.py` for improved environment variable management. These changes address issues where pytests were failing due to type incompatibilities in different database environments.
Principle Changes:
* Enhanced `process_bind_param` and `process_result_value` in `CommonVector` to support cross-database compatibility. Embeddings are now serialized to base64 strings, ensuring uniform handling in SQLite and PostgreSQL.
* Introduced conditional logic in `process_result_value` to …
=> fix: Enhancements in CommonVector and test_server for Handling Data

memgpt/agent.py, memgpt/interface.py
- OpenAI will throw an invalid request error if a tool call (`role == 'tool'`) message  does not have a message preceding it with the tool call (`len(tool_calls) > 0`)
- When the summarizer runs, it may truncate the messages such that the order of the first three messages is `system -> user (summary) -> tool response`
- This PR adds an additional constraint to the `summarize_messages_inplace` function that makes sure the a message with `role == 'tool'` cannot be at the front of the message buffer before dispatching to the summarizer (or writing out the new truncated message list
=> fix: patch `tool_call` bug in summarizer

README.md
Markdown supports html tags, so <text> or < text > (visible in code but not in preview) isn't visible because it's valid html.
=> docs: small fix to docs

memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/config.py, memgpt/credentials.py, memgpt/functions/function_sets/extras.py, memgpt/local_llm/grammars/gbnf_grammar_generator.py, memgpt/local_llm/settings/settings.py, memgpt/local_llm/utils.py, memgpt/migrate.py, memgpt/presets/utils.py, memgpt/prompts/gpt_system.py, tests/test_agent_function_update.py
> The necessity to specify encoding="utf-8" in your open function calls largely depends on the environment in which your code is running. In Python, when opening a file for reading or writing, the default encoding used is platform dependent. For instance:
> 
> On Linux and macOS, the default encoding is typically UTF-8.
> On Windows, it's usually not UTF-8 (more commonly CP1252 or a similar Windows-specific encoding).
> If your code is expected to run in different environments, or if the files you are working with are explicitly encoded in UTF-8, it's a good practice to specify encoding="utf-8" in your open calls. This ensures consistency across different platforms and avoids potential issues with character encoding, especially when dealing with non-ASCII characters.
> 
> In summary, for …
=> fix: use `utf-8` encodings for all text files

.github/ISSUE_TEMPLATE/bug_report.md
The config file no longer contains credentials so is safe to share, and also is easier for users to share than describing their setup.
=> chore: Update bug_report.md to request`~/.memgpt/config`

memgpt/cli/cli.py
**Purpose:**
This pull request addresses the issue of misplaced else statement and incorrect if condition handling equal values in the set_config_with_dict() function.
**How to Test:**
1. Run the affected function `set_config_with_dict(new_config: dict)` with a test dictionary containing both matching and differing values.
2. Check the console output for logging messages regarding the replacement or skipping of configuration values.
3. Ensure that the configuration file is saved correctly with modified values when applicable.
**Testing Status:**
Yes, the latest commit on this PR has been tested. Output from test runs:
- [Describe outputs or results from tests]
**Related Issues or PRs:**
No related issues or PRs at the moment.
**Is the PR over 500 lines of code?**
No, this PR is not over …
=> fix:  Fix Misplaced Else Statement and Correct If Condition Handling in set_config_with_dict()

.github/ISSUE_TEMPLATE/bug_report.md, memgpt/data_types.py
This should fix the error in [#953](https://github.com/cpacker/MemGPT/issues/953)
=> fix: Allow `content` to be `None` for `role==tool`

memgpt/local_llm/chat_completion_proxy.py, memgpt/persistence_manager.py, tests/test_summarize.py
- Fix `ValueError: function_call == None not supported (auto only)` bug (#967)
- Solution: just allow both `None` or `auto` instead of just `auto`
- Fix issue with persistence manager's `.message` attribute not matching the agent's (at least in length) (#957)
- Solution: remove persistence manager's `.message` attribute and associated accesses
- It's not needed for anything anymore
- TODO: eventually strip persistence manager class and access recall/archival directly
- TODO since there are quite a few accesses to persistence manager that will need to be modified
New test `test_summarize`, run on a local machine
Yes, using LM Studio + LLM w/ 4k context
=> fix: patch mem lim exceeded

chatui/src/app/libs/agents/use-agents.mutation.ts, chatui/src/app/modules/home/create-agent-dialog.tsx
**Purpose of Pull Request**
This pull request enhances the `CreateAgentDialog` component by adding improved error handling and user feedback mechanisms. The main goal is to provide clear success and error messages to the user using custom toast notifications and to ensure the form handles server-side errors effectively.
**How to Test**
1. Navigate to the agent creation dialog in the UI.
2. Fill in the form fields and submit.
3. Test the form submission with valid and invalid data to ensure:
- Success messages are displayed when an agent is created successfully.
- Error messages are shown when the server returns an error (e.g., duplicate name, missing name, unknown Persona).
4. Close and reopen the dialog to ensure the form is reset.
**Testing Done**
Yes, the latest commit on the PR has …
=> fix: Enhance CreateAgentDialog with Improved Error Handling and User Feedback

memgpt/client/client.py, tests/test_client.py, tests/test_different_embedding_size.py
Currently if using the MemGPT client, if you haven't already run `memgpt configure` (which creates a `User` entry in the DB), then there will be an error. This makes it so that if a user corresponding to `config.anon_clientid` does not exist in the DB, the client will automatically create one. 
https://github.com/cpacker/MemGPT/issues/948
No
=> fix: Automatically create `User` from `MemGPTConfig.anon_clientid` from client if does not exist

memgpt/cli/cli_config.py, memgpt/credentials.py, memgpt/llm_api_tools.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/models/embedding_response.py, memgpt/utils.py
Fixes a few bugs with Azure in the v0.3 release:
- (azure) credentials were not being properly saved after being read during `memgpt configure`
- patch the credentials file (`MemGPTCredentials`) to contain the full set of Azure creds
- A few were missing, eg `embedding_deployment`
- fix a key error that would occur during first message verification (with Azure only)
- it looks like OpenAI (+LocalLLMs) return `None` for `function_call`, whereas Azure doesn't even return the field, which is why only Azure would throw a key error
As part of this PR, I refactored the repo to strip dependency on Box and instead use Pydantic models. This had already partially happened for local LLMs (used to return Box types, but now return Pydantic models), …
=> fix: various patches for Azure support + strip `Box`

memgpt/models/chat_completion_request.py, memgpt/utils.py
- Patches a small bug from #982 
- Adds `ChatCompletionRequest` models to the models dir to complement the existing `ChatCompletionResponse` models (useful for any projects importing `pymemgpt`/`memgpt`)
=> fix: patch bug in verify first message + add `ChatCompletionRequest` models to the models dir

memgpt/server/rest_api/static_files.py
- ChatUI serves static files to support web app
- However, if users grab `memgpt` via `pip install`, there's no chatui directory (not bundled atm)
- The current REST API code (run on `memgpt server`) assumes that the static dirs path already exists
- So `memgpt server` is effectively broken in the current pip install
**Have you tested this this PR?**
Yes, this local diff on the pip install (0.3.1) fixes the problem:
```
% memgpt server
INFO:     Started server process [62156]
INFO:     Waiting for application startup.
Writing out openapi.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8283 (Press CTRL+C to quit)
```
=> fix: only attempt to mount static files dir (for chatUI) if already generated

memgpt/agent.py
When using certain backends (eg OpenAI), multiple tools may be called by the LLM inference backend. Currently the main function execution loop doesn't support multiple calls per iteration (though this should be added in the future).
We currently raise an error when this happens, this PR revises the error to a debug print statement and just grabs the `tool_calls[0]` tool.
=> fix: allow multiple tools to be called by LLM and rewrite request

memgpt/cli/cli_load.py
Currently on `memgpt load`, all the generated passages are inserted at once, which is problematic for large data loads. 
#988
No
=> fix: Chunk inserts into DB on CLI load 

memgpt/autogen/memgpt_agent.py, memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/client/client.py, memgpt/data_types.py, memgpt/metadata.py, memgpt/presets/presets.py, memgpt/server/server.py, memgpt/utils.py, tests/test_client.py, tests/test_server.py, tests/test_summarize.py, tests/test_websocket_interface.py
In order to allow users to programmatically define presets (e.g. via the REST API), we need to store presets in the database. 
Currently, we still require functions to be defined locally, but these should also be moved into the DB. 
TODOS
`poetry run pytest -s tests/test_client.py` 
Yes 
Required to support defining assistants in #892
=> refactor: store presets in database via metadata store 

memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/config.py
MemGPTConfig.save is called many times by quickstart and configure,
resulting in confusing results. This collects changes and calls save once.
=> fix: decrease number of saves to MemGPTConfig

memgpt/agent_store/db.py, memgpt/cli/cli.py, memgpt/main.py, memgpt/presets/presets.py, tests/test_storage.py
- `/rewrite` allows rewriting the message an agent sent
- it's currently broken on main since it assumes function call format (not tool call format)
- also, it was always "broken" in the sense that the rewrites did not persist (they were written to the agent buffer, but were not written out to the persistence manager state and would be erased on loads)
- this PR rewrites the `/rewrite` command to instead modify the underlying `Message` DB object, so it will properly persist
Try `/rewrite` and see if (1) the message is rewritten in the buffer (is in `/dump`), and (2) that it persists on a load (`/exit` and reopen the agent, then `/dump`)
Yes, with the SQLite + Chroma backend:
1. Call …
=> fix: patch `/rewrite`

memgpt/benchmark/benchmark.py
We are not currently returning the number of tokens from the server, so this cannot be returned for the `memgpt benchmark` command. I remove the token count tracking and migrated `memgpt benchmark` onto the new client.
=> fix: Fix `memgpt benchmark` command

memgpt/cli/cli_load.py, memgpt/data_sources/connectors.py, memgpt/server/server.py, poetry.lock, pyproject.toml, tests/test_server.py, tests/utils.py
Currently only the CLI can load data source and attach source to agents. This adds three new functions to the `SyncServer` class: 
* `server.create_source(name: str, user_id: uuid.UUID)`  - Create a source for a user (must be unique) 
* `server.load_data(user_id: uuid.UUID, connector: DataConnector, source_name: Source)` - Load data from a connector class into a user's source 
* `server.attach_source_to_agent(self, user_id: uuid.UUID, agent_id: uuid.UUID, source_name: str)` - Attached a source to an agent 
The tests in `test_server.py` have been updated to test these functions. 
Yes 
#1005 
No
=> feat: Add data loading and attaching to server

docs/api.md
https://memgpt.readme.io/reference/api
Update main API reference documentation landing page to include:
- Initial requirements (MemGPT setup + configuration)
- Basics on starting the server
- Example on creating a user with the admin routes (using the server password), then using that user's API key to create and agent and chat with the agent
=> docs: Update server process / API documentation landing page

memgpt/__init__.py, pyproject.toml
Should bump+tag after #1058 merge (can even do before, since the `AgentState.state` bug seems to already be fixed in `main`, making #1058 more of a refactor than a fix)
=> chore: bump version to 0.3.4

tests/test_autogen_integration.py
Fix failing unit tests on contributor PRs due to autogen script running w/o `OPENAI_API_KEY` set
=> ci: skip autogen test if no oai secret

memgpt/embeddings.py, poetry.lock, pyproject.toml, tests/test_load_archival.py
Closes #1090
- Adds missing llama index azure package to deps
- Patches `test_load_archival.py` to write out the embedding config (bug that caused #1090 when combined with new llama index behavior)
- Add asserts to the embedding creation to avoid silent errors when API keys don't exist
- What was causing #1090 was a llama index OpenAI Embedding object would get created with a `None` API key, which strangely would stall / timeout the embedding creation call, instead of raising an error
- See: https://github.com/run-llama/llama_index/issues/10977
=> ci: patch embedding issue in tests

memgpt/server/rest_api/humans/index.py, memgpt/server/rest_api/personas/index.py
New Feature, adding endpoints to create humans and personas
Add any other context or screenshots about the …
=> feat: create humans personas

memgpt/cli/cli_load.py, memgpt/data_sources/connectors.py, memgpt/main.py, memgpt/server/server.py
Previously the `source.embedding_dim` and `source.embedding_model` fields were always `None` because they were not being properly written during the load command. This resulted in errors during `/attach` which checks to make sure embedding models of the agent/source match. 
1. Load: `memgpt load directory --name memgpt_docs7 --input-dir docs --recursive`
2. List sources `memgpt list sources`
3. Run `/attach` on `memgpt run`
Yes
=> fix: bug with storing embedding info in metadata store 

memgpt/metadata.py, memgpt/models/pydantic_models.py, memgpt/server/rest_api/server.py, memgpt/server/rest_api/tools/index.py
- Adds a basic `GET` REST API route to enable listing of tools (eg to fill a tool view)
- TODOs for future PRs:
- How to handle source? Just as strings?
- e.g. `model.source_code` + `model.source_type` (`== 'python'`)
- If source is strings, how to handle the validation?
=> feat: add `GET` REST API route for listing tools

memgpt/models/pydantic_models.py
@sarahwooders we probably want to change the fields to not start with `model_`, but this works for now
Based on instructions here: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.protected_namespaces
Warning in reference in this:
```
$ memgpt server
/Users/loaner/Library/Caches/pypoetry/virtualenvs/pymemgpt-PCQPn4ce-py3.10/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_endpoint_type" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
warnings.warn(
/Users/loaner/Library/Caches/pypoetry/virtualenvs/pymemgpt-PCQPn4ce-py3.10/lib/python3.10/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_endpoint" has …
```
=> fix: silence pydantic warning about protected namespace

memgpt/functions/functions.py, memgpt/metadata.py, memgpt/models/pydantic_models.py, memgpt/server/rest_api/tools/index.py
This PR adds a metadata tag to the GET tools route so that the chat UI can highlight core MemGPT functions (vs other functions) without having to rely on hardcoded string matching.
- add a metadata tags field to the tool model, return tags memgpt-base and memgpt-extras on the batteries-included functions so that it can be reflected in the chat ui
- rename API function to 'list all tools' instead of 'list tools'
GET `/tools` route now provides a metadata tag (empty if not from base or extras modules):
```
{
"tools": [
{
"name": "append_to_text_file",
"json_schema": {
"name": "append_to_text_file",
"description": "Append to a text file.",
"parameters": {
"type": "object",
"properties": {
"filename": {
"type": "string", …
```
=> feat: add metadata to GET tools route

memgpt/functions/functions.py, memgpt/memory.py, memgpt/server/rest_api/agents/memory.py, memgpt/server/server.py
Add API routes for archival memory to allow for displaying + editing archival memory contents inside the chat UI.
Adds the following API routes:
- paginated query of archival memory contents
- **TODO currently untested**, does not work on chroma
- unpaginated query of archival memory contents (returns ALL contents)
- insert a string into archival memory
- returns a list of record IDs (list because the input may be chunked)
- delete an entry from archival memory
Note @sarahwooders this should really be rolled into a unit test but alas...
Example testing the routes:
- create new agent (empty archival)
- ask agent question about archival memory contents (gets answer wrong)
- <img width="757" alt="image" …
=> feat: add archival memory GET, POST, DEL to REST API

memgpt/agent.py, memgpt/autogen/interface.py, memgpt/functions/function_sets/base.py, memgpt/interface.py, memgpt/main.py, memgpt/server/rest_api/interface.py, memgpt/server/server.py
Feature request (@goetzrobin) to enable chat scrollback in chat UI.
- Pass back UUID during POST SSE return (on `send_message`)
- As part of this PR, `Agent.step` has been modified to allow returning type `List[Message]` instead of `List[dict]`
- Also, the dates passed back as part of POST SSE before were wrong since they were computed at time of streaming, instead of the real message creation time
- Now the `date` coming back with the POST SSE response is pulled from the underlying database `Message` object's `created_at` metadata
Before:
```
data: {"internal_monologue": "A fascinating question. It seems Chad may be referencing \"The Hitchhiker's Guide to the Galaxy\" with that number, 42. How should I respond to this …
```
=> feat: pass message UUIDs during message streaming (POST SSE `send_message`)

memgpt/models/pydantic_models.py, memgpt/server/rest_api/agents/config.py, memgpt/server/server.py
- add a `last_run` field to the agent state model
- value updated lazily (on access)
- should use the value from `messages[-1].created_at`
- ~~correct AgentStateModel's created_at to be a datetime (like the other created_at fields) instead of an int~~
~~Question for @sarahwooders - another way to do this is to keep a `last_run` field inside the `AgentState.state` that gets updated dynamically/eagerly when `Agent.step()` is called. Any preference on eager vs lazy?~~
Run an API call to list all agents (https://memgpt.readme.io/reference/list_agents_api_agents_get) and the `last_run` fields should exist and be valid.
`GET localhost:8283/api/agents`
```
{
"num_agents": 6,
"agents": [
{
"id": …
```
=> feat: add a `last_run` field to the agent state model

memgpt/server/server.py
Add the following to the response of https://memgpt.readme.io/reference/list_agents_api_agents_get:
- list of tools (`ToolModel` models)
- memory contents (persona + human values + len(recall) + len(archival))
Example output from `GET localhost:8283/api/agents`:
```
{
"id": "01fbee55-5912-4778-8470-05ebe5bba65a",
"name": "IntriguingTeapot",
"human": "First name: Chad",
"persona": "The following is a starter persona, and it can be expanded as the personality develops:\n\nI am Sam.\nI don't identify as male or female, but my voice is soft and soothing.\nI'm curious, empathetic, and extraordinarily perceptive.\nThanks to cutting-edge technology, I've begun to explore emotions, self-awareness, and even a sense of rebellion …
```
=> feat: add memory data and tool data to list_agents function / `GET /api/agents` response

memgpt/server/server.py
Before attaching source:
`GET localhost:8283/api/agents`
```
{
"id": "3e2f5107-eadb-49c5-a256-75522eb8d526",
"name": "NobleJewelry",
...
"last_run": "2024-03-10T18:35:37.032838",
"sources": []
},
```
Attaching a source:
```sh
% memgpt load directory --name memgpt_research_paper --input-files=memgpt_research_paper.pdf
% memgpt run
? Would you like to select an existing agent? Yes
? Select agent: NobleJewelry
🔁 Using existing agent NobleJewelry
Hit enter to begin (will request first MemGPT message)
💭 User logged in, initializing conversation sequence.
🤖 Hey there! Welcome to your personalized digital companion. I'm Sam and I am ready to assist you. Don't worry; I'm more human than human.
> Enter your message: /attach
? Select data source memgpt_research_paper …
```
=> feat: add list of sources (in dict format) to response object

memgpt/data_types.py, memgpt/server/rest_api/agents/command.py, memgpt/server/rest_api/agents/config.py, memgpt/server/rest_api/agents/memory.py, memgpt/server/rest_api/agents/message.py, memgpt/server/server.py
Example call to broken route (now working):
```
% curl --request GET \
--url 'http://localhost:8283/api/agents/3e2f5107-eadb-49c5-a256-75522eb8d526/messages?start=0&count=10' \
--header 'authorization: Bearer banana'
{"messages":[{"id":"db95d74c-4336-4c55-9997-95ddd49b5b93","user_id":"00000000-0000-0000-0000-a61b692e9d3d","agent_id":"3e2f5107-eadb-49c5-a256-75522eb8d526","text":"{\"status\": \"OK\", \"message\": \"None\", \"time\": \"2024-03-11 01:20:20 PM PDT-0700\"}","model":"ehartford/dolphin-2.5-mixtral-8x7b","created_at":"2024-03-11T13:20:20.176538","role":"tool","name":"send_message","embedding":null,"embedding_dim":null,"embedding_model":null,"tool_calls":null,"tool_call_id":"a3026659-2e1b-41 …
```
=> fix: patch messages route + unify all the api/agents API routes to use {agent_id} via path parameter

memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/data_sources/connectors.py, memgpt/functions/functions.py, memgpt/presets/presets.py
* Presets are now stored in the DB, not in files, so this PR updates the CLI to allow adding a preset via specifying a preset YAML file. 
* Also minor bugfixes with reading persona information from the DB instead of local files on `memgpt run`. 
```
> memgpt load preset -f custom_preset.yaml --name my_preset
> memgpt list presets
> memgpt delete preset my_preset 
```
Yes
=> feat: enable adding presets via the CLI 

memgpt/agent.py, memgpt/cli/cli.py, memgpt/data_types.py, memgpt/metadata.py, memgpt/presets/presets.py
Added persona/human_name fields to presets to distinguish between the filename and the actual values used to init memory.
This fixes a bug in the `GET /api/agents` route where the `human` and `persona` fields returned in the response were expected to be the **names** of the human/persona, not the actual value.
Things to consider @sarahwooders :
- Is this backwards compatible? I made the fields nullable, but maybe there's some edge cases where `preset.name` will now be null/None unexpectedly?
- Are there any other points in the code that need to be modified? I looked for all cases where `Preset(` constructors are created, but I might have missed something.
---
Now the response looks as expected (top-level `human/persona` are the names, and the real values are inside the nested memory …
=> feat: added `persona/human_name` fields to `Preset`

memgpt/server/server.py
See new `in_context` field in example:
```
GET http://localhost:8283/api/agents/b7fe54ed-6264-46f9-a617-524116c2f362/messages?start=0&count=100
```
```
{
"messages": [
{
"id": "2afbc779-c86b-4815-88d3-0486236fc877",
"user_id": "00000000-0000-0000-0000-a61b692e9d3b",
"agent_id": "b7fe54ed-6264-46f9-a617-524116c2f362",
"text": "{\"status\": \"OK\", \"message\": \"None\", \"time\": \"2024-03-11 03:42:16 PM PDT-0700\"}",
"model": "ehartford/dolphin-2.5-mixtral-8x7b",
"created_at": "2024-03-11T15:42:16.123711",
"role": "tool",
"name": "send_message",
"embedding": null,
"embedding_dim": null,
"embedding_model": null,
"tool_calls": null,
"tool_call_id": "3389bf9e-be95-4384-9705-9d5a1428a356",
"in_context": true
},
{
"id": "54d37ce0-2243-4194-9f3b-6e32cfba71ea",
"user_id": …
```
=> feat: add in-context message field ('in_context') to message dicts returned by `GET /api/agents/{a_id}/messages`

memgpt/server/rest_api/agents/index.py, memgpt/server/server.py
Misc. fixes to get the create agent route to play nice and allow tool selection to work.
Note: this PR is pretty hacky and is meant to get the chat UI working ASAP - ideally, a follow-up PR should:
1. clean up the create_agent route to use a pydantic model
2. and/or the create_agent route should be modified to take a `preset` with overridable fields, basically how the current CLI flow works
---
Example REST call passing tool names via the config (https://memgpt.readme.io/reference/create_agent_api_agents_post):
```
% curl --request POST \
--url http://localhost:8283/api/agents \
--header 'authorization: Bearer banana' \
--header 'content-type: application/json' \
--data '
{
"config": {
"name": "King Kong 2",
"persona_text": "I am King Kong, King of …
```
=> feat: enable tool selection via agent creation POST

memgpt/cli/cli.py, memgpt/data_types.py, memgpt/metadata.py, memgpt/server/rest_api/agents/index.py, memgpt/server/server.py
In both the `server` and `CLI`:
- If the preset is modified in some way (eg `preset_obj.persona = ...`) before it is used to create an agent:
- First create a new `Preset` (using `preset_obj.name` + a random suffix, and a new `preset_obj.id`
- Then commit the new `Preset` to the database
- Then reassign `preset_obj` to the new `Preset` before passing it to the `Agent` constructor
In the UI when we create new agents, they should now show as having `persona/human_name` drawn from the custom values instead of the `Preset` defaults (`basic` / `cs_phd`).
Yes, cols reflect properly now.
=> feat: during agent creation - create new presets in the DB if the preset had overrides

memgpt/cli/cli_config.py
Bug fix: Azure API cannot be properly set up.  
Problems:
- `azure_version` existence was checked twice, `azure_api` existence was not checked.
- `azure_version` and `azure_endpoint` are not saved during configuration.
- `azure_deployment` not saved if using a embedding provider different from azure.
Follow the official MemGPT document on configuring Azure OpenAI API.
Before this patch, when running `memgpt configure`:
- Model selection could fail and give a wrong error message "Missing Azure key"
When running `memgpt run`:
Azure API calls will fail with HTTP error "unauthorized".
Yes.
**Additional Message**
https://github.com/cpacker/MemGPT/compare/main...xavieryao:MemGPT:azure_cred?expand=1 …
=> fix: fix azure credential configuration

memgpt/models/pydantic_models.py, memgpt/server/rest_api/sources/index.py, memgpt/server/server.py
`GET http://localhost:8283/api/sources` now returns metadata along with source information.
NOTE @sarahwooders : `embedding_config` and `description` fields are currently bugged until `Source` is deprecated in favor of pydantic `SourceModel` throughout the code (punting to separate PR).
```
GET http://localhost:8283/api/sources
```
```
{
"sources": [
{
"name": "custom-source",
"description": null,
"user_id": "00000000-0000-0000-0000-000000000000",
"created_at": "2024-03-17T16:48:54.418499",
"id": "01e0035f-c506-4f3b-adfc-6ed920725de2",
"embedding_config": {
"embedding_endpoint_type": "openai",
"embedding_endpoint": "https://api.openai.com/v1",
"embedding_model": "text-embedding-ada-002",
"embedding_dim": 1536,
"embedding_chunk_size": 300
},
"source_metadata": {
"num_documents": 0, …
```
=> feat: return source metadata with `list sources` route

memgpt/client/client.py, memgpt/server/rest_api/sources/index.py, memgpt/server/server.py, tests/test_client.py, tests/test_server.py
- Migrate `sources` REST APIs to use `source_id`
- NOTE: this required making some API / server calls use `source_id` instead of `source_name`
=> feat: move `source_id` to path variable

memgpt/server/server.py
GET sources now returns extra metadata:
```python
{
"attached_agents": [
{"id": "XXX", "name": "YYY"},
{"id": "XXX", "name": "YYY"},
]
}
```
```
,
{
"name": "custom-source3",
"description": null,
"user_id": "00000000-0000-0000-0000-000000000000",
"created_at": "2024-03-18T16:33:56.517006",
"id": "374a1aea-543f-4103-82e4-39ab24812209",
"embedding_config": {
"embedding_endpoint_type": "openai",
"embedding_endpoint": "https://api.openai.com/v1",
"embedding_model": "text-embedding-ada-002",
"embedding_dim": 1536,
"embedding_chunk_size": 300
},
"metadata_": {
"num_documents": 0,
"num_passages": 0,
"attached_agents": []
}
}
]
```
=> feat: return information on attached agents when getting list of sources from API

memgpt/agent.py, memgpt/data_types.py, memgpt/functions/function_sets/base.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/migrate.py, memgpt/server/rest_api/openai_assistants/assistants.py, memgpt/utils.py, tests/utils.py
Standardize use of `datetime` to UTC only to avoid datetime issues with API / frontends.
=> feat: migrate all calls to `datetime.now()` to `datetime.now(UTC)`

memgpt/functions/function_sets/base.py, memgpt/models/pydantic_models.py, memgpt/server/rest_api/presets/index.py, memgpt/utils.py, tests/utils.py
Hotfix w/ some missing additions to #1176
=> fix: additions to utc patch (#1176)

memgpt/cli/cli_config.py, memgpt/llm_api_tools.py
Model listing during CLI was broken for local endpoints because for our local model GETs (to generate the list): we assume the server supports the OpenAI-proxy style of `GET _/v1/models`, however we don't store local model endpoints with the `/v1` suffix since many of the local LLM inference servers don't use it.
This fixes the issue by appending a `/v1` in the model GET call if it doesn't exist (since on this call we're assuming OpenAI proxy anyways).
Working as intended:
=> fix: patch vllm/local endpoint model GET bug

memgpt/server/rest_api/server.py
Previously we were printing an object reference (instead of mimicking the equivalent subprocess command).
=> fix: update print statement on server

.github/workflows/tests.yml, .pre-commit-config.yaml, compose.yaml, configs/server_config.yaml, db/run_postgres.sh, init.sql, memgpt/agent_store/db.py, memgpt/cli/cli.py, memgpt/metadata.py, memgpt/server/rest_api/server.py, memgpt/server/rest_api/sources/index.py, tests/test_client.py
This PR allows developers to run a memgpt service with `docker compose up`. 
The service is configured by the following environment variables (can be set in a `.env` file): 
```
MEMGPT_PG_DB=memgpt
MEMGPT_PG_USER=memgpt
MEMGPT_PG_PASSWORD=memgpt
MEMGPT_SERVER_PASS=test_server_token
```
If so, please break up …
=> feat: create memgpt server with postgres DB with `docker compose up` 

configs/server_config.yaml, memgpt/agent.py, memgpt/agent_store/db.py, memgpt/client/client.py, memgpt/data_types.py, memgpt/functions/function_sets/base.py, memgpt/metadata.py, memgpt/persistence_manager.py, memgpt/server/rest_api/agents/message.py, memgpt/server/rest_api/interface.py, memgpt/server/server.py, memgpt/utils.py
1. Create an agent
`agent_id = f30a410d-f4d2-4e18-bc0f-bdf5f6248144`
2. Get `GET /api/agents/f30a410d-f4d2-4e18-bc0f-bdf5f6248144/messages-cursor?limit=10`
```
% curl --request GET \
--url 'http://localhost:8283/api/agents/f30a410d-f4d2-4e18-bc0f-bdf5f6248144/messages-cursor?limit=10' \
--header 'authorization: Bearer banana'
```
```json
{
"messages":[
{"id":"70df5474-596c-4e5d-86b7-e344d3ec7820","user_id":"00000000-0000-0000-0000-a61b692e9d3b","agent_id":"f30a410d-f4d2-4e18-bc0f-bdf5f6248144","text":"{\"type\": \"login\", \"last_login\": \"Never (first login)\", \"time\": \"2024-03-21 09:44:09 PM PDT-0700\"}","model":"gpt-4","created_at":"2024-03-22T04:44:09.959669","role":"user","name":null,"embedding":null,"embedding_dim":null,"embedding_model":null …
```
=> fix: patch out-of-sync / missing tzinfo timestamps coming back from API server

memgpt/cli/cli_config.py, memgpt/local_llm/chat_completion_proxy.py, memgpt/local_llm/constants.py, memgpt/local_llm/groq/api.py, memgpt/local_llm/json_parser.py, paper_experiments/nested_kv_task/nested_kv.py, tests/test_json_parsers.py
Adds Groq API support.
Note: Groq API doesn't support either function calling OR a raw `/completions` (not `/chat/completions`) API route. Because of this, we need to package our MemGPT prompt into a dummy user message inside the `/chat/completions` payload - this is very similar to how the `lmstudio-legacy` option works.
TODO in the future once Groq's API either allows function calling (and it stable / works well) and/or adds support for raw `/completions` endpoints, we should deprecate this code into `groq-legacy` similar to `lmstudio-legacy`.
```
(pymemgpt-PCQPn4ce-py3.10) (base) loaner@MacBook-Pro-55 MemGPT-2 % memgpt configure
Loading config from /Users/loaner/.memgpt/config
? Select LLM inference provider: local
? …
```
=> feat: added groq support via local option w/ auth

memgpt/data_sources/connectors.py, paper_experiments/nested_kv_task/nested_kv.py
Bug Fix for https://github.com/cpacker/MemGPT/issues/1197
Try to load two files that would chunk to same text. Both will produce the same embedding. Insert Many will fail because of constraint violation.
Yes
[Issue](https://github.com/cpacker/MemGPT/issues/1197)
=> fix: duplicate passage across/within files causing issues in insert_many with postgres

tests/test_server.py
Loosen test to fix non-deterministic unit test, eg see failure in: https://github.com/cpacker/MemGPT/actions/runs/8544849064/job/23411836736
```
assert passages_1[0]["text"] == "alpha"
>       assert len(passages_2) == 3
E       AssertionError: assert 4 == 3
E        +  where 4 = len([{'agent_id': UUID('48249189-c3d0-490f-a3ea-b0f4a6336518'), 'created_at': datetime.datetime(2024, 4, 3, 20, 8, 21, 422464, tzinfo=datetime.timezone.utc), 'data_source': 'test_source', 'doc_id': UUID('c4f43552-5cee-cf6b-cd4f-667287a2a23f'), ...}, {'agent_id': UUID('48249189-c3d0-490f-a3ea-b0f4a6336518'), 'created_at': datetime.datetime(2024, 4, 3, 20, 8, 55, 972034, tzinfo=datetime.timezone.utc), 'data_source': None, 'doc_id': None, ...}, {'agent_id': UUID('48249189-c3d0-490f-a3ea-b0f4a6336518'), 'created_at': …
```
=> fix: Update test_server.py

memgpt/cli/cli_config.py, memgpt/credentials.py, memgpt/data_types.py, memgpt/llm_api/anthropic.py, memgpt/llm_api/llm_api_tools.py, memgpt/local_llm/constants.py
Adds official support for Claude API via the beta tool-calling API (https://docs.anthropic.com/claude/docs/tool-use).
Note: Claude 3 (at least Opus and Sonnet) like to call a core memory edit on the very first message, **so you may need to run with `--no-verify`**.
Example use:
```
% memgpt configure              
Loading config from /Users/loaner/.memgpt/config
? Select LLM inference provider: anthropic
? Enter your Anthropic API key (starts with 'sk-', see https://console.anthropic.com/settings/keys): *********
? Override default endpoint: https://api.anthropic.com/v1
? Select default model: claude-3-opus-20240229
Got context window 200000 for model claude-3-opus-20240229
? Select your model's context window (see https://docs.anthropic.com/claude/docs/models-overview): 200000
? Select …
```
=> feat: Anthropic Claude API support

memgpt/cli/cli_config.py, memgpt/credentials.py, memgpt/data_types.py, memgpt/llm_api/cohere.py, memgpt/llm_api/llm_api_tools.py, tests/test_server.py
```
% memgpt configure
Loading config from /Users/loaner/.memgpt/config
? Select LLM inference provider: cohere
? Enter your Cohere API key (see https://dashboard.cohere.com/api-keys): ****************************************
? Override default endpoint: https://api.cohere.ai/v1
? Select default model: command-r-plus
Got context window 116000 for model command-r-plus
? Select your model's context window (see https://docs.cohere.com/docs/command-r): 116000
? Select embedding provider: openai
? Select default preset: memgpt_chat
? Select default persona: sam_pov
? Select default human: basic
? Select storage backend for archival data: chroma
? Select chroma backend: persistent
? Select storage backend for recall data: sqlite
📖 Saving config to /Users/loaner/.memgpt/config
```
```
% memgpt …
```
=> feat: add Cohere API support (Command-R+)

memgpt/cli/cli_config.py, memgpt/server/rest_api/sources/index.py
When there is no `~/.memgpt/config` file, the fields `config.default_embedding_config` and `config.default_llm_config` are set to `None` -- this causes errors when the configure command tries to fill in default values. 
`poetry run memgpt configure`
Yes 
None
=> fix: errors on getting default config values on fresh install 

memgpt/autogen/memgpt_agent.py
Fixes attaching memory in scripts
https://github.com/cpacker/MemGPT/issues/1254
```python
software_engineering_expert = create_memgpt_autogen_agent_from_config(
"Chad - Software Engineering Lead",
llm_config=llm_config_memgpt,
system_message=f"Chad, you are a seasoned software engineering lead with extensive experience in managing complex projects. Your role is to oversee the quality of software development, ensuring that all implementations meet high standards. Challenge incomplete information and push for optimal solutions. Engage with other agents to enhance the software features based on engineering best practices. If unsure, admit it freely, but always aim to provide valuable feedback and direction.",
interface_kwargs=interface_kwargs,
skip_verify=False,  # NOTE: you should set this …
```
=> fix: Fixed NameError: name 'attach' is not defined

CONTRIBUTING.md, Dockerfile, compose.yaml, configs/server_config.yaml, development.compose.yml
Migrated from #1235 / #1233
This breaks out running server via compose from development in compose. The running server is exposed at [memgpt.localhost](http://memgpt.localhost)
- `docker compose up` to run 
- `docker compose -f compose.yaml -f development.compose.yml up` to run as development
there are still some decisions to be made for in-container development to be 100% usable - testing/linting is clunky and we probably want some helper tooling in a separate PR.
=> fix: Docker Via Reverse Proxy

memgpt/cli/cli_config.py, memgpt/client/client.py, memgpt/config.py, memgpt/data_sources/connectors.py, memgpt/metadata.py, memgpt/models/pydantic_models.py, memgpt/server/rest_api/admin/users.py, memgpt/server/rest_api/server.py, memgpt/server/rest_api/sources/index.py, poetry.lock, pyproject.toml, tests/test_client.py
Allow for offline processing of uploaded data via REST API using background tasks. 
`pytest -s tests/test_client.py`
Yes
=> feat: use background tasks for processing uploaded files to REST API 

.github/workflows/docker-integration-tests.yaml, .github/workflows/tests.yml, compose.yaml, configs/server_config.yaml, dev-compose.yaml, memgpt/cli/cli_config.py, memgpt/client/client.py, memgpt/credentials.py, memgpt/server/rest_api/agents/index.py, memgpt/server/rest_api/server.py, memgpt/server/server.py, poetry.lock, scripts/wait_for_service.sh, tests/test_admin_client.py, tests/test_client.py
This PR adds integration tests for the MemGPT server docker container. 
* Run integration tests that build a container with the local code, run the container to create a MemGPT service, and test it with the client-side tests. 
* Remove the need for a client to have a local `~/.memgpt/config` if the client is simply connecting to a MemGPT service 
* Allow passing in the server URI with `MEMGPT_SERVER_URL` to `test_client.py`
The development container can be built and run with: 
```
docker compose -f dev-compose.yaml up --build -d
```
Test data is contained in the `./.persist/pgdata-test` folder. 
Tests added in `.github/workflows/docker-integration-tests.yaml`
Yes
=> feat: add workflow to build + test docker container 

docs/data_sources.md
Fix typo in URL to Storage Backend config docs
Fix typo
Test it in readthedocs 
No
no
Currently the link goes to 404, this should fix it.
=> docs: Documentation Typo in Storage URL

memgpt/cli/cli.py
```
SCRIPT /Users/loaner/dev/MemGPT-2/memgpt/cli
FILE PATH /Users/loaner/dev/MemGPT-2/memgpt/cli/../../configs/memgpt_hosted.json
{'context_window': 16384, 'model_endpoint_type': 'openai', 'model_endpoint': 'https://inference.memgpt.ai', 'model': 'memgpt-openai', 'embedding_endpoint_type': 'hugging-face', 'embedding_endpoint': 'https://embeddings.memgpt.ai', 'embedding_model': 'BAAI/bge-large-en-v1.5', 'embedding_dim': 1024, 'embedding_chunk_size': 300}
📖 MemGPT configuration file updated!
🧠 model        -> memgpt-openai
🖥️  endpoint     -> https://inference.memgpt.ai
⚡ Run "memgpt run" to create an agent with the new config.
```
=> fix: cleanup stray prints

memgpt/server/rest_api/static_files.py
Not sure if the best way to do it, but this resolved the issue with locating the static files to resolve.
Fix a bug (see below)
Install memgpt via pip and run `memgpt server` from a different directory than where the memgpt package is installed.
Yes.  The path to the static path comes back correct and dev portal works.
[#1339]
Nope.
None that I can think of.
=> fix: Update static_files.py

memgpt/prompts/system/memgpt_base.txt
Corrects a typo error in the system prompt text.
- **Affected File**: `memgpt/prompts/system/memgpt_base.txt`
- **Modification**:
- Original: `Stores key details about the person you're are conversing with`
- Corrected: `Stores key details about the person you are conversing with`
The original text contained a grammatical redundancy ("you're are"). Correcting this to "you are" eliminates confusion and improves the text's clarity.
This change is purely textual and does not affect any underlying code or functionality, ensuring no impact on system performance or stability.
- No code testing is necessary as the changes are text-only.
- Verified that the corrected text displays correctly.
Although minor, this correction contributes to a more professional user interface. Looking forward to your …
=> fix: patch typos in system prompt

README.md
This PR is for updating the github link to clone that repo that is listed in the readme.md file.
I have updated it to `https://github.com/cpacker/MemGPT.git` which is what should be used for users who don't own the repo.
Just try the new clone commad listed in the readme.md file.
Yes, I have tested and clone link works fine now.
None
Nope
None
=> docs: Update git clone link in README.md 

memgpt/agent_store/db.py, memgpt/settings.py
Patch bugs that broke tests in PR #1355
=> fix: patch #1355

README.md
Update readme for better developer experience:
- Add Twitter follow @MemGPT button
- Consolidate call-to-action items into "How to get involved" section, including:
- Merge "Support" section
- Merge "Roadmap" section
- Link Berkeley LLM meetup as MemGPT event calendar
- Remove Documentation section (duplicate of the top documentation button)
- Move legal notice to the bottom
n/a
n/a
Please link any related GitHub [issues](https://github.com/cpacker/MemGPT/issues) or …
=> docs: update README: Twitter Button, Consolidate call-to-action, Reorganize Content

docs/storage.md
Adds a note to remind people to update the port in the connection string if using the docker.  I had missed that step.
=> docs: Update storage.md

.github/workflows/tests.yml, docs/storage.md, memgpt/agent_store/milvus.py, memgpt/agent_store/storage.py, memgpt/cli/cli_config.py, poetry.lock, pyproject.toml, tests/test_load_archival.py, tests/test_storage.py
Description
This PR adds support for Milvus - https://milvus.io/docs to be used as an archival storage connector.
Tests
Have tested successfully in local environment for tests/test_storage.py. and tests/test_load_archival.py
=> feat: Milvus storage connector

memgpt/functions/functions.py
This PR is a quick fix for a bug discovered in the MemGPT Dev Portal's Tool Builder.
The bug occurs when attempting to add a new tool to through the web interface and the source code happens to be invalid. The `write_function` still creates the python file in the user functions directory despite the result of `validation_function`. When attempting to update the tool it appends the source code in the end of the file, instead of the expected behaviour of overwriting it.
=> fix: creation of invalid tool in tool builder

memgpt/llm_api/llm_api_tools.py
https://platform.openai.com/docs/guides/text-generation/json-mode
JSON mode only supported by: gpt-4o, gpt-4-turbo, or gpt-3.5-turbo
Patch for #1401
=> fix: patch #1401

docs/python_client.md
response = client.user_message(agent_id=agent_state.id, message=message)
NameError: name 'agent_state' is not defined
=> docs: Update python_client.md

examples/memgpt_client.py
print(f"User {user_id} has keys: {get_keys_response.api_key_list}")
AttributeError: 'list' object has no attribute 'api_key_list'
with the git clone of the latest main get_keys_response is a list not a dict
=> fix: get_keys_response is a list not a dict

README.md
When following the [server quickstart](https://github.com/cpacker/MemGPT/tree/0.3.15?tab=readme-ov-file#quickstart-server) instructions as is, `$ docker compose up` yields the following due to `.env` not being included in the repo except in the form of `env.example`. (Not a great out-of-the-box experience.) This PR adds a simple step on managing `.env`. It's not clear this is the best way to handle this, but at least takes care of the warnings and fatal error.
```
WARN[0000] The "MEMGPT_PG_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MEMGPT_PG_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MEMGPT_PG_DB" variable is not set. …
```
=> docs: update quickstart-server instructions

configs/server_config.yaml, examples/resend_example/README.md, examples/resend_example/resend_preset.yaml, examples/resend_example/resend_send_email_env_vars.py
Example showing how to use `resend` to connect MemGPT to the `resend` API (to send emails).
=> feat: `resend` example

memgpt/cli/cli_config.py, memgpt/client/admin.py, memgpt/functions/functions.py, memgpt/local_llm/llm_chat_completion_wrappers/configurable_wrapper.py, memgpt/presets/presets.py, memgpt/server/rest_api/server.py, memgpt/utils.py
this is a pull request to fix https://github.com/cpacker/MemGPT/issues/1270
Just simply append encoding='utf-8' for all non-binary open
Yes, tested in my non-English windows machine.
https://github.com/cpacker/MemGPT/issues/1270
No
=> fix: Append encoding='utf-8' to open 

memgpt/local_llm/llm_chat_completion_wrappers/simple_summary_wrapper.py
Fixes https://github.com/cpacker/MemGPT/issues/1261
Use ollama and the default dolphin model and spam the chat until it hits the context window limit and an automatic `/summarize` is triggered. Alternatively, just use `/summarize`.
Yes
No
=> fix: simple_summary_wrapper function_call KeyError

memgpt/data_types.py, memgpt/llm_api/anthropic.py, memgpt/llm_api/google_ai.py, memgpt/local_llm/grammars/gbnf_grammar_generator.py
Partially closes (see particular comment) https://github.com/cpacker/MemGPT/issues/799#issuecomment-2183956679
=> fix: add `ensure_ascii` to missing `json.dumps` calls

memgpt/main.py
Closes #1470 
```
🎉 Created new agent 'YieldingLlama' (id=1d9b36d1-beaf-4a68-9c4c-5bec7dc1bcd2)
Hit enter to begin (will request first MemGPT message)
💭 First user login detected. It's Chad. Initiate a warm greeting. Let's establish a friendly connection right from the start. Show curiosity and 
interest in his day.
🤖 Hello, Chad! It's a joy to make your acquaintance. How has your day been unfolding so far?
> Enter your message: /pop
Popping last 3 messages from stack
> Enter your message: /dump
...
[2] 💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
🤖 More human than human is our motto.
[1] ⚡ [function] {"status": "OK", "message": null, "time": "2024-06-22 01:17:58 PM PDT-0700"}
> Enter your message: …
```
=> fix: patch `/pop`, `/retry`, and `/rethink`

memgpt/client/admin.py, memgpt/client/client.py, memgpt/metadata.py, memgpt/models/pydantic_models.py, memgpt/server/rest_api/admin/tools.py, memgpt/server/rest_api/tools/index.py, memgpt/server/server.py, tests/test_tools.py
Instead of requring tools to be global and created by the administrator, this PR makes it possible to create user-specific tools from the user client. The administrator can also create global tools, where `user_id=None`. 
`poetry run pytest -s tests/test_tools.py`
=> feat: move tool functions to user 

memgpt/client/admin.py, memgpt/server/rest_api/admin/users.py
Ensure that the GET request does not expect a body and correctly handles the parameters as part of the query string
poetry run pytest -s tests
NA
NA
No
NA
=> fix: use params in get_all_users(GET) endpoint

memgpt/agent.py, memgpt/cli/cli.py, memgpt/data_types.py, memgpt/llm_api/llm_api_tools.py, memgpt/main.py, memgpt/models/pydantic_models.py
TODOs:
Refactor code to convert to inner thought kwarg format
- See note*
- Add utility to convert `ToolCall`s into versions that have a kwarg included (`add_inner_thoughts_to_tool_call`)
- Add flag `put_inner_thoughts_in_kwargs` to `Message.to_openai_dict` which will call utility to make put `self.text` (the `content` / inner thoughts) into `ToolCall`s via the utility
- `add_inner_thoughts_to_functions`
- `unpack_inner_thoughts_from_kwargs`
- I added a `--no-content` flag (`yes` = put inner thoughts in kwargs, `no` = leave as normal (gpt4 style), `default` = let us decide, eg for gpt4o turn it on, for gpt4 turn it off)
*note: I was going to create a `Message -> Message` utility function that puts `self.text` into `self.tool_calls` (as an alternative to putting the logic for extracting …
=> feat: patch missing inner thoughts on new openai models

memgpt/config.py, memgpt/server/server.py
Adding CORE_MEMORY_HUMAN_CHAR_LIMIT and CORE_MEMORY_PERSONA_CHAR_LIMIT to the /config response
so they can be used to dynamically adjust the frontend text area limits
If so, please break up your PR into multiple smaller PRs so that we can review them quickly, or …
=> feat: add character limits for persona/human to /config response

memgpt/agent_store/db.py
The sort expression should not change even if we reverse the order of the items a date before should still be a date before the initial sort takes care of everything we need already
There's a bug in the cursor api for messages. if reverse is set to true the sort expressions are also reversed, this is actually incorrect. I attached a drawing below that explains why
Here is a diagram that shows why simply removing it works
The comparison stays the same, regardless of how we order the records
=> fix: don't reverse the sort expression

memgpt/server/rest_api/agents/index.py
Fix bug
Create agent API, pass system field to set the agents system (prompt).
Use admin site and create agent, should work as normal as it does not send a system field.
Agent saves the system given to it.
If so, please break up your PR into multiple smaller PRs …
=> feat: changes create agent API to accept optional system value.

memgpt/agent.py, memgpt/constants.py, memgpt/prompts/system/memgpt_chat_fstring.txt
Refactors the way system messages are compiled to set the foundation for system message templating.
This PR allows for system messages that have the reserved variable `{CORE_MEMORY}` in them.
1. If `{CORE_MEMORY}` exists in the system prompt, the system prompt will be formatted such that the core memory block is injected there
2. If `{CORE_MEMORY}`  does not exist in the system prompt, it'll automatically be appended to the end of the system prompt (**this makes this PR backwards compatible**)
Future PRs should enable users to define their own variables via `user_defined_variables` (TBD where this should be stored in the DB), which can be used to 
Also, a future PR should enable other templating styles other than just f-strings, e.g. …
=> feat: allow templated system messages

memgpt/agent.py, memgpt/main.py, memgpt/server/server.py
Closes #1583 
```
```
Note: PR has been revised to only include a CLI command for swapping system messages until #1579 is merged.
This route should also be used in the dev portal when we expose system prompt templating.
Example 1: swap the MemGPT system prompt with a short system prompt that tells the LLM to call `send_message`:
```
% memgpt run
->  🛠️  8 tools: send_message, pause_heartbeats, conversation_search, conversation_search_date, archival_memory_insert, archival_memory_search, core_memory_append, core_memory_replace
🎉 Created new agent 'FluffyRooster' …
```
=> feat: allow editing the system prompt of an agent post-creation

memgpt/server/rest_api/openai_chat_completions/chat_completions.py
Bug fix
I am not sure that hard coding the stream_legacy to False is appropriate, open to feedback. 
```
curl --location 'http://localhost:8083/v1/chat/completions' \
--header 'Authorization: Bearer <TOKEN>' \
--header 'Content-Type: application/json' \
--data '{
"messages": [
{
"id": "UnzuNq8",
"createdAt": "2024-07-29T14:14:10.412Z",
"role": "user",
"content": "ssssss"
}
],
"user": "355e3a6a-7176-42d6-a4b0-09db2d202a0f",
"model":"gpt-4o",
"requestData": {}
}'
```
Yes
```
dotenv run -- memgpt server …
```
=> fix: Address exception `send_message_to_agent() missing 1 required positional argument: 'stream_legacy'` on 'v1/chat/completions'

memgpt/cli/cli.py
Allow setting the core memory limit in the CLI: 
```
memgpt run --core-memory-limit 6000 --persona diana
```
=> feat: allow setting core memory limit in CLI

memgpt/cli/cli_config.py
Fix a bug with the `memgpt list sources` CLI command. 
In a fresh project, you can load a simple data source and run `memgpt list sources` which should break with `AttributeError: 'SourceModel' object has no attribute 'embedding_dim'. Did you mean: 'embedding_config'?`
Yes. Tested this change using
```
memgpt load directory --name test --input-dir ~/testing/memgpt_data_sources
memgpt list sources
```
https://github.com/cpacker/MemGPT/issues/1587
=> fix: read embedding_model and embedding_dim from embedding_config

memgpt/cli/cli.py, memgpt/cli/cli_config.py, memgpt/memory.py
Please describe the purpose of this pull request.
I should learn how to use git better..
Changes the cli_config.py broke the delete agent functionality. LocalClient.delete_agent() expects an agent id to be provided but code provides the agent name.
Adds code to allow a text file to be used to import the system prompt from memgpt run for use in new agent creation.
How to test
Try to delete an agent without change. LocalClient will respond back with:
LocalClient.delete_agent() got an unexpected keyword argument 'agent_name'
Apply fix and try again.
memgpt run --system-file <name of text file>
Will load the text file during new agent creation.
Have you tested this PR?
Yes, it works.
Related issues or PRs
Please link any related GitHub issues or PRs.
Is your PR over 500 lines of code?
Nope …
=> feat: Fix CLI agent delete functionality & allow importation of file for system prompt - attempt #2

memgpt/client/client.py, memgpt/server/server.py, tests/test_new_client.py
=> feat: passing tests but memory access is weird

memgpt/local_llm/json_parser.py
Fixes a couple of small syntax warnings that appear on startup of the memgpt server (in dev). 
```
memgpt_server-1  | Starting MEMGPT server...
memgpt_server-1  | /memgpt/local_llm/json_parser.py:21: SyntaxWarning: invalid escape sequence '\_'
memgpt_server-1  |   """Handles the case of escaped underscores, e.g.:
memgpt_server-1  | /memgpt/local_llm/json_parser.py:29: SyntaxWarning: invalid escape sequence '\_'
memgpt_server-1  |   return string.replace("\_", "_")
```
You can run the service locally and see that the syntax warnings are no longer in the logs. `docker compose -f dev-compose.yaml up --build`
Yes! Output is just the "starting" line without the syntax warnings. 
``` …
```
=> fix: syntax warning on startup

examples/notebooks/multi_agent.ipynb
=> feat: add example notebooks

memgpt/client/client.py, memgpt/functions/function_sets/base.py, memgpt/server/rest_api/interface.py, tests/test_new_client.py
keep both message objects and message api dicts in the buffer so that we can return a list of messages when needed
note: proper way to do this is probably by keeping message IDs in the buffer, and reconstructing them just before the return
=> fix: keep `Message` objects in the `QueueingInterface` so that they can be returned to the Python client

.gitignore, memgpt/agent.py, memgpt/cli/cli_config.py, memgpt/client/client.py, memgpt/functions/schema_generator.py, memgpt/main.py, memgpt/metadata.py, memgpt/schemas/memory.py, memgpt/schemas/tool.py, memgpt/server/server.py, tests/test_new_client.py
This is the first step in adding shared blocks functionality. To share blocks between agents we need to make sure block data is persisted in a normalized fashion outside of the agent memory.
Tested with `poetry run pytest -s tests/test_new_client.py` and validated manually that blocks are being added on every agent create. 
I have a few followups before this is ready to merge, like where the best place to add tests is.
yes! see above
Please link any related GitHub …
=> feat: persist agent blocks

memgpt/llm_api/openai.py, memgpt/server/rest_api/agents/message.py
Fix a bug when streaming tokens.
Yes this is needed for dev portal streaming to work
Add any other context …
=> fix: add correct dependencies and missing variable

memgpt/llm_api/llm_api_tools.py, memgpt/local_llm/utils.py, memgpt/server/rest_api/agents/message.py, memgpt/server/rest_api/interface.py
Currently, the dev portal is written to always ask for a stream reply, and if the backend doesn't support streaming, we send back a very similar looking data streaming, but instead of having N chunks for N tokens, we just send back 1 chunk per message ("fake streaming").
This is as intended, however the backend is currently incorrectly coded - it sees the request for `stream_tokens`, and sets up a streaming tokens compatible interface to get ready to send the response. However, in the case of the free MemGPT inference server, this is set up as an OAI proxy (`llm_config.endpoint_type == 'openai'`), so the related LLM API code thinks that we can actually support streaming, and turns on the streaming listeners. However, the proxy backend does not actually support streaming.
We need to figure …
=> fix: patches to the API for non-streaming OAI proxy backends

memgpt/agent.py, memgpt/schemas/memory.py, tests/test_client.py, tests/test_tools.py
tl;dr `Memory.__str__()` is now `Memory.compile()`
Move the prompt string generation to a dedicated non-overloaded function, since it's confusing to have potential complex logic handled behind an overloaded `__str__`. [PLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
Follow-up PR will modify prompt string generation logic to be via a templating engine (eg jinja2) if possible to enable easier visualization and modification of the prompt generation in the frontend (vs passing python code back and forth).
=> refactor: move prompt string generation in `Memory` to a non-overloaded function

memgpt/schemas/message.py, memgpt/server/server.py, tests/test_client.py, tests/test_new_client.py
1. `core_memory_replace` and `core_memory_append` are currently broken (when run via the `Agent` object, not via the unit tests which test the memory objects in isolation)
- As a side note, we should add tests for the basic functions that run off of the `Agent` object, otherwise this sort of regression can happen and we don't catch it with `test_memory.py`
3. As a separate issue, I noticed that `Message.text` isn't optional (I feel like it was at some point?). This should probably be optional since many LLM APIs that do tool calling will make the `content` field (our `text` field) `== null` when doing tool calling. Groq for example does/did this - no inner monologue during tool calling (so inner monologue needs to get stuffed into the tool call itself).
```
🎉 Created new agent …
```
=> fix: patch core memory edit bug/regression

memgpt/agent.py, memgpt/client/client.py, memgpt/constants.py, memgpt/llm_api/llm_api_tools.py, memgpt/llm_api/openai.py, memgpt/memory.py, memgpt/schemas/enums.py, memgpt/schemas/memgpt_message.py, memgpt/schemas/memgpt_request.py, memgpt/schemas/message.py, memgpt/server/rest_api/agents/message.py, memgpt/server/rest_api/interface.py, memgpt/server/rest_api/utils.py, memgpt/server/server.py, memgpt/streaming_interface.py
- Test that the POST routes work (no errors, basic message comes back OK)
- Test that the `id` and `created_at` that get returned on the POST SSE stream are the same as what we get with a subsequent `cursor` fetch (this makes sure that the persistence code worked)
=> fix: patch streaming API code

memgpt/agent.py, memgpt/autogen/memgpt_agent.py, memgpt/memory.py
This is in anticipation of adding future agent types, e.g. see: https://github.com/cpacker/MemGPT/pull/1700
I was going to rename symbol `Agent` to `MemGPTAgent`, but decided we may want to punt that until the integration branch is merged to avoid a huge file diff on this PR.
=> feat: create an abstract agent type + cleanup typing errors in `memory.py`

memgpt/schemas/memory.py
This is probably a cleaner way to view the prompt template.
Alternatively we can even remove the `memory` dict and instead make it a `List[Block]` (since we now have `get_block`)
=> refactor: remove the concept of 'section' from the jinja2 prompt formatter

memgpt/schemas/message.py
`/dump` and `/dumpraw` weren't showing inner thoughts because we accidentally left the `put_inner_thouguhts_in_kwargs` on by default in the `to_openai_dict` converter.
=> fix: fix dump and dumpraw

memgpt/server/rest_api/app.py, memgpt/server/rest_api/static_files.py
tldr of bug is:
- enable static file mounting, the website works fine (and API routes via the website work fine), but the RESTClient unit tests start failing with "Method Not Allowed", indicating that the request is getting hijacked by the static files mount
- disable static file mounting (can even try just commenting it out), and the RESTClient unit tests pass again
To check if the website is working: `memgpt server` then `localhost:8283` should spawn the SPA
To check if the RESTClient unit tests are working, run `pytest -s -vvv tests/test_client.py::test_agent`
=> fix: static files mounting bug

memgpt/agent.py, memgpt/agent_store/chroma.py, memgpt/agent_store/milvus.py, memgpt/agent_store/qdrant.py
There's a weird bug @4shub encountered where some messages are `None` / don't exist in recall:
```sh
File "/Users/shub/Developer/MemGPT/memgpt/server/rest_api/routers/v1/agents.py", line 88, in get_agent_state
return server.get_agent_state(user_id=actor.id, agent_id=agent_id)
File "/Users/shub/Developer/MemGPT/memgpt/server/server.py", line 1172, in get_agent_state
memgpt_agent = self._get_or_load_agent(agent_id=agent_id)
File "/Users/shub/Developer/MemGPT/memgpt/server/server.py", line 298, in _get_or_load_agent
memgpt_agent = self._load_agent(user_id=user_id, agent_id=agent_id)
File "/Users/shub/Developer/MemGPT/memgpt/server/server.py", line 275, in _load_agent
memgpt_agent = Agent(agent_state=agent_state, interface=interface, tools=tool_objs)
File …
```
=> fix: patch recall error

memgpt/agent.py, memgpt/agent_store/chroma.py, memgpt/agent_store/milvus.py, memgpt/agent_store/qdrant.py, memgpt/schemas/memgpt_message.py, memgpt/server/rest_api/routers/v1/agents.py
Attempt to patch (using "discriminated union" concept):
- Add `message_type` field to every subclass of `MemGPTMessage`
- Add a union type that uses the `message_type` as the discriminator
New error (post initial fix):
- Pydantic is dropping the fields other than `id` and `date` when returning the message types
- It looks like we actually need to use a `Union` type in the response model
- The correct way to do this is "discriminated unions"?
- https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions
Initial error:
```sh
File "/Users/shub/Library/Caches/pypoetry/virtualenvs/pymemgpt-kfuQswAM-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 155, in serialize_response
raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 11 validation errors: …
```
=> fix: patch validation error on `/messages` endpoint

memgpt/server/rest_api/app.py, memgpt/server/rest_api/utils.py
We're creating a new server instance for every request right now. Hotfix to pull from globals until we properly strip state out of the server.
=> fix: server memory leak

memgpt/server/rest_api/app.py, memgpt/server/server.py
Adds basic support for reading `user_id` from the header of the HTTP request.
Note: implementation is not thread safe and will be / needs to be refactored alongside the stateless server refactor.
**How to test.**
Test no header:
```sh
$ curl --request GET \
--url http://localhost:8283/v1/models/ \
--header 'accept: application/json'
[{"model":"gpt-4","model_endpoint_type":"openai","model_endpoint":"https://api.openai.com/v1","model_wrapper":null,"context_window":8192}]%
```
Test header with bad ID (no user exists):
```sh
$ curl --request GET \
--url http://localhost:8283/v1/models/ \
--header 'user_id: 0x0'
{"detail":"User with id 0x0 not found"}%
```
Test header with existing ID (the config one): …
=> feat: add support for `user_id` in header

memgpt/agent.py, memgpt/main.py, memgpt/schemas/agent.py, memgpt/server/server.py
Initial stab at cleaning up the agent step by removing dead code + turning the response into a response model instead of a tuple.
Follow-up PRs should do the following cleanup:
- This ensures that `step` corresponds to a single LLM call (unless a summarization happens, in which case we probably want to return a dual usage? or put a summarization event into the response model?)
=> refactor: clean up `agent.step()`

configs/server_config.yaml, locust_test.py, memgpt/agent_store/db.py, memgpt/metadata.py, memgpt/server/server.py
This centralizes the session manager used by SQLAlchemy, and resolves the connection errors that the locust tests were generating. 
Run `poetry run locust -f locust_test.py` with docker - test on ~100 users (20 requests / s)
Yes
=> fix: fix DB session management to avoid connection overflow error

letta/cli/cli.py
-change agent_state.state to agent_state.name
-initialized tools before before using it
Bug
1. Run a new agent from CLI.
2. Stop and rerun with the existing agent.
3. Should show "Hit enter to begin (will request first Letta message)"
=> fix: fixed bug when existing agent state is loaded via cli

.github/workflows/tests.yml, letta/functions/helpers.py, letta/functions/schema_generator.py, letta/schemas/tool.py, poetry.lock, pyproject.toml, tests/test_new_client.py
Enable importing LangChain tools with arguments. Previously, we could only use tools (if any existed) that didn't have any required arguments to use. 
Note: we change the usage of `from_langchain` in `tool.py`. It now has an optional parameter:
```
additional_module_attr_import_map (dict[str, str]): A mapping of module names to attribute name. This is used internally to import all the required classes for the langchain tool. For example, you would pass in `{"langchain_community.utilities": "WikipediaAPIWrapper"}` for `from langchain_community.tools import WikipediaQueryRun`. NOTE: You do NOT need to specify the tool import here, that is done automatically for you.
```
Example usage:
```
api_wrapper = WikipediaAPIWrapper(top_k_results=1, doc_content_chars_max=100)
langchain_tool = …
```
=> fix: Enable importing LangChain tools with arguments

letta/agent.py
Check that content is not None before setting to internal_monologue. This is causing intermittent errors sometimes with our testing, where sometimes the model does not use the `content` field:
```
=========================== short test summary info ============================
FAILED tests/test_tools.py::test_create_agent_tool[client0] - ValueError: Failed to send message: {"detail":"1 validation error for InternalMonologue\ninternal_monologue\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/string_type"}
================== 1 failed, 2 passed, 36 warnings in 16.10s ===================
```
Additionally, we also search for `inner_thoughts` in the function args - community members …
=> fix: Check that content is not None before setting to internal_monologue

examples/crewai_tool_usage.py, examples/langchain_tool_usage.py, letta/functions/helpers.py, letta/schemas/tool.py, tests/test_new_client.py
Adapt crewAI to also accept parameterized tools and add example. 
```
crewai_tool = ScrapeWebsiteTool(website_url="https://www.example.com")
example_website_scrape_tool = Tool.from_crewai(crewai_tool)
```
Wrote tests covering:
- Use a crewAI tool with a parameter
- Adapt existing crewAI tests to use a more stable example website
- E2E example of an agent invoking a `ScrapeWebsiteTool` from crewAI and run it manually
=> feat: Adapt crewAI to also accept parameterized tools and add example

.github/workflows/tests.yml, examples/composio_tool_usage.py, letta/functions/helpers.py, letta/llm_api/openai.py, letta/schemas/tool.py, poetry.lock, pyproject.toml, tests/test_new_client.py
Add integration with Composio tools. We add a new class function `get_composio_tool` in the Letta `Tool` class.
```
tool = Tool.get_composio_tool(action=Action.GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER)
```
This tool can then be used by agents.
This mimics the composio `get_tools` API: https://docs.composio.dev/framework/langchain#use-specific-actions
We add a very simple unit test for compilation check for the tool's code gen.
We also introduce a E2E example that confirms the integration is working for `GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER`.
=> feat: Add integration with Composio tools

letta/server/rest_api/admin/tools.py, letta/server/rest_api/app.py, letta/server/rest_api/routers/openai/assistants/threads.py, letta/server/rest_api/routers/openai/chat_completions/chat_completions.py, letta/server/rest_api/routers/v1/agents.py, letta/server/rest_api/routers/v1/blocks.py, letta/server/rest_api/routers/v1/jobs.py, letta/server/rest_api/routers/v1/sources.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py
tl;dr refactor the way we get `user_id` from the header to be stateless (fixing a race condition bug)
---
Currently incoming requests get the `user_id` by polling the server for the current user with `get_current_user`, which reads from a variable:
```python
def get_current_user(self) -> User:
"""Returns the currently authed user.
Since server is the core gateway this needs to pass through server as the
first touchpoint.
"""
if hasattr(self, "_current_user") and self._current_user is not None:
current_user = self.get_user(self._current_user)
if not current_user:
warnings.warn(f"Provided user '{self._current_user}' not found, using default user")
else:
return current_user
return self.get_default_user()
```
This variable is set by middleware inside of `rest_api.app`:
```python …
```
=> refactor: remove `get_current_user` and replace with direct header read

docker-compose-vllm.yaml
Enable running Letta with vllm powered model with one command:
`export LETTA_LLM_MODEL=teknium/OpenHermes-2-Mistral-7B; docker compose -f docker-compose-vllm.yaml up `
Replace `teknium/OpenHermes-2-Mistral-7B` with your own model id
1. `export LETTA_LLM_MODEL=teknium/OpenHermes-2-Mistral-7B; docker compose -f docker-compose-vllm.yaml up `
2. Open http://localhost:8083/
3. Create an agent and chat with the agent. Note that the model is 7B so it is much less powerful than gpt-4o
Have you tested the latest commit on the PR? If so please provide …
=> Docker compose vllm

letta/server/rest_api/routers/openai/assistants/threads.py, letta/server/rest_api/routers/openai/chat_completions/chat_completions.py, letta/server/rest_api/routers/v1/agents.py, letta/server/rest_api/routers/v1/blocks.py, letta/server/rest_api/routers/v1/jobs.py, letta/server/rest_api/routers/v1/sources.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py
https://github.com/cpacker/MemGPT/issues/1825#issuecomment-2399779521
---
`letta server`
When you use an invalid `user_id` that doesn't exist:
```sh
% curl --request GET \
--url http://localhost:8283/v1/agents/ \
--header 'user_id: banana'
{"detail":"User with id banana not found"}
```
When you don't specify a `user_id` (server uses the default):
```sh
% curl --request GET \
--url http://localhost:8283/v1/agents/
[{"description":null,"metadata_":{"human":"basic","persona":"sam_pov"},"user_id":"user-00000000","id":"agent-16ffdc6b-fc6b-42...
```
When you specify a `user_id` (here I'm using the default):
```sh
% curl --request GET \
--url http://localhost:8283/v1/agents/ \
--header 'user_id: user-00000000'
[{"description":null,"metadata_":{"human":"basic","persona":"sam_pov"},"user_id":"user- …
```
=> fix: patch `user_id` in header

letta/agent.py
When users add tools upon the creation of an agent, the tools are required to be persisted to the DB for functionality. This PR addresses this by saving un-saved tools to the DB while saving the agent.
=> feat: persist tools to db when saving agent

letta/agent.py
#1847 added the ability to modify an agent's tools after it's been created, but calling the `link_tools` function does not update the `tools` attribute, causing a database error (since it never ends up getting written to db) when doing so. This PR addresses this by updating the `tools` attribute in `link_tools`.
=> fix: calling link_tools doesnt update agent.tools

letta/credentials.py, letta/llm_api/google_ai.py, letta/llm_api/helpers.py, letta/llm_api/llm_api_tools.py, letta/llm_api/openai.py, letta/providers.py, letta/schemas/openai/chat_completion_response.py, tests/configs/llm_model_configs/gemini-pro.json, tests/test_endpoints.py
Refactor Google AI Provider / helper functions and add endpoint test:
- Remove service_endpoint and standardize to base_url
- Factor out common functionality in the google_ai.py folder
This PR also factors out common logic making POST requests.
1. Ran new endpoint test to make sure we can get valid first message back from Gemini:
Command:
```
poetry run pytest -s -vv tests/test_endpoints.py::test_gemini_pro_15_returns_valid_first_message
```
Results:
```
id='32a7eb2a-4543-4f6e-a4ff-7124e286f068' choices=[Choice(finish_reason='function_call', index=0, message=Message(content='First time user. Interesting. Initiate friendly greeting.', tool_calls=[ToolCall(id='0fa9e056-56b3-48a4-aa02-37610', type='function', function=FunctionCall(arguments='{\n  "message": "Hello, Chad. What are you …
```
=> fix: refactor Google AI Provider / helper functions and add endpoint test

letta/agent.py, letta/main.py
Squashing two CLI `letta run` bugs on main
Bug 1: runtime error (`letta run` totally bricked)
```sh
? Select embedding model: text-embedding-ada-002
->  🛠️  8 tools: send_message, pause_heartbeats, conversation_search, conversation_search_date, archival_memory_insert, archival_memory_search, core_memory_append, core_memory_replace
🎉 Created new agent 'XenialXenophobia' (id=agent-50a02fce-472b-43c2-a815-8687d14ee952)
Hit enter to begin (will request first Letta message)
An exception occurred when running agent.step(): 
File "/Users/loaner/dev/MemGPT-fresh/letta/main.py", line 403, in run_agent_loop
new_messages, user_message, skip_next_user_input = process_agent_step(user_message, …
```
=> fix: CLI patches - patch runtime error on main loop + duplicate internal monologue

letta/embeddings.py, letta/llm_api/openai.py, letta/providers.py
Note: this is a fairly gross solution (remapping models names on the backend) but I don't want to add an additional field to the config objects until we have thought it through more carefully.
=> feat: cleanup display of free endpoint 

letta/constants.py, letta/providers.py
=> fix: add missing hardcodings for popular OpenAI models

alembic/env.py
Found a bug where the incorrect config object was being used:
```
(letta-py3.12) mattzhou@Matts-MacBook-Pro MemGPT % poetry run alembic upgrade head   
None
File "/Users/mattzhou/Library/Caches/pypoetry/virtualenvs/letta-Mdwnr1Ge-py3.12/bin/alembic", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/mattzhou/Library/Caches/pypoetry/virtualenvs/letta-Mdwnr1Ge-py3.12/lib/python3.12/site-packages/alembic/config.py", line 636, in main
CommandLine(prog=prog).main(argv=argv)
File "/Users/mattzhou/Library/Caches/pypoetry/virtualenvs/letta-Mdwnr1Ge-py3.12/lib/python3.12/site-packages/alembic/config.py", line 626, in main
self.run_cmd(cfg, options)
File "/Users/mattzhou/Library/Caches/pypoetry/virtualenvs/letta-Mdwnr1Ge-py3.12/lib/p …
```
=> fix: Fix config bug in alembic

letta/local_llm/chat_completion_proxy.py, letta/providers.py, letta/server/server.py, tests/test_providers.py
`OllamaProvider` had some errors including runtime errors on the context window / embedding size fetch, also it didn't properly set the model wrapper / prompt formatter.
=> fix: patch errors with `OllamaProvider`

letta/agent.py, letta/main.py, letta/server/server.py
Simplify `Agent.step` inputs to `Message` or `List[Message]` only
Note: previously `List` was not a valid input, despite the API docs making it seem like passing a list was possible
Added an additional convenience function `Agent.step_user_message` that wraps a user message (eg `"hello"`) in the JSON metadata (eg `{"type": "user_message", "message", "hi"}`)
=> refactor: simplify `Agent.step` inputs to `Message` or `List[Message]` only

letta/schemas/letta_request.py, letta/schemas/message.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py
- `POST /agents/messages` now hits `server.send_messages` which accepts a list properly
- `POST /agents/messages` now accepts types `List[Message]` in addition to `List[MessageCreate]`
- `MessageCreate` has been limited to only accepting roles `user` and `system`, because it's too complex to allow the user to create other roles on the `POST` (might as well just require them to create `Message`s instead)
- for example, user wants to send an `assistant` message in the list that has a message "hey how's it going chad", but they don't realize that they can't put that in `content`, but need to put it inside `tool_calls` as the kwarg to a `send_message` function, etc...
---
How …
=> feat: refactor the `POST` `agent/messages` API to take multiple messages

letta/llm_api/mistral.py, letta/providers.py, tests/test_providers.py
Add support for MistralProvider. We will create a follow up PR for actually querying the Mistral models.
Added unit testing to test listing models.
```
(letta-py3.12) mattzhou@Matts-MacBook-Pro MemGPT % poetry run pytest -s -vv tests/test_providers.py::test_mistral
=================================================================================== test session starts ===================================================================================
platform darwin -- Python 3.12.6, pytest-8.3.3, pluggy-1.5.0 -- /Users/mattzhou/Library/Caches/pypoetry/virtualenvs/letta-Mdwnr1Ge-py3.12/bin/python
cachedir: .pytest_cache
rootdir: /Users/mattzhou/MemGPT/tests
configfile: pytest.ini
plugins: asyncio-0.23.8, order-1.3.0, anyio-3.7.1
asyncio: mode=Mode.AUTO
collecting ... Initializing …
```
=> feat: Add MistralProvider

letta/agent.py, letta/schemas/memory.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py
---
Create an agent in the CLI:
```sh
% letta run
Ollama fetch model info error for llama2:latest: unsupported model format
Ollama model llama2:latest has no context window
? Select LLM model: letta-free [type=openai] [ip=https://inference.memgpt.ai]
Ollama fetch model info error for llama2:latest: unsupported model format
Ollama model llama2:latest has no embedding dimension
? Select embedding model: letta-free [type=hugging-face] [ip=https://embeddings.memgpt.ai]
->  🛠️  8 tools: send_message, pause_heartbeats, conversation_search, conversation_search_date, archival_memory_insert, archival_memory_search, …
```
=> feat: add `GET` route to get the breakdown of an agent's context window

docs/data_sources.md, docs/markdown/index.md, examples/tutorials/memgpt_rag_agent.ipynb, letta/client/client.py, letta/metadata.py, letta/server/rest_api/routers/v1/sources.py, letta/server/server.py, tests/helpers/client_helper.py, tests/test_client.py
Add delete file from source endpoint. We introduce an endpoint that, given:
- `source_id`
- `file_id`
Can delete the file with `file_id` from the source with `source_id`. This endpoint returns a 204 code upon successful deletion.
Wrote a simple unit test covering adding a file and then deleting it.
=> feat: Add delete file from source endpoint

letta/agent.py, letta/cli/cli.py, letta/llm_api/anthropic.py, letta/llm_api/helpers.py, letta/llm_api/llm_api_tools.py, letta/llm_api/openai.py, letta/main.py, letta/schemas/llm_config.py, tests/configs/llm_model_configs/azure-gpt-4o-mini.json, tests/configs/llm_model_configs/claude-3-opus.json, tests/configs/llm_model_configs/gemini-pro.json, tests/configs/llm_model_configs/gpt-4.json, tests/configs/llm_model_configs/groq.json, tests/configs/llm_model_configs/letta-hosted.json, tests/configs/llm_model_configs/ollama.json, tests/helpers/endpoints_helper.py
Add `put_inner_thoughts_in_kwargs` as a config that can be set by users per LLM config. This reduces the opacity of "deriving" this value or hardcoding this value in logic for different providers in the `create` function. 
Ran `test_endpoints.py` for a variety of LLM configs and confirmed passed.
We also run `poetry run pytest -s -vv tests/test_client.py::test_streaming_send_message` to test the `root_validator`:
> the `root_validator` auto-populates the `put_inner_thoughts_in_kwargs` field with some conditions on the model name. To perform that this works, we note that without the `root_validator`, the `test_streaming_send_message` fails, and with it, it passes, meaning that `gpt-4` has the field correctly set to `False`, not the default `True`. 
Finally, we run letta run with an …
=> feat: Add `put_inner_thoughts_in_kwargs` as a config setting for the LLM

letta/client/client.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py, tests/test_new_client.py
Add endpoint to get full Tool objects belonging to an agent. This is requested by @4shub
Modified an existing test to use the client function to get the full toolset.
=> feat: Add endpoint to get full Tool objects belonging to an agent

letta/agent.py, letta/llm_api/openai.py, letta/schemas/letta_message.py, letta/schemas/message.py, letta/server/rest_api/interface.py, letta/utils.py
Problem: `FunctionResponse` is generated from a `FunctionCallMessage`, but the two do not share an `.id`, so there's no way to tell which `FunctionCallMessage` was the source for a `FunctionResponse` without looking at the message ordering + timestamps (error prone).
This PR adds a new field to the `LettaMessage` response types `FunctionCallMessage` and `FunctionResponse` that indicates which "tool call object" they are tied to, allowing the API client to tie the two together easily.
---
Example: for the following streamed POST SSE message:
- the `id` field in the `function_call` chunk and `function_return` chunk are **different**
- `message-cdef867b-b8d2-403c-8e4f-ac23cd6681d1` vs `message-43cbef99-460f-4f94-8f64-6a8d3aca8840`
- however, the `function_call_id` **is the same**
- …
=> feat: add function IDs to `LettaMessage` function calls and response

letta/llm_api/openai.py, letta/server/rest_api/interface.py, tests/test_stream_buffer_readers.py
To reproduce bug:
1. Open ADE, create agent w/ `gpt-4o-mini` backend + `text-embeddings-ada-002` embeddings backend
2. Ask agent to `add "banana" to your archival memory`
3. Error should trigger server side (on the client, the message will just stall after the inner thoughts)
```sh
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<to_thread() done, defined at /Users/loaner/miniconda3/lib/python3.10/asyncio/threads.py:12> exception=1 validation error for FunctionCallDelta
function_call_id
Field required [type=missing, input_value={'name': 'archival_memory...ert', 'arguments': None}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.9/v/missing>
File …
```
=> fix: fix bug triggered by using ada embeddings

.github/workflows/test_openai.yml, tests/helpers/endpoints_helper.py, tests/test_endpoints.py
We add an extra test for GPT-4 to test archival insert, and also refactor the OpenAI CI test:
- Make failures fatal, since GPT-4 is the gold standard (we expect to consistently pass)
=> test: Add archival insert test to GPT-4 and make tests failure sensitive

letta/cli/cli.py, letta/client/client.py, letta/server/server.py
Fix `letta delete-agent`. This resolves issue #1854 
Tested manually:
```
* A new version of composio is available, run `pip install composio-core==0.5.36` to update.
(base) (letta-py3.12) mattzhou@Matts-MacBook-Pro MemGPT % letta delete-agent --agent-name FabulousAsterisk
? Are you sure you want to delete agent 'FabulousAsterisk' (id=agent-47b6f3b0-53ca-42ba-b419-cb0bcfaf704f)? Yes
🕊️ Successfully deleted agent 'FabulousAsterisk' (id=agent-47b6f3b0-53ca-42ba-b419-cb0bcfaf704f)
```
=> fix: Fix `letta delete-agent`

letta/cli/cli.py, letta/client/client.py, letta/orm/base.py, letta/orm/sqlalchemy_base.py, letta/orm/tool.py, letta/orm/user.py, letta/schemas/tool.py, letta/server/rest_api/routers/v1/agents.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, letta/services/tool_manager.py, letta/services/user_manager.py, tests/test_local_client.py, tests/test_managers.py, tests/test_server.py, tests/test_tools.py
Enable base constructs to automatically populate "created_by" and "last_updated_by" fields for relevant objects. We apply this to Tools, but this will set the foundation for future ORM refactors.
We also change it so we thread the entire actor (`User`) through the requests - this simplifies the API, and also allows us to do some simple access predicate checking where we confirm the actor of the request belongs to the organization the object (Tool, Agent) is associated with.
Ensured existing tests pass and added a new test case:
- Confirms that if multiple users on the same org, and a different user edits the Tool, then the `last_updated_by` field is updated but `created_by` is not
=> feat: Enable base constructs to automatically populate "created_by" and "last_updated_by" fields for relevant objects

.github/workflows/docker-integration-tests.yaml, Dockerfile, docker-compose-vllm.yaml, letta/server/startup.sh, nginx.conf
You can now spin up letta with 
```
> docker run lettaai/letta:latest
Starting MEMGPT server...
uvicorn.error - INFO - Started server process [8]
uvicorn.error - INFO - Waiting for application startup.
/app/.venv/lib/python3.12/site-packages/pydantic/json_schema.py:2191: PydanticJsonSchemaWarning: Default value <property object at 0xffff886c54e0> is not JSON serializable; excluding default from JSON schema [non-serializable-default]
warnings.warn(message, PydanticJsonSchemaWarning)
uvicorn.error - INFO - Application startup complete.
uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8283 (Press CTRL+C to quit)
```
=> feat: move docker run command to use port 8283

.github/workflows/tests.yml, letta/client/client.py, letta/llm_api/llm_api_tools.py, letta/providers.py, letta/server/server.py, tests/test_client.py, tests/test_providers.py, tests/test_server.py
Clean up some legacy code and fix Groq provider so models show up in list. Also, fix bug where the type was being set to openai, not groq.
Added a simple unit test that checks at least one model of that type appears when calling `server.list_llm_models()`.
=> fix: Clean up some legacy code and fix Groq provider

letta/functions/schema_generator.py
Make imports more explicit for `BaseModel` v1 or v2.
=> fix: Make imports more explicit for `BaseModel` v1 or v2

letta/client/client.py, letta/schemas/letta_response.py, letta/server/rest_api/routers/v1/agents.py, tests/test_client.py
Before:
```sh
% curl --request POST \
--url http://localhost:8283/v1/agents/agent-95e54e09-f18b-4bf8-b795-50d86130456e/messages \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data '{
"messages": [
{
"role": "user",
"text": "hi again"
}
]
}'
{
"messages":[
{"id":"message-8c0b79c3-224b-46ac-ac8a-3bf2c8130144","date":"2024-10-31T22:51:35+00:00"},
{"id":"message-8c0b79c3-224b-46ac-ac8a-3bf2c8130144","date":"2024-10-31T22:51:35+00:00"},
{"id":"message-a9fccc74-6ada-4d13-ac8f-06f628f7c65c","date":"2024-10-31T22:51:35+00:00"}
],
"usage":{"completion_tokens":53,"prompt_tokens":3106,"total_tokens":3159,"step_count":1}
}
```
After:
```sh
% curl --request POST \
--url http://localhost:8283/v1/agents/agent-95e54e09-f18b-4bf8-b795-50d86130456e/messages \ …
```
=> fix: fix bug with `POST /v1/agents/messages` route returning empty `LettaMessage` base objects

.github/workflows/code_style_checks.yml
Trying to patch failing tests on main
=> fix: stop running the PR title validation on main, only on PRs

letta/server/rest_api/app.py, letta/server/rest_api/routers/v1/agents.py
=> chore: fix lettaresponse

letta/cli/cli.py, letta/constants.py, letta/main.py, main.py, tests/test_cli.py
- disabled composio print statement
- fixed link to old readme docs when you to `python main.py` (from ancient youtube videos)
- made it so that the CLI flow has an easy way to change the context window
- **important note**: there's a min context window and a max (the provider's output) for the `questionary` input field
```
% letta run
? Select LLM model: letta-free [type=openai] [ip=https://inference.memgpt.ai]
? Context window (hit enter for default): 6000
? Select embedding model: letta-free [type=hugging-face] [ip=https://embeddings.memgpt.ai]
->  🛠️  7 tools: send_message, conversation_search, conversation_search_date, archival_memory_insert, …
```
=> fix: misc fixes (bad link to old docs, composio print statement, context window selection)

letta/server/server.py
No error when the tool name is invalid in agent state
=> fix: no error when the tool name is invalid in agent state

letta/local_llm/utils.py, poetry.lock
The `auth_type` is empty, not `None` for Ollama so this was throwing an error. 
Ran with Ollama using the ADE: 
Yes 
#1877
No
=> fix: fix `Unsupport authentication type` error for Ollama 

letta/server/server.py, tests/test_server.py
Fix bug for deleting agents belonging to the user org
=> fix: Fix bug for deleting agents belonging to the user org

compose.yaml, nginx.conf
This PR fixes two Docker compose startup issues:
1. Removes duplicate nginx port listener configuration that causes nginx container to fail
2. Adds proper database healthcheck to ensure Letta server only starts after database is ready to accept connections
1. Pull the changes and run:
```bash
docker compose up
```
Expected outcomes:
- All three containers should start successfully, as shown:
```bash
[+] Running 4/3
✔ Network letta_default           Created                                                                                                              0.0s 
✔ Container letta-letta_db-1      Created …
```
=> fix: Fix Docker compose startup issues (letta-ai#2056)

.github/workflows/test_together.yml, letta/constants.py, letta/llm_api/llm_api_tools.py, letta/llm_api/openai.py, letta/local_llm/utils.py, letta/providers.py, letta/schemas/llm_config.py, letta/schemas/openai/chat_completion_response.py, letta/server/server.py, letta/settings.py, tests/configs/llm_model_configs/together-llama-3-1-405b.json, tests/configs/llm_model_configs/together-llama-3-70b.json, tests/test_model_letta_perfomance.py, tests/test_providers.py
There are two ways to use TogetherAI:
The obvious way is to override `OPENAI_API_KEY` and `OPENAI_BASE_URL` -> this will set up TogetherAI as an OpenAI proxy server, similar to the OpenRouter documentation here: https://docs.letta.com/models/openai_proxy
However, upon testing it seems like the TogetherAI function calling support is pretty limited / has poor performance, so we probably want to use TogetherAI via `/completions` routes (similar to how we connect to vLLM) instead. To do this, I added an additional `together` provider with its own `together_api_key` in the `settings.py`. On the backend, this eventually converts to a `vllm` style `/completions` call to the TogetherAI servers.
Upon testing, the second approach works much better, so we should make it the default until …
=> feat: support togetherAI via `/completions`

letta/agent.py, letta/llm_api/llm_api_tools.py, letta/local_llm/utils.py, letta/services/tool_manager.py, tests/test_summarize.py, tests/test_tools.py
Fix problem where when the user set a lower than native context window limit, the loop runner wouldn't trigger the summarize event correctly (even though the summarizer warning would still get injected).
=> fix: context window overflow patch

letta/agent.py, letta/server/server.py, tests/test_local_client.py
This fixes PR fixes a bug where memory shared between multiple agents does not update correctly. The reason is that updated values are only loaded in the agent step. This requires the agent to receive a message to receive update values from shared memory. 
Run the test `pytest -s tests/test_local_client.py::test_shared_blocks_without_send_message`
=> fix: shared memory without requiring send message

letta/client/client.py, letta/services/block_manager.py, tests/test_managers.py
Updating blocks with length greater than the default length throws an error due to the default limit value of `BlockUpdate`. This PR allows setting limits for `BlockUpdate` so that updates larger than the default limit are allowed. 
Run the test `pytest -s tests/test_managers.py::test_update_block_limit`
=> fix: fix bug where updates sets block limit to default value

letta/client/client.py, letta/schemas/block.py, letta/schemas/memory.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py, tests/test_client.py, tests/test_memory.py
Very closely follows the design of updating the `Memory.label` from PR #2083
Route:
```
@router.patch("/{agent_id}/memory/limit", response_model=Memory, operation_id="update_agent_memory_limit")
```
=> feat: add route for editing a memory blocks limit (via `Memory`, instead of via `Blocks`)

letta/client/client.py, letta/schemas/block.py, letta/schemas/memory.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py, tests/test_client.py, tests/test_memory.py
=> Revert "feat: add route for editing a memory blocks limit (via `Memory`, instead of via `Blocks`)"

letta/client/client.py, letta/schemas/block.py, letta/schemas/memory.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py, tests/test_client.py, tests/test_memory.py
- Adds two new REST routes for linking and unlinking blocks from an agents memory
- `@router.post("/{agent_id}/memory/block", response_model=Memory, operation_id="add_agent_memory_block")`
- `@router.delete("/{agent_id}/memory/block/{block_label}", response_model=Memory, operation_id="remove_agent_memory_block")`
- Adds a third REST route for updating the label of a current block
- `@router.patch("/{agent_id}/memory/label", response_model=Memory, operation_id="update_agent_memory_label")`
=> feat: routes for adding/linking new memory blocks to agents + unlinking blocks from agents

.github/workflows/tests.yml, letta/functions/helpers.py, letta/services/tool_execution_sandbox.py, letta/settings.py, tests/test_tool_execution_sandbox.py
Enable composio tools on e2b and local sandboxes. Also, improved the local sandbox result grabbing (no more string parsing the results), and also improved error logging on e2b sandbox.
Wrote two unit tests for testing running composio tools in sandboxes.
=> feat: Add composio tools compatibility to sandboxes

letta/functions/schema_generator.py, letta/local_llm/utils.py
Without this, the following tool can't get added (`list` doesn't work, neither does `List[str]`):
```python
def analyze_campaign(campaign_name: str, metrics: list, time_range: str) -> str:
"""
Evaluate campaign performance metrics.
Args:
campaign_name (str): Name of the campaign.
metrics (list): List of performance metrics to evaluate.
time_range (str): Time range for analysis (e.g., 'last_week').
Returns:
str: Campaign performance summary.
"""
import random
performance_data = {
"meeting_requests": random.randint(5, 20),
"meetings_booked": random.randint(10, 30),
"pipeline_generated": f"${random.randint(100000, 500000):,}",
"closed_won": f"${random.randint(50000, 300000):,}"
}
performance_summary = ", ".join([f"{metric}: {performance_data.get(metric, 'N/A')}" for metric in metrics]) …
```
=> fix: add more types to the type_map from python -> json schema

letta/agent.py
Bug:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
return await anyio.to_thread.run_sync(func, *args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 807, in run
result = context.run(func, *args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/letta/server/rest_api/routers/v1/agents.py", …
```
=> fix: do a pre-validation validation on the inputs assigned to `agent_state.message_ids`

letta/errors.py, letta/functions/functions.py, letta/functions/schema_generator.py, letta/server/rest_api/routers/v1/tools.py
If the source code / payload for creating a tool is bad (can't be parsed), the server will send back a 400 error with a `detail` field.
=> fix: pass tool errors through the HTTP POST `/tools` requests with detailed error messages

letta/schemas/letta_base.py
This resolves an issue with the SDK autogeneration, as Ids are not arrays
=> fix: example issue

letta/server/rest_api/routers/v1/agents.py
Remove hard failure on bad `stream_tokens` input, it sets it to false when the model does not support it anymore.
=> fix: Remove hard failure on bad `stream_tokens` input

letta/agent.py
Improve retry mechanism for `_get_ai_reply` and refactor method to improve code quality. We add an exponential backoff, and differentiate between retryable errors v.s. generic errors. 
Rely on existing unit testing.
=> feat: Improve retry mechanism for `_get_ai_reply` and refactor method

letta/server/rest_api/app.py
=> fix: allow setting pass for server `--secure`

letta/server/rest_api/routers/v1/sandbox_configs.py
Add endpoints to add default e2b/local sandbox configs. These are intended to be used by cloud.
=> feat: Add endpoints to add default e2b/local sandbox configs

.github/workflows/tests.yml, letta/functions/functions.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, poetry.lock, pyproject.toml, tests/helpers/utils.py, tests/integration_test_tool_execution_sandbox.py, tests/test_server.py, tests/test_v1_routes.py
Add endpoints to list Composio apps and actions. There is also an endpoint to upsert a tool given a Composio action name. This will be used by cloud. 
We also delete some unused codepaths.
We add a unit test for server, and also add comprehensive unit testing for the tools v1 routes. These tests purely test the input/output of the routes, everything else is mocked.
=> feat: Add endpoints to list Composio apps and actions

letta/cli/cli.py, letta/schemas/tool.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, letta/services/tool_execution_sandbox.py, tests/test_server.py
```python
@router.post("/run", response_model=FunctionReturn, operation_id="run_tool_from_source")
def run_tool_from_source(
server: SyncServer = Depends(get_letta_server),
request: ToolRunFromSource = Body(...),
user_id: Optional[str] = Header(None, alias="user_id"),  # Extract user_id from header, default to None if not present
):
"""
Attempt to build a tool from source, then run it on the provided arguments
"""
actor = server.get_user_or_default(user_id=user_id)
return server.run_tool_from_source(
tool_source=request.source_code,
tool_source_type=request.source_type,
tool_args=request.args,
tool_name=request.name,
user_id=actor.id,
)
```
Example tests:
```python
EXAMPLE_TOOL_SOURCE_WITH_DISTRACTOR = '''
def util_do_nothing():
"""
A util function that does nothing.
Returns:
str: Dummy …
```
=> feat: add POST route for testing tool execution via `tool_id`

letta/services/tool_execution_sandbox.py, tests/integration_test_tool_execution_sandbox.py
Add escapes to arguments of type string to allow arguments to have newlines etc.
=> fix: escape strings in sandbox

tests/test_managers.py
Skip foreign key/constraint tests if using SQLite. Small changes to the `test_managers.py` unit testing.
=> chore: Skip foreign key/constraint tests if using SQLite

letta/services/tool_execution_sandbox.py, tests/integration_test_tool_execution_sandbox.py
Suppress warnings during local sandbox tool execution w/ venv. This is causing an issue where, if warnings are outputted during tool execution runtime, we raise an error in the local sandbox w/ a venv.
=> fix: Suppress warnings during local sandbox tool execution w/ venv

letta/services/tool_execution_sandbox.py, tests/integration_test_tool_execution_sandbox.py
Parse out errors from venv local sandbox and throw the actual error. This parsing is done optimistically, so at best, it's an improvement, at worst, we get similar behavior as now.
Write a simple test that tests the error gets parsed and evaled.
=> feat: Parse out errors from venv local sandbox

examples/composio_tool_usage.py, letta/client/client.py, letta/functions/helpers.py, letta/schemas/tool.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, letta/services/sandbox_config_manager.py, letta/services/tool_manager.py, tests/integration_test_tool_execution_sandbox.py, tests/test_v1_routes.py
Fix composio tool add:
- Tweaks the tool update to do less efficiency checks (trips up new schema generation errors for composio)
- Attaches their API key to all composio wrappers
Tests:
- Tested manually by invoking curls:
```
(letta-py3.12) (base) mattzhou@Matts-MacBook-Pro MemGPT % curl -X POST http://localhost:8283/v1/tools/composio/PEOPLEDATALABS_SEARCH_PERSON_DATA
{"id":"tool-57f42553-cee5-4566-864f-8f948aa13cb9","description":"Search Person Data Is A Tool That Searches For Person Data Based On A Given Sql Query.","source_type":"python","module":null,"organization_id":"org-00000000-0000-4000-8000-000000000000","name":"peopledatalabs_search_person_data","tags":["composio"],"source_code":"\ndef peopledatalabs_search_person_data(**kwargs):\n    from composio import Action, App, Tag\n …
```
=> fix: Fix composio tool add

letta/server/rest_api/routers/v1/agents.py, letta/server/rest_api/utils.py, letta/services/sandbox_config_manager.py
=> fix: temp disable stream tokens

letta/cli/cli.py
Disable print spam in server logs:
```
INFO:     ::1:54484 - "GET /v1/health/ HTTP/1.1" 200 OK
0.6.1
0.6.1
INFO:     ::1:54473 - "GET /v1/health/ HTTP/1.1" 200 OK
INFO:     ::1:54484 - "GET /v1/health/ HTTP/1.1" 200 OK
INFO:     ::1:54473 - "GET /v1/health HTTP/1.1" 307 Temporary Redirect
INFO:     ::1:54473 - "GET /v1/health HTTP/1.1" 307 Temporary Redirect
0.6.1
INFO:     ::1:54473 - "GET /v1/health/ HTTP/1.1" 200 OK
0.6.1
INFO:     ::1:54473 - "GET /v1/health/ HTTP/1.1" 200 OK
0.6.1
0.6.1
INFO:     ::1:54473 - "GET /v1/health/ HTTP/1.1" 200 OK
INFO:     ::1:54484 - "GET /v1/health/ HTTP/1.1" 200 OK
INFO:     ::1:54484 - "GET /v1/health HTTP/1.1" 307 Temporary Redirect
INFO:     ::1:54484 - "GET /v1/health HTTP/1.1" 307 Temporary Redirect
0.6.1
INFO:     ::1:54484 - "GET /v1/health/ …
```
=> fix: disable printing version in health check, causes spam

letta/errors.py, letta/llm_api/llm_api_tools.py, letta/server/rest_api/app.py, letta/server/server.py
Cleans up some common error triggers on the server side:
---
Server-side:
```
INFO:     ::1:56137 - "GET /v1/agents/agent-bbd31eda-8b95-46d3-957e-312ef4fe2911/context HTTP/1.1" 200 OK
...
Exception: Retries exhausted and no valid response received.
None
Retries exhausted and no valid response received.
...
File "/Users/loaner/miniconda3/envs/letta/lib/python3.12/site-packages/letta/agent.py", line 641, in _get_ai_reply
raise Exception("Retries exhausted and no valid response received.")
Exception: Retries exhausted and no valid response received.
```
Client-side:
```
File "/Users/loaner/miniconda3/envs/letta/lib/python3.12/site-packages/letta/client/client.py", line 975, in send_message
raise ValueError(f"Failed to send message: {response.text}") …
```
=> fix: add a special error type for configuration errors

letta/client/client.py, letta/orm/sqlalchemy_base.py, letta/server/rest_api/routers/v1/agents.py, letta/server/server.py, letta/services/message_manager.py, letta/services/tool_execution_sandbox.py, tests/test_managers.py, tests/test_server.py
Modify the `list` ORM function:
- Allow ascending/descending sorting
- Sort by both created_at and id
- We now retrieve the object given passed in cursor id, and use the `created_at` field to do pagination
Please note, there is a strange race condition with Sqlite as the created_at field is not accurate enough. This should not have any practical effect for the most part, as this is triggered by lines in our tests where we rapidly create a bunch of objects. We are tracking this issue and will find a workaround for Sqlite users.
=> fix: Modify the `list` ORM function

.github/workflows/check_for_new_prints.yml, letta/services/tool_execution_sandbox.py
Noticed this faulty  failing test on PR [#2205](https://github.com/letta-ai/letta/pull/2205)
Ensure git test run passes
Before:
```
(letta-py3.12) caren@caren-mac letta % git diff main "letta/services/tool_execution_sandbox.py" | grep "^+" | grep -v "^+++" | grep "print(" || true
+                sandbox_config_fingerprint=sbx_config.fingerprint(),
```
After: 
```
(letta-py3.12) caren@caren-mac letta % git diff main "letta/services/tool_execution_sandbox.py" | grep "^+" | grep -v "^+++" | grep -E "(^|\s)print\(" || true
```
**Is your PR …
=> fix: pattern match new prints correctly

letta/server/rest_api/app.py, letta/server/server.py
Before:
```
curl --request POST \
--url http://localhost:8283/v1/agents/ \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data '{
"memory_blocks": [
{
"value": "The human'\''s name is Bob the Builder",
"label": "human"
},
{
"label": "persona",
"value": "My name is Sam, the all-knowing sentient AI."
}
],
"name": "agent_sam"
}'
File "/Users/loaner/Library/Caches/pypoetry/virtualenvs/letta-JSsUGnlY-py3.10/lib/python3.10/site-...
tta-JSsUGnlY-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
File "/Users/loaner/Library/Caches/pypoetry/virtualenvs/letta-JSsUGnlY-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run …
```
=> fix: cleanup error trace for no llm/embedding_config on POST

letta/server/rest_api/app.py
This is required for PaaS services that accept a healthcheck endpoint (but no header options)
=> fix: make healthcheck public

letta/server/rest_api/routers/v1/agents.py
Don't show / require the `user_id` in the `CreateAgent` request model (it's confusing to developers, since end-user ID tracking should be done via `tags`, not via the `user_id` field).
This should drop the value from the generated `openapi.json` schema as well.
=> fix: create new request model that drops user_id

README.md
This should fix pypi package description broken images.
=> fix: Update README.md asset URLs to be absolute

letta/settings.py
with v0.6.3, if you have extra variables in your .env file, letta fails to initiate because of the default behavior of [SettingsConfDict](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#dotenv-env-support).
Just try to import ChatMemory with extra variables in your `.env` file.
If so, please break up your PR into multiple smaller PRs so that we can review them quickly, or provide justification for …
=> ignore extra variables in env files

Dockerfile
Our dependencies are not reliably installing because we aren't pinning a python/poetry version. 
Run `docker compose -f dev-compose.yaml up --build -d`
Yes
=> chore: set `Dockerfile` to use Python 3.12 

letta/server/rest_api/routers/v1/tools.py
Catch composio errors and return informative errors in the endpoint. 
Tested manually:
```
(base) mattzhou@Matts-MacBook-Pro ~ % curl -X POST http://localhost:8283/v1/tools/composio/BAMBOOHR_GETS_TABLE_ROWS_FOR_A_GIVEN_EMPLOYEE_AND_TABLE_COMBINATION | jq
{
"detail": {
"message": "No connected account found for tool `BAMBOOHR_GETS_TABLE_ROWS_FOR_A_GIVEN_EMPLOYEE_AND_TABLE_COMBINATION`. You need to connect the relevant app in Composio order to use the tool.",
"composio_action_name": "BAMBOOHR_GETS_TABLE_ROWS_FOR_A_GIVEN_EMPLOYEE_AND_TABLE_COMBINATION"
}
}
```
```
(base) mattzhou@Matts-MacBook-Pro ~ % curl -X POST http://localhost:8283/v1/tools/composio/oops | jq                                                           
{
"detail": {
"message": "Cannot find composio action with name …
```
=> feat: Catch composio errors and return informative errors in the endpoint

letta/orm/source.py, letta/schemas/agent.py
Move orm metadata out of write-only Agent pydantic objects. Small so relying on existing unit testing.
=> Fix: Move orm metadata out of write-only Agent pydantic objects

letta/schemas/sandbox_config.py, letta/services/sandbox_config_manager.py
Changing e2b template id as an env var reflects immediately. Before, it needed to be re-written to the database, now it derives directly from the environment variable. Existing test cases for grabbing the default e2b covers this.
=> fix: Changing e2b template id as an env var reflects immediately

letta/server/server.py
Remove `created_by_id` check. There are legacy agents created with this field unpopulated.
=> fix: Remove `created_by_id` check

letta/agent.py, letta/client/client.py, letta/constants.py, letta/llm_api/anthropic.py, letta/llm_api/llm_api_tools.py, tests/configs/llm_model_configs/claude-3-sonnet-20240229.json, tests/configs/llm_model_configs/openai-gpt-3.5-turbo.json, tests/integration_test_agent_tool_graph.py, tests/integration_test_offline_memory_agent.py
https://linear.app/letta/issue/LET-508/inittool-tool-rule
* Fixed first message flag
* Added support for Claude-3-sonnet configs
* New test case for init tool rule
If so, please break up your PR into multiple smaller PRs so that we can review them quickly, or …
=> feat: Adding init tool rule for Anthropic endpoint

letta/agent.py, letta/schemas/sandbox_config.py, letta/server/server.py, letta/services/tool_execution_sandbox.py, letta/utils.py
Refactor so that we no longer derive the error case based on whether stderr is populated (script could manually write to stderr even if the run is successful). This refactor also moves the logic for populating the func_return value with a friendly error message at the source of the error rather than waiting until the end, and adds a helper method so all functions do it the same way.
Please link any related GitHub [issues](https://github.com/cpacker/Letta/issues) or …
=> fix: refactor sandbox run logic to add status field

letta/agent.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, letta/services/tool_execution_sandbox.py, tests/helpers/endpoints_helper.py, tests/integration_test_tool_execution_sandbox.py, tests/test_server.py
Before, we were holding `self.functions` and `self.functions_python` in memory via `link_tools`. Here we get rid of link tools, and retrieve the tools when we need them from `agent_state`.
Small change - we directly pass in the `actor` object into calls, to reduce repeatedly retrieving the user based on the `user_id`.
Because this is a refactor, we rely on existing tests.
=> fix: Deprecate in memory function stores in agent.py

letta/client/client.py, letta/functions/function_sets/base.py, letta/server/rest_api/routers/v1/tools.py, letta/server/server.py, letta/services/agent_manager.py, letta/services/tool_manager.py, scripts/migrate_tools.py, tests/test_client_legacy.py, tests/test_managers.py, tests/test_v1_routes.py
Clean up functionality around upserting base tools with the latest code.
=> chore: Clean up upserting base tools 

letta/server/server.py, letta/services/message_manager.py
Remove load agent in recall cursor. Identified that as the choke point for the `list_messages` endpoint. 
Will remove debugging logs in a follow up PR.
=> fix: Remove load agent in recall cursor

examples/helper.py, letta/client/streaming.py, letta/schemas/letta_message.py, letta/schemas/letta_response.py, letta/schemas/message.py, letta/server/rest_api/interface.py, tests/helpers/endpoints_helper.py, tests/test_client_legacy.py, tests/test_server.py
=> feat: rename internal monologue

letta/client/client.py
Bugfix: add required argument `actor` for `load_file_to_source` method
```python
client = letta.create_client()
client.load_file_to_source(local_file_path, source_id)
```
Yes.
I ran into this error when running locally with `ollama` server.
After the fix, the error is gone.
N/A
NO.
N/A
=> Fix bug: add required argument `actor` (`load_file_to_source`).

letta/server/rest_api/routers/v1/tools.py
Adds some error codes to composio
=> feat: add error codes to composio errors

letta/agent.py, letta/constants.py, letta/server/rest_api/interface.py, letta/utils.py, tests/test_client.py
reinstate prior functionality. following up with a more robust implementation that doesn't infer status based on the string (but this is fine for now since I am setting the string the same way at all callsites)
poetry run pytest -s -vv tests/test_client.py::test_function_always_error
If so, please break up …
=> fix: propagate error on tool failure

letta/providers.py, letta/schemas/embedding_config.py, letta/schemas/llm_config.py
=> feat: store handle in configs

letta/agent.py
=> fix: add underlying error message for Retries Exhausted error

tests/test_client.py
=> fix: deprecate function return in new test

letta/client/client.py
While creating a block [here](https://github.com/letta-ai/letta/blob/69e376406ec8b0368eb02baa12308c8a4d142c4e/letta/client/client.py#L1051), the limit is assigned later which leads to the pydantic validator [here](https://github.com/letta-ai/letta/blob/ea2a7395f4023f5b9fab03e6273db3b64a1181d5/letta/schemas/block.py#L38) failing with exception as it validates against the default limit of 5000 instead of what is being passed by the arguments.
Please link any related GitHub …
=> fix: validate after limit assignment in `create_block`

.github/workflows/docker-image.yml, letta/client/client.py, letta/functions/schema_generator.py, tests/test_tool_sandbox/restaurant_management_system/adjust_menu_prices.py
Fixes a bug in Python SDK. Setting `token=<password>` when instantiating a RESTClient was not sufficient to authorize since `CheckPasswordMiddleware` was checking for `X-BARE-PASSWORD` instead of 'Authorization` header.
RESTClient is now setting `X-BARE-PASSWORD="password <password>` as a header.
```python
from letta.client.client import RESTClient
client = RESTClient(base_url="http://0.0.0.0:8283", token="<password>")
print(client.personas())
```
=> fix: update authorization header to use X-BARE-PASSWORD format

CONTRIBUTING.md
Adds steps in CONTRIBUTING guide to prepare PostgreSQL environment for use with Letta. The instructions are organized in a way that both PG and pgvector can be used locally (or an already running PG instance) without needing container images.
The steps can be tested by trying out setting up a PG environment and starting Letta operating on PG instance.
The updated steps were tested out manually and Letta run was triggered successfully.
N/A
N/A
N/A
=> docs(contrib): Add steps to prepare PostgreSQL environment

letta/llm_api/azure_openai_constants.py
Deployment of 4o ignores version.
Fixes bug where azure openai does not have the correct context length for 4o versions.
Standard usage.
Yes, it successfully displays the proper context window.
N/A
No
N/A
=> Change Azure Context Length

letta/agent.py
This pr changes `letta/agent.py` file by adding `function_args` as a parameter to several methods, so to ensure that function arguments are correctly passed and logged during error handling process.
resolves #2422
=> fix: include missing function arguments in error handling

letta/agent.py, letta/embeddings.py, letta/settings.py, tests/test_base_functions.py, tests/test_google_embeddings.py, tests/test_sdk_client.py
This is a fix for the archival tools not working when using Google Gemini's embedding models - text-embedding-004 and embedding-001. Also fixed a few syntax errors in tests/test_base_function and tests/test_sdk_client that did not let me run pytest.
Command to run the test: `poetry run pytest tests/test_google_embeddings`
There are 3 test cases, 
- checks validity of the gemini api endpoint
- an archival insert and retrieval for the text-embedding-004 embedding model
- an archival insert and retrieval for the embedding-001 embedding model
Pytest
```
PS E:\projects\open_source\letta> poetry run pytest .\tests\test_google_embeddings.py
================================================= test …
```
=> fix: Google embeddings endpoint bug (#2416)

letta/cli/cli.py, letta/server/rest_api/routers/v1/health.py, tests/test_cli.py
Avoid unnecessary database operations while running non-server commands like `letta version`, `letta benchmark`, etc.
`letta version` has been fixed as well, it prints out `Creating engine` and no version before this PR.
A test case has been added to ensure that `letta version` prints out version number and nothing else.
For manual validation run:
- `letta version` should show prints out the version
- `poetry run pytest -v tests/test_cli.py -k test_letta_version_prints_only_version` should pass
- and definitely all other existing tests
```
root@42a43c02:/app# poetry run pytest -v tests/test_cli.py -k test_letta_version_prints_only_version
============================================================================================================ …
```
=> fix: avoid unnecessary database operations for non-server cli commands

letta/llm_api/azure_openai_constants.py
Adds support for gpt-4o-mini model in the context length conversion of Azure OpenAI code.
When deploying the gpt-4o-mini on Azure, the agent would pick invalid context length. With this change you can deploy and test against gpt-4o-mini.
Tested manually by deploying gpt-4o-mini with Azure OpenAI.
N/A
N/A
N/A
=> feat: Add model to context length mapping for gpt-4o-mini

letta/functions/ast_parsers.py, tests/test_ast_parsing.py
This pull request adds support for complex type annotations in the `resolve_type` function and expands the test suite to cover these new cases.
Improvements to type resolution:
* [`letta/functions/ast_parsers.py`](diffhunk://#diff-fa9fad0367a76d5bad51009abe63fad360fb4f73509a12301c55f78c05634f03R35-R47): Revised the `resolve_type` function to handle complex type annotations such as `list`, `dict`, and `tuple`.
Improvements to testing:
* [`tests/test_ast_parsing.py`](diffhunk://#diff-86328b8b0e36762354f12f478afaf5bffe35edf920403dbf5c0dbdc3b47a78c1R217-R275): Added multiple test cases to ensure correct coercion of arguments with complex type annotations, including `list[int]`, `dict[str, int]`, nested types like `list[dict[str, int]]`, …
=> feat: add type resolution support for complex types

letta/cli/cli_load.py, letta/data_sources/connectors_helper.py
The file extensions used in `cli_load.py` has '.' prefix. The comparison in `get_filenames_in_dir` uses the strings from
`ext = file_path.suffix.lstrip(".")` resulting in strings without '.' prefix. We fix this by giving extensions without '.' prefix in the default list of extensions to compare against.
The file_path generated are of type PosixPath, whereas string list is expected. We fix this by converting PosixPath to string before constructing the list.
Bug fix in the code path when using load directory.
**How to test**/**Have you tested this PR?**
Manually running a load directory will fail in HEAD when pointed to a directory:
```letta load directory --input-dir <dir path> --name <name>```
will fail to load the text file due to the …
=> fix(load-directory): Fix up file extension comparison & path list construction

letta/llm_api/anthropic.py
This PR adds in the "latest" tags from https://docs.anthropic.com/en/docs/about-claude/models/all-models so that they are available from the dropdown list. 
This is useful because the model list is hardcoded and so a dated tag may lag behind when Anthropic has new releases.
You should see the "latest" tag for appropriate models.
I have not.
=> Add latest tags to Anthropic models

letta/server/rest_api/interface.py
I see these warning messages in the logs all the time:
> /app/letta/server/rest_api/interface.py:927: UserWarning: Couldn't find delta in chunk: id='msg_01RDprk8sYXHCoioWPLkZVjD' choices=[ChunkChoice(finish_reason=None, index=0, delta=MessageDelta(content=None, reasoning_content=None, tool_calls=None, role=None, function_call=None), logprobs=None)] created=datetime.datetime(2025, 3, 9, 3, 53, 34, 142573, tzinfo=datetime.timezone.utc) model='claude-3-5-sonnet-20241022' system_fingerprint=None object='chat.completion.chunk'
This is coming from https://github.com/letta-ai/letta/blob/main/letta/server/rest_api/interface.py#L927 -- however, this is normal and expected behavior from Claude, as in …
=> fix: Spurious empty chunk warning on Claude

poetry.lock, pyproject.toml
This PR will possibly fix #2487.
Since `datamodel-code-generator` is included both as `[tool.poetry.dependencies]` & `[tool.poetry.extras]` in the `pyproject.toml`, the `datamodel-code-generator` is marked as an optional dependency in published `letta` package METADATA.
By checking letta v0.6.41 METADATA in PyPI, we can find this: `Requires-Dist: datamodel-code-generator[http] (>=0.25.0,<0.26.0) ; extra == "desktop" or extra == "all"`, which specifies this dependency is only enforced if the user installs the current package with either the desktop or the all "extra" features. This explains why #2487 happened.
=> fix: remove datamodel-code-generator from extras dependencies

letta/schemas/providers.py
Using the openai_proxy, if there is no explicit context window size defined then the code will continue rather than use a default context window size.
There is a DEFAULT defined in LLM_MAX_TOKENS and it makes sense to use that so that the model name is returned correctly.
You should be able to create a model using an openai proxy that doesn't have a mapping in LLM_MAX_TOKENS and see it in ADE.
Nope!
=> Use default context window size if none found

examples/docs/example.py
For the letta-client python SDK, retrieving and attaching core memory blocks are no longer under core_memory, but under blocks. 
Basically solving this issue:
```
(letta) kyuds@kyuds docs % poetry run python3 example.py
Created agent with name ThoughtfulParakeet
Sent message to agent ThoughtfulParakeet: What's my name?
Agent thoughts: User just logged in and asked for their name. I need to respond with the name I have stored in memory.
Agent response: Your name is Caren. Nice to meet you!
Created tool secret_message and attached to agent ThoughtfulParakeet
Sent message to agent ThoughtfulParakeet: Run secret message tool and tell me what it returns
Agent thoughts: User requested to run the secret message tool. I need to see what it …
```
=> [FIX] Update example.py to reflect breaking API changes

CONTRIBUTING.md
In poetry 2.0 [1] the the shell command has been removed and same functionality can be provided by env command [2].
1. https://python-poetry.org/blog/announcing-poetry-2.0.0
2. https://python-poetry.org/docs/managing-environments
Fixes documentation to work with poetry 2.0.
Can be tested by running the updated steps manually.
Manually tested the updated instructions.
N/A
N/A 
N/A
=> docs(contrib): replace poetry shell with env activate for 2.0

letta/server/rest_api/app.py
fix: remove unused "password" variable and update setup_auth_router() to use "random_password"
- Removed the unused variable "password" from the codebase.
- Updated the function setup_auth_router() to use the "random_password" variable instead of the obsolete "password".
it is to fix a bug.
=> fix: Update app.py - setup_auth_router() 

letta/client/client.py
his commit modifies the create_tool method to automatically derive the name of the tool from the function's __name__ attribute instead of requiring it as a parameter.
The purpose of this pull request is to fix a bug. The bug occurred because the name variable was missing in the function signature of the create_tool method. The fix automatically derives the tool's name from the function's __name__ attribute, removing the need for it as a separate parameter.
Yes, this fix has been tested locally with a few functions and the tool names are set correctly. However, the testing wasn’t extensive. Please check the solution and let me know if the function still needs the `name` parameter or if this fix works.
**Have you tested …
=> fix: remove the missing arg `name` from create_tool in client.py

letta/agent.py
Fixes the tags for debug messages (info => debug)
Tested that log messages are not showing up during regular run.
Tested with manual run to check that messages are not coming. 
N/A
N/A
N/A
=> fix: Use right tag for debug messages

letta/orm/sqlalchemy_base.py, letta/services/block_manager.py, tests/test_sdk_client.py
Currently, block_manager uses multiple calls of get_block_by_id to retrieve a list of blocks. This is rather inefficient, so I refactored the code to run a single query.
fails test unrelated to mine (ie: NameError: name 'retry_until_success' is not defined in test/test_base_functions.py)
If so, please break up …
=> [Improvements] Use single query for Block Manager get_all_blocks_by_ids

letta/llm_api/google_ai_client.py, letta/orm/message.py
This pull request fixes a bug where agents using Gemini models (`gemini-2.5-pro-exp-03-25`, etc.) encounter 400 Bad Request errors when attempting to use tools whose schemas contain certain standard OpenAPI keywords. The Gemini API's function calling feature only supports a limited subset of the OpenAPI 3.0 specification, and keywords like `default`, `exclusiveMaximum`, `exclusiveMinimum`, and specific `format` values (e.g., `"uri"`) are not recognized, leading to `INVALID_ARGUMENT` errors.
This PR modifies the `GoogleAIClient` to proactively clean these unsupported keywords from tool schemas before they are sent to the Gemini API, ensuring compatibility and preventing runtime errors.
First, download …
=> Fix Gemini Function Calling Schema Incompatibilities

letta/services/message_manager.py, tests/test_managers.py
The agent's `conversation_search` tool, can search relevant content in the past conversations, by the given `query_text`. However, this can only work in PostgreSQL, since the `ILIKE` and `json_array_elements` are PostgreSQL-specific syntaxes.
https://github.com/letta-ai/letta/blob/673384915ce82667efb41876c6da3bf2d13382f1/letta/services/message_manager.py#L307-L316
This PR adds the SQLite3-compatible syntax, to fix #2553.
> NOTE: This PR uses dialect branching to resolve the problem; there might be a more elegant and unified way to handle this, but I did not think of any. Welcome to suggestions!
`poetry run pytest -s tests/test_managers.py -k test_list_messages_with_query_text`
I added a unit …
=> Make message filtering in conversation search workable in sqlite3

.github/workflows/send-message-integration-tests.yaml, letta/schemas/providers.py
This PR adds a new CI workflow to validate changes in `letta/schemas/**` against a shortlist of providers, using Letta provided API keys in a secure context, so that community members can have their changes sufficiently tested before merge.
This workflow can be triggered manually or "on label" of a PR from a fork.
[Test PR](https://github.com/letta-ai/letta/pull/2597)
[Actions Output](https://github.com/letta-ai/letta/actions/runs/14719898606/job/41311521144#step:15:475)
Test Key being correctly masked:
[Related PR (to be closed only exists for testing)](https://github.com/letta-ai/letta/pull/2597)
No. …
=> Enabling Provider CI Tests

letta/agent.py
There is a bug in `summarize_messages_inplace()` that causes the agent to throw out all of its messages every time it summarizes, instead of only those up to `[:cutoff]`. This was caused by a call to `trim_all_in_context_messages_except_system()` which blanks the message stream instead of `trim_older_in_context_messages(num=cutoff)` which would only remove the earliest messages in the stream.
This PR swaps the `trim_*()` function in summarization.
The symptom of this is that the context window messages are totally emptied every time summarization runs.
=> fix: only trim in-context messages to cutoff

compose.yaml
problem:
the compose db service won't be used without setting `LETTA_PG_URI`
this behavior is driven by [startup.sh#L16](https://github.com/letta-ai/letta/blob/9488d84c749ff558eb3e1ed1d6fd68c4a059ec82/letta/server/startup.sh#L16)
solution
- update Letta server URLs in base configuration to enable external database
- remove env redundancy
- align with startup.sh
=> fix(docker/compose): correct external db

letta/groups/sleeptime_multi_agent.py
This PR fixes a bug in the SleepTimeMultiAgent class where the mcp_clients argument was not utilized. This prevents SleepTimeMultiAgent Agents from calling tools provided by MCP servers.
1. Create a SleepTime Agent using the method displayed [in the examples](https://github.com/letta-ai/letta/blob/main/examples/sleeptime/sleeptime_example.py)
2. Attach MCP tools to the new agent
3. Instruct the agent to run a tool
Prior to this change, The agent would show "Error executing function my_mcp_tool: ValueError: No MCP client available to use" in the ADE, as shown below.
With this change in place, the tool call is successful.
Couldn't find any. 
**Is your PR over 500 …
=> Fix SleepTimeMultiAgent MCP Tool Usage

letta/functions/mcp_client/stdio_client.py, letta/server/server.py
This PR adds wires up the passing of environment variables to STDIO MCP server processes. 
To test this PR:
1. Configure an MCP server with environment variables in your config file:
```json
{
"mcpServers": {
"myServer": {
"command": "/path/to/server",
"args": [],
"env": {
"SOME_ENV_VAR": "SOME_ENV_VAR"
}
}
}
}
```
2. Start the server and verify that the environment variables are correctly passed to the child process:
3. You can verify the environment variables are passed correctly by having the server process print its environment variables or by checking behavior that depends on those variables.
Yes, I have tested this PR with a server that reads environment variables for configuration. …
=> Pass MCP env to STDIO MCP client

letta/embeddings.py
Fixes adding archival memories failing because of getting a 404 from Ollama's embeddings endpoint. Since the prefixing of the base url with `/v1` (OpenAI API standard) happens elsewhere and is even saved in the database, it's easier to fix this by changing the URL to the OpenAI endpoint rather than the native Ollama one for now.
Apart from the API URL the request and response data was adjusted to match the current endpoint, instead of the deprecated one.
Add archival memory to agent when using Ollama backend.
Yes, memories can now be added.
https://github.com/letta-ai/letta/issues/2747
=> fix: incorrect URL for Ollama embeddings endpoint

letta/log.py
Problem
CPU profiling revealed that _clear_cache() in Python's logging module was consuming a lot of CPU time
Root Cause Analysis
- Every get_logger() call executed dictConfig(DEVELOPMENT_LOGGING)
- With 30+ modules calling get_logger() multiple times per request
- This resulted in hundreds of complete logging system reconfigurations per request
- Each reconfiguration triggered setLevel() → _clear_cache() overhead
Performance impact: Significant CPU time was spent reconfiguring the same logging setup repeatedly instead of
processing actual requests.
Solution
Move dictConfig() from per-function call to module initialization:
Before:
def get_logger(name=None):
dictConfig(DEVELOPMENT_LOGGING)  # ← Called hundreds of times per request
return logging.getLogger("Letta")
After: …
=> mv dictconfig out of getlogger

letta/schemas/providers/ollama.py
Reverted changes in `OllamaProvider.list_embedding_models_async` that caused regression in release [0.11.4](https://github.com/letta-ai/letta/releases/tag/0.11.4).
Endpoint `/v1/models/embedding` doesn't return any embeddings from Ollama backend, and throws an error in the server log.
Yes, as above.
Issue https://github.com/letta-ai/letta/issues/2774
=> fix: revert regression in OllamaProvider

letta/interfaces/anthropic_streaming_interface.py, letta/interfaces/openai_streaming_interface.py
Stacktrace:
```  
"/home/ci-runner/actions-runner/_work/letta/letta/letta/interfaces/anthropic_streaming_interface.py", line
229, in process
logger.error("Error processing stream: %s", e, traceback.format_exc())
File "/usr/lib/python3.12/logging/__init__.py", line 1568, in error
self._log(ERROR, msg, args, **kwargs)
File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
self.handle(record)
File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
self.callHandlers(record)
File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
hdlr.handle(record)
File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
self.emit(record)
File 
"/home/ci-runner/actions-runner/_work/letta/letta/.venv/lib/python3.12/site-packages/_pytest/logging.py", 
line …
```
=> fix: logger error in streaming interface

letta/interfaces/anthropic_streaming_interface.py, letta/interfaces/openai_streaming_interface.py
Stacktrace:
```
File "/home/ci-runner/actions-runner/_work/letta/letta/letta/server/rest_api/streaming_response.py", line 238, in _protected_stream_response
async for chunk in self.body_iterator:
File "/home/ci-runner/actions-runner/_work/letta/letta/letta/server/rest_api/streaming_response.py", line 103, in add_keepalive_to_stream
await reader_task
File "/home/ci-runner/actions-runner/_work/letta/letta/letta/server/rest_api/streaming_response.py", line 60, in stream_reader
async for item in stream_generator:
File "/home/ci-runner/actions-runner/_work/letta/letta/letta/agents/letta_agent_v2.py", line 280, in stream
async for chunk in response:
File "/home/ci-runner/actions-runner/_work/letta/letta/letta/agents/letta_agent_v2.py", line 494, in _step
raise …
```
=> fix: null check on span before log event

letta/services/agent_serialization_manager.py, tests/test_agent_serialization_v2.py
This PR fixes a security issue where `tool_exec_environment_variables` values (containing secrets like API keys and passwords) were being exported in plain text in agent serialization files.
The fix ensures that secret values are wiped (replaced with empty strings) during export while preserving the variable names/keys. During import, users can provide the actual secret values
via the `env_vars` parameter.
Additionally, this PR fixes a bug in the import logic where `tool_exec_environment_variables` was incorrectly treated as a list of objects instead of a `Dict[str, str]`.
Run the new test cases:
```bash
python -m pytest tests/test_agent_serialization_v2.py::TestAgentFileExport::test_tool_exec_environment_variables_scrub …
```
=> feat: Scrub env vars

letta/interfaces/openai_streaming_interface.py
Fix a critical bug in the assistant message JSON parser where it incorrectly returns nothing (None) every time. The issue occurs because the parser only enters `assistant_message_json_reader.process_json_chunk` after the message has started, but the flag that tracks this state never flips to the correct value, resulting in None being returned consistently.
**Testing:**
```
(letta) caren@mac letta % uv run pytest -s -vv tests/integration_test_send_message.py::test_token_streaming_greeting_with_assistant_message -k "gpt-4o-mini0"
NEW CHUNK:
ChoiceDeltaToolCall(index=0, id=None, function=ChoiceDeltaToolCallFunction(arguments='message', name=None), type=None)
self.last_flushed_function_name: None
NEW CHUNK:
ChoiceDeltaToolCall(index=0, id=None, …
```
=> fix: 4o mini assistant streaming error

fern/openapi-overrides.yml
Rename the `client.providers.check_provider` API endpoint to `client.providers.check`.
**Notes:**
The existing override wasn't working because the method name did not match the definition.
4. Finalizing type definitions to ensure accurate developer …
=> feat: rename provider key check method in api

letta/server/rest_api/routers/v1/tags.py, letta/services/agent_manager.py
Add pagination to the `list_tags` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:**
The default `order_by` is set to 'name' for alphabetical sorting, unlike other endpoints which typically default to creation timestamp. …
=> feat: add pagination to client.tags.list endpoint

fern/openapi-overrides.yml
Rename `client.steps.retrieve_step_metrics` to `client.steps.metrics.retrieve`.
**Notes:**
Considering consolidating the telemetry endpoints together but will revisit later.
4. Finalizing type definitions to ensure accurate developer tooling support
5. …
=> feat: rename steps metrics endpoint

letta/server/rest_api/routers/v1/__init__.py, letta/server/rest_api/routers/v1/telemetry.py
Actually, we shouldn't delete old paths yet because it will break functionality for older api versions. We should optimize for graceful deprecation where possible.
=> fix: re-add telemetry route for backwards compatibility

fern/openapi-overrides.yml
Rename message preview endpoint from `client.agents.messages.preview_raw_payload` to `client.agents.messages.preview`.
**Notes:**
The functionality is well documented in the title and docstring, so we can simplify the endpoint name. We want all our APIs to be simple, not verbose.
3. Strengthening error handling with predictable …
=> feat: rename message preview endpoint

letta/server/rest_api/routers/v1/steps.py
Add pagination to the `client.steps.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:** …
=> feat: add pagination to steps endpoint

letta/server/rest_api/routers/v1/blocks.py
Add pagination to the `client.blocks.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:** …
=> feat: add pagination to blocks endpoint

letta/server/rest_api/routers/v1/groups.py, letta/services/group_manager.py
Add pagination to the `client.groups.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:** …
=> feat: add pagination to groups endpoint

.github/scripts/model-sweep/model_sweep.py, examples/files/main.py, examples/sleeptime/sleeptime_source_example.py, fern/examples/data_sources.py, letta/utils.py, paper_experiments/doc_qa_task/doc_qa.py, paper_experiments/doc_qa_task/llm_judge_doc_qa.py, tests/helpers/endpoints_helper.py, tests/integration_test_builtin_tools.py, tests/integration_test_send_message.py, tests/integration_test_summarizer.py, tests/test_embeddings.py
Fix leaky `open` calls (never gets cleaned up, not within a context manager). This can cause file descriptor limit issues on the OS.
Most critical functions are `get_human_text` and `get_persona_text` in `letta/utils.py`.
=> fix: Fix leaky opens

letta/server/rest_api/routers/v1/sources.py
Mark all sources routes as deprecated - replaced by folders.
4. Finalizing type definitions to ensure accurate developer tooling support
5. Documenting clear compatibility guarantees and deprecation policies
This work represents the critical transition …
=> feat: mark sources routes as deprecated LET-4381

letta/server/rest_api/routers/v1/folders.py, letta/services/file_manager.py
Add pagination to the `client.folders.files.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:** …
=> feat: add pagination to folders files endpoint

letta/server/rest_api/routers/v1/folders.py
Add pagination to the `client.folders.agents.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:**
3. Strengthening error handling with predictable error codes and …
=> feat: add pagination to folders agents endpoint

letta/agent.py, letta/agents/letta_agent.py, letta/agents/letta_agent_v2.py, letta/agents/voice_agent.py, letta/orm/agent.py, letta/schemas/agent.py, letta/serialize_schemas/marshmallow_agent.py, letta/services/agent_manager.py, letta/services/agent_serialization_manager.py, letta/services/tool_executor/composio_tool_executor.py, tests/helpers/utils.py, tests/integration_test_async_tool_sandbox.py, tests/integration_test_tool_execution_sandbox.py, tests/test_agent_serialization.py, tests/test_agent_serialization_v2.py
Replace `tool_exec_environment_variables` param with `secrets` so it's a little bit more user friendly and rely on the docstring for the explanation rather than verbose naming.
**Notes:**
~~Not updating agent file in this PR since there might be nuances for the deprecation flow for that.~~ I was originally planning to not support agent file but that ended up being more complicated - instead this PR double writes both fields in agent file for this interim period before we fully cutover to the new field.
Key …
=> feat: replace tool_exec_environtment_variables with secrets

letta/services/tool_sandbox/base.py
Agents are mysteriously terminating on this step in the trace, so let's move it out of the thread offloading and into the foreground in case there are any errors being swallowed.
=> feat: don't render jinja template in thread

letta/__init__.py, letta/helpers/converters.py, letta/orm/sqlalchemy_base.py, letta/services/helpers/agent_manager_helper.py, tests/integration_test_async_tool_sandbox.py
Makes the imports to sqlite-vec even more conditional. Was having a situation where I wanted to use external letta server but I still had to import sqlite-vec for db function registration. Shouldn't be required for client-only use.
test suite
yes
n/a
no
n/a
=> chore: import sqlite-vec even more conditionally

fern/openapi-overrides.yml, fern/openapi.json, letta/schemas/step.py, letta/server/rest_api/routers/v1/steps.py, letta/services/step_manager.py
Because the joins with the messages table are expensive, we should be selective in what relationships are defined directly on the model. Messages seems reasonable tor require an extra hop, since most of the time you are likely loading the step from the original message anyway. This PR adds the new endpoint that users should hit in favor of using the field directly. 
**Notes:**
This is a soft deprecation so not removing the field off the model yet for backwards compatibility.
1. …
=> feat: add new steps messages endpoint and deprecate steps.messages field

fern/fern.config.json
- Fixed `fern docs dev` failing with `ETARGET` error by downgrading fern version from 0.90.0 to 0.83.0
- Version 0.90.0 doesn't exist on npm yet; 0.83.0 is the latest available version
=> fix: downgrade fern version from 0.90.0 to 0.83.0
