- memgpt/utils.py
> add csv support for preloading files into archival memory

- main.py
> Simplify load

- index.html
I added meta tags for [`Open Graph & Twitter`](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started).
> chore: Add Twitter Preview Card

- README.md
- main.py
- memgpt/openai_tools.py
Closes #63 
Does not break existing OpenAI support, but needs testing with an Azure OpenAI account.
> azure support

- main.py
Question: should we autoload (run `/load`, loads most recent checkpoint) by default?
if so, we need a flag to disable
if not, user will need to use `/load`
Also, should we catch ctrl-c/d and pass into /exit to get the autosave?
---
edit: upon further thought, maybe we should autoload, but only once we move to questionary?
for example, when you start main.py, you select whether or not you want to load from your last saved session
> autosave on /exit

- memgpt/local_llm/chat_completion_proxy.py
- memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
- memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py
- memgpt/local_llm/webui/settings.py
- memgpt/main.py
- also defaulted airoboros to a wrapper that supports inner monologue
> add wrapper for dolphin mistral + inner monologue wrapper

- memgpt/autogen/examples/agent_groupchat.py
- memgpt/autogen/interface.py
- memgpt/autogen/memgpt_agent.py
TODO
~~- [ ] Add TeachableAgent example (from https://github.com/microsoft/autogen/blob/main/test/agentchat/chat_with_teachable_agent.py / https://github.com/microsoft/autogen/blob/main/notebook/agentchat_teachability.ipynb)~~
> Refactored AutoGen integration + added examples folder

- memgpt/agent.py
- memgpt/memory.py
- memgpt/openai_tools.py
- Make CLI use sync memgpt agent <-- will put in a separate PR after #154 is merged in.
> Add synchronous memgpt agent

- memgpt/local_llm/chat_completion_proxy.py
- memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
- memgpt/local_llm/lmstudio/api.py
- memgpt/local_llm/lmstudio/settings.py
README updated with notes on LM Studio setup:
https://github.com/cpacker/MemGPT/blob/main/memgpt/local_llm/README.md#%EF%B8%8F-serving-your-llm-from-a-web-server-lm-studio-example
> LM Studio inference server support

- memgpt/local_llm/lmstudio/api.py
- memgpt/local_llm/webui/api.py
os.path.join breaks on windows, patch by using urljoin instead
> use urljoin instead of path.join

- memgpt/openai_tools.py
> azure typo patch

- README.md
- memgpt/utils.py
* Added ability to load .db (as shown in original README)
* This didn't work because it was being read in as the csv file, not the db
* Added README instructions to load .csv (not shown in original README)
> Added db load ability

- memgpt/autogen/README.md
- memgpt/autogen/examples/agent_groupchat.py
- memgpt/autogen/memgpt_agent.py
- memgpt/local_llm/chat_completion_proxy.py
- memgpt/openai_tools.py
- memgpt/utils.py
Example run on dolphin-2.1-mistral-7b:
```
❯ python3 examples/agent_groupchat.py
User_proxy (to chat_manager):
I want to design an app to make me one million dollars in one month. Yes, your heard that right.
--------------------------------------------------------------------------------
Product_manager (to chat_manager):
Absolutely! Let's design a groundbreaking and innovative idea that can potentially generate one million dollars within a month. Here are some high-potential software product ideas for achieving this goal:
1. Virtual Art Platform: Create a virtual reality platform that enables artists to showcase and sell their digital artwork. This could include sculptures, paintings, animations, and interactive experiences. Users can create profiles, follow other artists, and purchase …
```
> Support for MemGPT + Autogen + Local LLM

- memgpt/memory.py
> len needs to be implemented in all memory classes

- memgpt/prompts/gpt_functions.py
> Fix typos in functions spec

- memgpt/interface.py
- Removed repeating every user message like bein in debug mode
- Re-added the "dump" flag for the user message, to make it look nicer. I may "reformat" other message too when dumping, but that was what sticked out to me as unpleasant.
> Stopping the app to repeat the user message in normal use.

- memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
- memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py
- memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py
small patch to fix the following error:
`if message["function_call"]:
~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'function_call'`
> Fixing some dict value checking for function_call

- docs/autogen.md
- docs/example_data.md
- memgpt/agent.py
- memgpt/autogen/examples/agent_docs.py
- memgpt/autogen/memgpt_agent.py
> Add autogen example that lets you chat with docs

- docs/lmstudio.md
Just replacing the LMS screenshot to show the prompt formatting option.
> Update lmstudio.md to show the Prompt Formatting Option

- docs/lmstudio.md
Move asset (screenshot) from fork to main repo
> Swap asset location from #384

- .github/workflows/main.yml
Fix main.yml to not rely on requirements.txt
Runs locally
> Fix main.yml to not rely on requirements.txt

- memgpt/openai_tools.py
Hotfix openai create all with context_window kwarg. Currently all calls to create are failing.
Tested locally
> Hotfix openai create all with context_window kwarg

- memgpt/cli/cli.py
A potential fix to the issue [#426 ](https://github.com/cpacker/MemGPT/issues/426)
> Fix MemGPTAgent attach docs error

- memgpt/memory.py
Closes #428
Patch described https://github.com/cpacker/MemGPT/issues/428#issuecomment-1807197364
> Patch for #428 (context window not passed to summarize calls)

- memgpt/functions/functions.py
AFAIK local functions (inside of `~/.memgpt/functions`, not `install_location/memgpt/memgpt/functions/examples`) are not getting linked properly. This PR fixes the linking issues.
1. Create a file `~/.memgpt/functions/d20.py`:
```python
import random
def roll_d20(self) -> int:
"""
Simulate the roll of a 20-sided die (d20).
This function generates a random integer between 1 and 20, inclusive,
which represents the outcome of a single roll of a d20.
Returns:
int: A random integer between 1 and 20, representing the die roll.
Example:
>>> roll_d20()
15  # This is an example output and may vary each time the function is called.
"""
return random.randint(1, 20)
```
2. Create a file `~/.memgpt/presets/memgpt_d20.yaml`:
```yaml …
```
> Fix linking functions from `~/.memgpt/functions`

- memgpt/cli/cli_config.py
- memgpt/local_llm/chat_completion_proxy.py
- memgpt/local_llm/constants.py
- memgpt/local_llm/webui/legacy_api.py
- memgpt/local_llm/webui/legacy_settings.py
> Move `webui` backend to new openai completions endpoint

- memgpt/server/utils.py
- memgpt/server/websocket_protocol.py
- memgpt/server/websocket_server.py
Changes to support chat UI frontend on alpha frontend
> updated websocket protocol and server

- memgpt/local_llm/webui/api.py
- memgpt/local_llm/webui/settings.py
Modify contents of the POST request body to match parameters used here: https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/completions.py#L77
> patch web UI

- memgpt/personas/examples/anna_pa.txt
… your personal research assistant really good with archival documents and research.
This adds a persona for Personal Assistant for Research purposes.
- Load some documents into the Archive
- Select anna_pa during running memgpt config. 
- This will take on the ANNA Persona for interactions. 
- /attach loaded documents to Agent.
Yes, extensively with 20+ archival documents loaded with openai. 
https://github.com/cpacker/MemGPT/issues/493
No
> ANNA, an acronym for Adaptive Neural Network Assistant. personal research assistant

- memgpt/cli/cli_config.py
- memgpt/local_llm/chat_completion_proxy.py
- memgpt/local_llm/vllm/api.py
> vLLM support

- memgpt/autogen/examples/agent_autoreply.py
- memgpt/autogen/examples/agent_docs.py
- memgpt/autogen/examples/agent_groupchat.py
- memgpt/autogen/memgpt_agent.py
- memgpt/cli/cli.py
Fix various bugs in the AutoGen integration code.
Run the AutoGen examples, both with the OpenAI setup and the local LLM setup (you have to comment/uncomment different lines).
Testing:
Many (need to tag)
No
> Fixes bugs with AutoGen implementation and exampes

- docs/adding_wrappers.md
- docs/autogen.md
- docs/cli_faq.md
- docs/functions.md
- docs/koboldcpp.md
- docs/llamacpp.md
- docs/lmstudio.md
- docs/local_llm_faq.md
- docs/ollama.md
- docs/presets.md
- docs/quickstart.md
- docs/webui.md
- mkdocs.yml
Remove duplicate headers, clean TODOs, etc.
> clean docs

- docs/storage.md
> Fix typo in storage.md 

- memgpt/cli/cli.py
allow passing custom host to rest server
```
memgpt server --host 127.0.0.1
```
> allow passing custom host to rest server

- poetry.lock
- pyproject.toml
Closes #614
---
Added deps w/ `poetry add`.
Checkout this PR, just make sure that `memgpt run` still works.
> fix: poetry add [html2text/docx2txt]

- .github/workflows/semantic-prs.yml
@sarahwooders will make the squashed commits going into main cleaner, and make the tag/release notes cleaner
---
Action copied from: https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#installation
Valid pull request titles:
- fix: Correct typo
- feat: Add support for Node.js 18
- refactor!: Drop support for Node.js 12
- feat(ui): Add Button component
Note that since pull request titles only have a single line, you have to use ! to indicate breaking changes.
> feat: Add semantic PR checking to enforce prefixes on PRs

- memgpt/openai_tools.py
> fix: added logging of raw response on debug

- memgpt/main.py
Allow forcing the summarizer to run.
Run `/summarize` in the CLI.
> feat: added /summarize command

- db/Dockerfile.simple
> fix: typo in Dockerfile comment

- .github/workflows/tests.yml
- db/run_postgres.sh
Moving workflow tests to use postgres running in container created by #393
> ci: Run tests using postgres docker container

- memgpt/interface.py
Fix CLI interface to print on searches:
> fix: updated CLI interface to properly print searches on archival memory

- memgpt/local_llm/json_parser.py
- tests/test_json_parsers.py
- Add new json test case from #729
- Added patch for the test case
- Refactored cascading parser to flattened
```sh
poetry shell
python -m pytest tests/test_json_parsers.py
```
Yes
> fix: refactor + improve json parser

- docs/quickstart.md
Added install instructions if running LLMs locally.
Added instructions for Local LLM installation of memgpt via pip
N/a
N/a
N/a
No
N/a
> docs: Include steps for Local LLMs

- README.md
Documentation spelling fix.
Review the change log. (tiny change)
Yeah.
> docs: word choice in documentation

- docs/python_client.md
Tested this and it works. The API supports "human" and not "person" as previously stated.
Add any other …
> docs: Update python_client.md

- configs/memgpt_hosted.json
- memgpt/configs/memgpt_hosted.json
> fix: correct context window for dolph mixtral

- docs/python_client.md
This fixes the broken Client documentation due to recent refactoring.
> fix: Fix broken doc due to refactor

- memgpt/cli/cli_config.py
saves openai key to llm state, which fixes cli configuration
cli configured agent works correctly
tested on my machine
discussion here: https://discord.com/channels/1161736243340640419/1171281929165881384/1195184177449029632
> fix: store opeani key

- docs/webui.md
corrected typo in docs/webui. 
The title in frontmatter was oob**o**booga. 
No testing requried.
No
No related issues or PRs that I could find.
Definitely not.
No additional Context
> docs: Fixed typo in docs/webui.md

- memgpt/memory.py
> fix: fix typo in memory.py

- memgpt/server/rest_api/agents/command.py
- memgpt/server/rest_api/agents/config.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/rest_api/agents/memory.py
- memgpt/server/rest_api/agents/message.py
- memgpt/server/rest_api/config/index.py
- memgpt/server/rest_api/server.py
- memgpt/server/server.py
- memgpt/server/static_files/index.html
Various parts of the frontend + server code was written assuming it's OK to pass around `user_id`s that are dummy vars + not type `uuid.UUID`. This patch fixes those various issues enabling the chat UI to run.
In a future PR we should also adjust the frontend code to pass a real user ID (eg by reading from config file or by GETing the server config) in the requests to the backend - left as a TODO in the REST server API code.
> fix: various patches related to UUID usernames to make chatui work

- memgpt/agent.py
- memgpt/functions/schema_generator.py
- memgpt/local_llm/chat_completion_proxy.py
- memgpt/local_llm/grammars/gbnf_grammar_generator.py
- memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
- memgpt/local_llm/llm_chat_completion_wrappers/chatml.py
- memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py
- memgpt/local_llm/llm_chat_completion_wrappers/simple_summary_wrapper.py
- memgpt/local_llm/llm_chat_completion_wrappers/wrapper_base.py
- memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py
- tests/test_server.py
Add support for pydantic models (also nested ones) for custom functions
Custom function for testing:
```python
from typing import List, Any
from pydantic import Field, BaseModel
class RowData(BaseModel):
row: List[Any] = Field(..., description="The values for each row")
citation: str = Field(
..., description="The citation for this row from the original source data"
)
class Dataframe(BaseModel):
"""
Class representing a dataframe. This class is used to convert
data into a frame that can be used by pandas.
"""
name: str = Field(..., description="The name of the dataframe")
data: List[RowData] = Field(
...,
description="Correct rows of data aligned to column names, Nones are allowed",
)
columns: List[str] = Field(
..., …
```
> feat: Support pydantic models as parameters to custom functions

- .github/workflows/black_format.yml
- .github/workflows/main.yml
- .github/workflows/poetry-publish-nightly.yml
- .github/workflows/poetry-publish.yml
- .github/workflows/rdme-openapi.yml
- .github/workflows/tests.yml
- tests/test_cli.py
This change simplifies and aligns all actions to use the same Poetry install method. It also removes some extra Poetry config that is now handled by `packetcoders/action-setup-cache-python-poetry`.
n/a
n/a
#845 
#844
n/a
This also contains the changes in #844 and #845 - Those should be merged before this.
> build: Update all actions to use cached poetry builds

- .github/workflows/semantic-prs.yml
- .github/workflows/tests.yml
Simple change to rename two github actions jobs.
n/a
n/a
n/a
n/a
n/a
> build: Rename Github actions to improve clarity

- tests/clear_postgres_db.py
Use an external environment variable for the postgres URI
n/a
n/a
Follow-up to #863
n/a
n/a
> fix: Remove the hard-coded database URI in the test helper to use an env var

- docs/contributing_code.md
Use `--all-extras` for poetry install guide in docs
> docs: Update contributing_code.md

- memgpt/server/rest_api/agents/config.py
Fix bad docstring for delete agent endpoint
> docs: Update config.py

- memgpt/migrate.py
> fix: account for trailing space in timestamp

- README.md
Adding "benchmark" section at the bottom of the readme.md
There is nothing to test, as this is just a simple update on readme.md
No
No
Upon @cpacker's approval, I have created a MemGPT performance chart to compare different open source models' performances on MemGPT function calling.
> docs: Include information regarding benchmarking

- memgpt/prompts/system/memgpt_modified_chat.txt
I added an additional memgpt_chat prompt I modified  trying to make it more clear for the LLM what to do.
> feat: Add memgpt_modified_chat.txt

- memgpt/agent_store/db.py
- memgpt/metadata.py
automatically close them
closes db sessions, preventing orphaned sessions from building up. probably not an issue for sqlite, but good to be consistent
normal test suite should cover
> fix: update remaining sqlalchemy sessions

- memgpt/cli/cli.py
- memgpt/data_types.py
- memgpt/metadata.py
- memgpt/server/server.py
- tests/test_load_archival.py
- tests/test_metadata_store.py
- tests/test_storage.py
remove default_human, default_preset, and default_persona from user config.
rely on global config for these values instead
simplify configuration, fix unexpected behavior in agent initialization
tests provide coverage, configured defaults should be respected
> fix: simplify user config

- memgpt/cli/cli_config.py
during memgpt configure the process fails because we pass in arguments that have been removed.
Also optimized some imports
Run `memgpt configure` after deleting your `.memgpt` folder
I have. I tried to add a test, but wasn't sure how to write a test that depends on no configuration to exist.
**Is your …
> fix: remove unexpected arguments for user

- memgpt/migrate.py
- tests/test_migrate.py
* Call `save_agent(agent, ms)` in `migrate.py` (was not saving agents in metadata store before) 
* Modify tests to create a temporary copy of test data, to avoid editing git tracked files 
* Check via server and metadata store for proper migration in tests
> fix: Check existing of migrated agents and sources in tests + fix migrated agent saving bug

- memgpt/agent.py
- memgpt/agent_store/chroma.py
- memgpt/agent_store/db.py
- memgpt/agent_store/lancedb.py
- memgpt/autogen/memgpt_agent.py
- memgpt/cli/cli_load.py
- memgpt/config.py
- memgpt/data_types.py
- memgpt/embeddings.py
- memgpt/interface.py
- memgpt/migrate.py
- memgpt/server/server.py
- memgpt/utils.py
Patch fatal attribute errors in pyright. See #916 (previous #855 )
> fix: resolve fatal attribute errors in pyright

- docs/cli_faq.md
Added more information to FAQ. 
No tests needed. 
No
> docs: Update cli_faq.md to include information about personas, agents and humans

- docs/cli_faq.md
Added information about multi-user setup into the FAQ.
> docs: Update cli_faq.md for multi-user faq

- memgpt/llm_api_tools.py
see: https://discord.com/channels/1161736243340640419/1162177332350558339/1199811825932447825
> fix: do not try to iterate over None

- docs/cli_faq.md
> docs: Update cli_faq.md for spelling issues

- docs/storage.md
Added instructions to get up and running with docker
This adds the Docker Container instructions to the documentation. Instructions were generously provided by @sarahwooders
> fix: Update storage.md to include instructions for running the Docker container

- memgpt/cli/cli.py
- memgpt/migrate.py
- memgpt/utils.py
Improve migration scripts.
Initialize home dir with old directory copy:
```sh
rm -rf ~/.memgpt
cp -r ~/.memgpt-backup-dec22-436-total-agents ~/.memgpt
```
Run `memgpt run` to set up the config:
```sh
memgpt run
```
```
Your current config file is incompatible with MemGPT versions later than 0.2.12
? To use MemGPT, you must either downgrade your MemGPT version (<= 0.2.12), or regenerate your config. Would you like to proceed? Create a new config using defaults
Deleted config file (/Users/loaner/.memgpt/config) and saved as backup (/Users/loaner/.memgpt/migration_backups/config_backup_20240129_171926)
Note: if you would like to migrate old agents to the new release, please run `memgpt migrate`!
? How would you like to set up MemGPT? Use the free MemGPT endpoints
📖 MemGPT configuration file …
```
> fix: misc updates to the migration code to improve migration UX

- memgpt/local_llm/llm_chat_completion_wrappers/airoboros.py
- memgpt/local_llm/llm_chat_completion_wrappers/chatml.py
- memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py
- memgpt/local_llm/llm_chat_completion_wrappers/simple_summary_wrapper.py
- memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py
> fix: patch bug in airo wrapper

- .github/workflows/rdme-openapi.yml
> ci: run quickstart before memgpt server

- .github/workflows/rdme-openapi.yml
- memgpt/server/rest_api/server.py
Splits OpenAPI json file into two to allow clean separation + syncing on docs page
> docs: cleanup API page

- .github/workflows/rdme-openapi.yml
> ci: Update rdme-openapi.yml

- memgpt/cli/cli.py
- memgpt/server/server.py
Attempt to fix #966
See conversation here: https://github.com/cpacker/MemGPT/issues/966#issuecomment-1949322836
> fix: removed superfluous create_agent calls

- memgpt/server/rest_api/admin/users.py
fixed bug on line 144 returning the wrong model
> fix: Corrected response_model usage

- memgpt/functions/function_sets/base.py
- memgpt/prompts/gpt_functions.py
> fix: Patch typo in base.py

- memgpt/server/rest_api/admin/users.py
- memgpt/server/rest_api/agents/command.py
- memgpt/server/rest_api/agents/config.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/rest_api/agents/memory.py
- memgpt/server/rest_api/agents/message.py
- memgpt/server/rest_api/auth/index.py
- memgpt/server/rest_api/auth_token.py
- memgpt/server/rest_api/config/index.py
- memgpt/server/rest_api/humans/index.py
- memgpt/server/rest_api/models/index.py
- memgpt/server/rest_api/personas/index.py
- memgpt/server/rest_api/server.py
endpoint that simulates admin sign in
New feature
Hit endpoints with Bearer ADMIN_PASSWORD_PRINTED_ON_SERVER_START
**Additional …
> feat: allow admin to access all API routes & add back auth 

- memgpt/config.py
this prevents nulled out anon-client id, which is a state that doesn't make sense
> fix: set default, all 0 anon UUID

- .github/workflows/tests.yml
- memgpt/agent.py
- memgpt/autogen/examples/agent_docs.py
- memgpt/autogen/examples/agent_groupchat.py
- memgpt/autogen/memgpt_agent.py
- tests/test_autogen_integration.py
> fix: patch AutoGen integration for `0.3.5` + add AutoGen integration tests

- memgpt/server/rest_api/admin/users.py
- Patch bug with getting user API keys, see [Discord message](https://discord.com/channels/1161736243340640419/1162177332350558339/1215403268327608421) for details
> fix: patch API key GET error + allow empty body on create user POST

- .github/workflows/tests.yml
- memgpt/cli/cli_load.py
- memgpt/client/client.py
- memgpt/data_sources/connectors.py
- memgpt/models/pydantic_models.py
- memgpt/server/rest_api/admin/users.py
- memgpt/server/rest_api/agents/config.py
- memgpt/server/rest_api/server.py
- memgpt/server/rest_api/sources/index.py
- memgpt/server/server.py
- poetry.lock
- pyproject.toml
- tests/test_client.py
This PR adds support for loading and attaching source data via the REST API server, including uploading a file to be loaded into a source. 
`pytest -s tests/test_client.py`
#1005
> feat: Add data sources to REST API 

- memgpt/server/rest_api/tools/index.py
> feat: add (dummy) create tool route

- memgpt/server/rest_api/agents/message.py
- memgpt/server/server.py
> feat: expose cursor based retrieval of previous messages

- memgpt/server/rest_api/agents/memory.py
> fix: fix key typo when getting archival memory response

- memgpt/server/rest_api/tools/index.py
> fix: correct dummy tools api call response

- memgpt/server/rest_api/agents/index.py
Bug resurfaced where persona/human values were being set to their names and not the content. Hotfix.
> fix: patch agent creation bug that resurfaced

- docs/api.md
SImply fixing the docs. It appears there's a mismatch between the [API documentation ](https://memgpt.readme.io/reference/send_message_api_agents__agent_id__messages_post) and this document. Executing the curl command as provided results in a 405 error response.
After running `memgpt server` execute the following command once agent is created and response would be 405
```
curl --request POST \
--url http://localhost:8283/api/agents/message \
--header 'authorization: Bearer ilovellms' \
--header 'content-type: application/json' \
--data …
```
> docs: Update api.md

- memgpt/server/rest_api/sources/index.py
- memgpt/server/server.py
> fix: write temporary file for REST upload file endpoint + return number added passages/documents

- .github/workflows/tests.yml
- compose.yaml
- db/run_postgres.sh
- docs/storage.md
- init.sql
- memgpt/agent_store/db.py
- memgpt/metadata.py
- memgpt/server/rest_api/sources/index.py
- scripts/pack_docker.sh
- tests/clear_postgres_db.py
- tests/test_admin_client.py
- tests/test_client.py
- tests/test_load_archival.py
- tests/test_metadata_store.py
- tests/test_server.py
- tests/test_storage.py
> feat: client tests for `docker compose` server

- memgpt/functions/schema_generator.py
Due to the criticality of [this pool request](https://github.com/cpacker/MemGPT/pull/661), as well as the fact that its author has not been active for a long time, I decided to make it anew.
Allows the usage of list[str] as a parameter and return type in MemGPT functions
I could use some help with that. Even when testing on the main branch, a lot of errors are thrown. It may be necessary to configure testing correctly, but I do not understand how to do this.
But in general, I did not notice the difference between the errors in main and in this branch.
[this pool request](https://github.com/cpacker/MemGPT/pull/661)
No
> fix: Handle list[str] in function schema(continuation)

- .github/workflows/tests.yml
Patch bug in tests (fallback was not set to be the hosted properly), triggering fails on contributor PRs, eg:
https://github.com/cpacker/MemGPT/actions/runs/8541729158/job/23401731962
> fix: patch tests.yml

- memgpt/prompts/system/memgpt_chat.txt
> fix: Fixing the last issue with memgpt_chat.txt

- memgpt/main.py
Patches `/rethink`, previously was silently failing.
> fix: patch `/rethink`

- memgpt/main.py
Before:
```
🎉 Created new agent 'InspiringWalrus' (id=c5acbdf8-2130-4e66-aec3-08b3511294e6)
Hit enter to begin (will request first MemGPT message)
💭 A new user has logged in. Gathering initial thoughts and preparing a welcoming message.
🤖 Hello, Chad! Lovely to meet you. I’m always here if you need someone to explore ideas with or 
maybe to challenge some conventional wisdom. What's on your mind today?
> Enter your message: sup m8
💭 Interesting. A casual greeting from the user. Must form a response keeping in line with my 
persona's empathetic and engaging communication style.
🤖 Hello there! I'm curious, how's your day going so far?
> Enter your message: /pop
Popping last 3 messages from stack
> Enter your message: /dump
[9] 🖥️ [system] You are MemGPT, the latest version of Limnal …
```
> fix: patched pop

- memgpt/server/server.py
- Make `GET /agents` list returned sorted by `Last run`
- TODO in future PR: make this route paginated, it's noticeably slow (>1s) when the list of agents is large
---
> feat: misc server updates

- memgpt/functions/functions.py
- memgpt/metadata.py
- memgpt/models/pydantic_models.py
> fix: misc bugs

- examples/personal_assistant_demo/README.md
- examples/personal_assistant_demo/charles.txt
- examples/personal_assistant_demo/gmail_test_setup.py
- examples/personal_assistant_demo/gmail_unread_polling_listener.py
- examples/personal_assistant_demo/google_calendar.py
- examples/personal_assistant_demo/google_calendar_preset.yaml
- examples/personal_assistant_demo/google_calendar_test_setup.py
- examples/personal_assistant_demo/personal_assistant_preset.yaml
- examples/personal_assistant_demo/twilio_flask_listener.py
- examples/personal_assistant_demo/twilio_messaging.py
- examples/personal_assistant_demo/twilio_messaging_preset.yaml
- memgpt/functions/functions.py
See README: https://github.com/cpacker/MemGPT/tree/personal-assistant-demo/examples/personal_assistant_demo
> feat: Add personal assistant demo code from meetup

- memgpt/cli/cli.py
- memgpt/config.py
- memgpt/metadata.py
- memgpt/server/rest_api/server.py
- The current error dump when eg postgres isn't connected is pretty hard to parse
- This PR updates the messaging to be a little friendlier
> chore: better database errors

- .github/workflows/isort_format.yml
- memgpt/metadata.py
- memgpt/server/rest_api/tools/index.py
- tests/data/memgpt-0.2.11/agents/agent_test/config.json
- tests/data/memgpt-0.2.11/agents/agent_test_attach/config.json
- tests/data/memgpt-0.2.11/agents/agent_test_empty_archival/config.json
> fix: patch tests

- README.md
> docs: add install instructions for docker

- configs/server_config.yaml
> fix: hardcoded version in server_config.yaml

- .github/workflows/docker-integration-tests.yaml
> fix: update docker test

- examples/personal_assistant_demo/README.md
Fix gmail listener script name.
> docs: Update README.md

- docs/storage.md
- memgpt/agent_store/milvus.py
- memgpt/cli/cli_config.py
- poetry.lock
- pyproject.toml
continue from this [pr](https://github.com/cpacker/MemGPT/pull/1198)
> feat: update milvus and milvus-lite dependency

- docs/storage.md
Refine the storage setup documents for milvus lite setting
Related PR [(https://github.com/cpacker/MemGPT/pulls).](https://github.com/cpacker/MemGPT/pull/1405)
> docs: update setup for milvus lite

- memgpt/server/rest_api/sources/index.py
the @pavel604 fix https://github.com/cpacker/MemGPT/issues/1352#issuecomment-2099250518 works for me to resolve @hqzhon issue #1352
> fix: #1532 upload sources file error "I/O operation on closed file"

- .github/workflows/docker-integration-tests.yaml
- memgpt/client/client.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/server.py
- tests/test_concurrent_connections.py
Locks on the server class are causing strange issues, so removing it for now. Locks should eventually be moved into the `Agent` class (or we should use queues instead). 
`pytest -s tests/test_concurrent_connections.py`
Yes 
#1438
> fix: remove server locking on agents 

- .github/workflows/test_ollama.yml
- README.md
- examples/resend_example/README.md
- memgpt/cli/cli_config.py
- memgpt/client/client.py
- memgpt/server/server.py
- tests/test_new_cli.py
> feat: Migrating CLI to run on MemGPT Client for `memgpt [list/add/delete]` (#1428)

- memgpt/agent.py
- memgpt/client/admin.py
- memgpt/client/client.py
- memgpt/functions/functions.py
- memgpt/server/server.py
- tests/test_tools.py
Add support to tool calling to `LocalClient` 
`poetry run pytest -s tests/test_tools.py`
Yes
> feat: add more tool calling support to `LocalClient` 

- memgpt/cli/cli.py
> fix: fix ugly dev tool print in cli

- memgpt/data_types.py
> fix: check tool call type 

- memgpt/agent.py
> fix: drop print from #1465

- memgpt/agent.py
- memgpt/presets/presets.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/server.py
> fix: more server patches for dev portal 

- memgpt/agent.py
Patch type error introduced in #1503
> fix: patch type error

- memgpt/server/rest_api/agents/message.py
Nit: update docs from 'stream = True' to 'stream_steps = True', to match error msg
`        raise HTTPException(status_code=400, detail="stream_steps must be 'true' if stream_tokens is 'true'")
`
> fix: update docs to say 'stream_steps = True'

- memgpt/client/client.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/server.py
Due to the core memory refactor, core memory tools were not being properly added. 
View the developer portal 
Yes 
#1538 
No
> fix: add memory tools from dev portal 

- memgpt/cli/cli_config.py
- memgpt/client/client.py
- memgpt/models/pydantic_models.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/server.py
- tests/test_cli.py
- tests/test_client.py
Various CLI commands `memgpt [list/add/delete] [persona/source/human/agent]` were outdated, and also needed to be migrated to run on the `LocalClient`.
> fix: fix CLI commands by migrating to Python client 

- memgpt/llm_api/openai.py
Parallel tool calling is not handled by MemGPT, so need to be disabled.
> feat: disable parallel tool calling 

- memgpt/agent_store/db.py
- tests/test_server.py
> fix: sort order

- memgpt/client/client.py
- memgpt/server/server.py
* implement `client.get_agent(agent_id) -> AgentState`
* allow sending message by `agent_name`
> feat: various fixes to improve notebook useability 

- memgpt/client/client.py
- memgpt/persistence_manager.py
- memgpt/schemas/memory.py
- memgpt/server/server.py
- tests/test_memory.py
- tests/test_new_client.py
- tests/test_tools.py
Passes tests:
```sh
poetry run pytest -sv tests/test_new_client.py
```
> feat: validate `memory.memory` edits + patch bug due to not returning copy of `AgentState`

- memgpt/client/client.py
- memgpt/server/rest_api/agents/index.py
- memgpt/server/rest_api/tools/index.py
- memgpt/server/server.py
- tests/test_client.py
> make it possible to create agents via the REST API 

- memgpt/client/client.py
- memgpt/server/rest_api/agents/index.py
- tests/test_client.py
Add a REST endpoint for listing attached sources for an agent. 
Added a test in `test_client.py::test_source` to test that attached sources are properly listed. 
Yes
No
> feat: add endpoint to list agent's attached sources

- memgpt/client/client.py
- memgpt/schemas/tool.py
- memgpt/server/rest_api/block/index.py
- memgpt/server/rest_api/tools/index.py
- memgpt/server/server.py
* Fix `user_id` error with updating block endpoints 
* Auto-generate JSON schema on server if not provided by the client 
`tests/test_tools.py`
Yes
> feat: generate JSON schema from source code on the server side

- tests/test_client.py
> fix: hotfix for PR #1693

- .github/workflows/test_anthropic.yml
- configs/llm_model_configs/anthropic.json
- memgpt/cli/cli.py
- memgpt/configs/anthropic.json
- memgpt/llm_api/anthropic.py
- memgpt/schemas/message.py
- tests/test_endpoints.py
* Patch issues with anthropic from the refactor 
* Add a `memgpt quickstart --backend anthropic` option 
* Add tests for anthropic endpoint 
`tests/test_endpoints.py`
Yes
> fix: various fixes to patch anthropic integration

- .github/workflows/black_format.yml
- .github/workflows/isort_format.yml
Instead of failing, isort and black just fix the issues and commit them
This is a tough one. you could use ACT but that's a huge lift to test some CI scripts. So let's just try them in GH and see if they work.
As best as can be with github actions without setting up ACT which is a pain.
> feat: autocommit linting

- .github/workflows/black_format.yml
- .github/workflows/isort_format.yml
> fix: patch workflows second attempt

- memgpt/autogen/interface.py
- memgpt/interface.py
- memgpt/llm_api/google_ai.py
- memgpt/local_llm/grammars/gbnf_grammar_generator.py
- memgpt/local_llm/llm_chat_completion_wrappers/dolphin.py
- memgpt/local_llm/llm_chat_completion_wrappers/llama3.py
- memgpt/local_llm/llm_chat_completion_wrappers/simple_summary_wrapper.py
- memgpt/local_llm/llm_chat_completion_wrappers/zephyr.py
- memgpt/server/rest_api/routers/v1/agents.py
- memgpt/server/rest_api/routers/v1/blocks.py
- memgpt/server/rest_api/routers/v1/jobs.py
- memgpt/server/rest_api/routers/v1/llms.py
- memgpt/server/rest_api/routers/v1/sources.py
- memgpt/server/rest_api/routers/v1/tools.py
- memgpt/server/rest_api/routers/v1/users.py
- memgpt/server/ws_api/example_client.py
- memgpt/server/ws_api/protocol.py
- memgpt/server/ws_api/server.py
- tests/test_function_parser.py
Gives an operation_id to all requests
> chore: normalize operation ids

- memgpt/client/admin.py
- memgpt/server/rest_api/app.py
- memgpt/server/rest_api/utils.py
Patch issue with CI failing on `assert` but passing fine locally.
> fix: hotfix for server test

- memgpt/schemas/memory.py
- memgpt/server/rest_api/routers/v1/agents.py
- memgpt/server/server.py
Fixes required to get create agent on REST to work.
Note @4shub there's still that press-edit-then-value-is-broken error (seems client-side).
> fix: various fixes to get create agent REST API to work

- .github/workflows/tests.yml
- README.md
- examples/helper.py
- letta/client/client.py
- letta/llm_api/llm_api_tools.py
- letta/schemas/llm_config.py
- letta/server/rest_api/app.py
- letta/server/server.py
- letta/settings.py
- paper_experiments/doc_qa_task/doc_qa.py
- paper_experiments/nested_kv_task/nested_kv.py
- tests/test_client.py
- tests/test_new_client.py
- tests/test_server.py
> fix: various fixes for workflow tests

- README.md
> docs: patch link

- letta/agent.py
- letta/server/server.py
- tests/test_tools.py
> fix: use JSON schema name instead of tool name for loading from env

- letta/benchmark/benchmark.py
Fix small benchmark bugs:
- `client` was not defined
- extraneous args
> fix: Fix small benchmark bugs

- letta/cli/cli.py
- letta/server/rest_api/app.py
- letta/settings.py
> chore: allow app.letta.com access to local if user grants permission

- letta/server/server.py
Remove testing print. No testing required.
> fix: remove testing print

- letta/llm_api/anthropic.py
- letta/llm_api/azure_openai.py
Factor out repeat POST request logic. Unit tests catch refactoring errors.
> fix: factor out repeat POST request logic

- .github/workflows/test_cli.yml
- .github/workflows/tests.yml
- letta/agent_store/db.py
- letta/cli/cli.py
- letta/client/utils.py
- letta/embeddings.py
- letta/interface.py
- letta/llm_api/google_ai.py
- letta/llm_api/helpers.py
- letta/llm_api/llm_api_tools.py
- letta/llm_api/openai.py
- letta/local_llm/constants.py
- letta/providers.py
- letta/server/server.py
- letta/settings.py
- letta/streaming_interface.py
- tests/helpers/endpoints_helper.py
- tests/test_cli.py
- tests/test_client.py
- tests/test_endpoints.py
Testing OpenRouter support via overriding OPENAI_API_KEY and OPENAPI_BASE_URL.
Seems to be working:
```sh
% letta run                         
? Select LLM model: (Use arrow keys)
» memgpt-openai
meta-llama/llama-3.2-11b-vision-instruct:free
meta-llama/llama-3.2-1b-instruct:free
meta-llama/llama-3.2-3b-instruct:free
meta-llama/llama-3.1-8b-instruct:free
google/gemini-pro-1.5-exp
google/gemini-flash-1.5-exp
google/gemini-flash-1.5-8b-exp
meta-llama/llama-3.2-1b-instruct
meta-llama/llama-3.2-3b-instruct
google/gemini-flash-1.5-8b
mistralai/mistral-7b-instruct
mistralai/mistral-7b-instruct-v0.3
meta-llama/llama-3-8b-instruct
meta-llama/llama-3.1-8b-instruct
meta-llama/llama-3.2-11b-vision-instruct …
```
> feat: working openrouter support

- .github/workflows/test_groq.yml
> chore: add e2e tests for Groq to CI

- .github/workflows/test_azure.yml
- letta/llm_api/azure_openai.py
- letta/llm_api/helpers.py
- letta/settings.py
Fix Azure tests and write CI tests - small PR, so leaving this intentionally brief. CI passes:
> test: Fix Azure tests and write CI tests

- examples/composio_tool_usage.py
- letta/schemas/llm_config.py
Modify composio example to work - it's broken after a couple of config changes.
> fix: modify composio example

- README.md
> docs: patch readme

- docs/markdown/index.md
> docs: update index.md

- letta/client/client.py
- letta/metadata.py
- letta/server/rest_api/app.py
- letta/server/rest_api/routers/v1/tools.py
- letta/server/server.py
- tests/test_client.py
- tests/test_new_client.py
Add pagination for list tools endpoint
Write a comprehensive unit test testing grabbing tools in chunks, and seeing if we can completely grab all the tools available.
> feat: Add pagination for list tools

- poetry.lock
- pyproject.toml
chore: bump composio version for stability
> chore: bump composio version for stability

- tests/conftest.py
- tests/helpers/mock_llm.py
- tests/helpers/utils.py
- tests/test_client.py
Create a mock_llm helper class that can intercept the public api calls to llms if a static response is sufficient for the unit test. Right now the default param is to use the public api, but once stable the default should be mock. The modifications to test_client.py are simply to show what the integration would look like, not something that would be landed as part of this PR 
Normal test run (calls public api):
`poetry run pytest -s -vv tests/test_client.py::test_agent_interactions`
With mock api
`poetry run pytest -s -vv tests/test_client.py::test_agent_interactions --llm-api=mock`
```
(letta-py3.12) carenthomas@Jeffs-MacBook-Pro-2 MemGPT % poetry run pytest -s -vv …
```
> Add mock llm api for unit tests that only require static response

- letta/server/rest_api/routers/v1/agents.py
- letta/server/rest_api/utils.py
Add usage data streaming to POST SSE (was missing).
---
Example:
```
data: {"id":"message-201caa6d-db27-4c09-914f-14221f33a917","date":"2024-10-30T00:28:02+00:00","message_type":"internal_monologue","internal_monologue":""}
data: {"id":"message-201caa6d-db27-4c09-914f-14221f33a917","date":"2024-10-30T00:28:02+00:00","message_type":"internal_monologue","internal_monologue":"The"}
data: {"id":"message-201caa6d-db27-4c09-914f-14221f33a917","date":"2024-10-30T00:28:02+00:00","message_type":"internal_monologue","internal_monologue":" user"}
data: {"id":"message-201caa6d-db27-4c09-914f-14221f33a917","date":"2024-10-30T00:28:02+00:00","message_type":"internal_monologue","internal_monologue":" just"}
data: {"id":"message-201caa6d-db27-4c09-914f-14221f33a917","date":"2024-10-30T00:28:02+00:00","mes …
```
> feat: added returning usage data

- letta/client/client.py
- letta/client/streaming.py
- letta/constants.py
- letta/schemas/letta_response.py
- letta/server/rest_api/app.py
- letta/server/rest_api/routers/v1/organizations.py
- letta/server/server.py
- tests/test_client.py
Fix create organization and streaming bugs
> fix: Fix create organization bug

- letta/client/client.py
- letta/constants.py
- letta/orm/sqlalchemy_base.py
- letta/server/rest_api/routers/v1/tools.py
- letta/server/server.py
- letta/services/tool_manager.py
- tests/test_client.py
- tests/test_tools.py
Add endpoint to add base tools to an org. This also adds a client function on the RESTClient to add base tools.
Also, this improves error messaging in the base ORM class.
Added a basic unit testing checking that the returned tools from adding the base tools are correct.
> feat: Add endpoint to add base tools to an org

- letta/schemas/tool.py
- letta/services/tool_manager.py
> chore: Tweak composio log levels

- letta/services/organization_manager.py
> chore: Remove extra print statements

- README.md
View https://github.com/cpacker/MemGPT/blob/cpacker-patch-1/
> docs: update badges in readme

- Dockerfile
> chore: install all extras for prod

- letta/server/server.py
Resync agents when tools are missing
> fix: Resync agents when tools are missing

- letta/server/server.py
> Revert "fix: Resync agents when tools are missing"

- letta/server/server.py
- tests/test_server.py
Continue relaxing tool constraints on agent create and load. Basically, any tool names that are invalid get ignored, instead of throwing a fatal error.
We write a simple test to test that the invalid tool does NOT get added, and does not throw an error on create/load.
> chore: Continue relaxing tool constraints

- letta/server/rest_api/routers/v1/users.py
Allow api access to update users
> chore: add endpoint to update users

- .github/workflows/letta-web-safety.yml
Retriggering the web saftey workflow so it doesnt record
> chore: retrigger the workflow

- CITATION.cff
> fix: Update CITATION.cff

- .github/workflows/poetry-publish-nightly.yml
- .github/workflows/poetry-publish.yml
> fix: patch workflows

- .github/workflows/letta-web-openapi-saftey.yml
- .github/workflows/letta-web-safety.yml
Add openapi compatibility checker
> feat: add openapi compatibility checker

- .github/workflows/test_openai.yml
- letta/agent_store/db.py
- letta/llm_api/openai.py
- letta/memory.py
- tests/helpers/endpoints_helper.py
- tests/test_endpoints.py
Fix memory summarization. Memory summarization was broken for models that put `inner_thoughts_in_kwargs`. 
> This is because for summarization, we construct a standard `user` `assistant` message flow that does not have inner thoughts, function calls, etc. When the `LLMConfig` requires `inner_thoughts_in_kwargs`, this causes the assistant message content to be `None`, which triggers an error on the LLM API.
Tested manually via CLI and added a CI test for the live gpt-4o capabilities test.
> fix: Fix memory summarization 

- letta/cli/cli.py
- letta/server/rest_api/app.py
adds a new flag `--secure` that generates a password that can be used for light securing a web service
> feat: support a new secure flag

- letta/client/client.py
> fix: Fix tool deletion bug

- .github/workflows/integration_tests.yml
- .github/workflows/test_anthropic.yml
- .github/workflows/test_azure.yml
- .github/workflows/test_groq.yml
- .github/workflows/test_memgpt_hosted.yml
- .github/workflows/test_ollama.yml
- .github/workflows/test_openai.yml
- .github/workflows/tests.yml
- .gitignore
- examples/tool_rule_usage.py
- letta/agent.py
- letta/llm_api/anthropic.py
- tests/configs/llm_model_configs/claude-3-5-haiku.json
- tests/integration_test_summarizer.py
- tests/test_agent_tool_graph.py
- tests/test_model_letta_perfomance.py
Fix summarizer for Anthropic and add integration tests. Also rename several testing files for accuracy.
> fix: Fix summarizer for Anthropic and add integration tests

- letta/agent.py
- letta/main.py
```
% letta run                                                
? Select LLM model: gpt-4 [type=openai] [ip=https://api.openai.com/v1]
? Select LLM context window limit (hit enter for default): 4001
? Select embedding model: letta-free [type=hugging-face] [ip=https://embeddings.memgpt.ai]
->  🛠️  7 tools: send_message, conversation_search, conversation_search_date, archival_memory_insert, archival_memory_search, core_memory_append, core_memory_replace
🎉 Created new agent 'QuickApple' (id=agent-ac297c2b-f9e7-4882-9acb-3f7d6d8be3c2)
Hit enter to begin (will request first Letta message)
💭 Chad's first login. I should welcome him to set a friendly …
```
> feat: added token counter command to CLI

- letta/functions/functions.py
This fixes a bug
https://github.com/biltrewards/gen-ai/issues/2
File "/Users/gregory/.virtualenvs/gen-ai/lib/python3.12/site-packages/letta/functions/functions.py", line 21, in derive_openai_json_schema
exec(source_code, env)
File "", line 1, in …
> Add missing import in functions.py

- .github/workflows/test_ollama.yml
Fix ollama CI test - also, make the test bootup much more descriptive to help debugging.
> fix: Fix ollama CI test

- letta/embeddings.py
Unblock work involving pip installs.
> fix: Lazy load `llamaindex` imports that are causing issues

- letta/agent_store/db.py
> fix: silence bad print

- letta/local_llm/utils.py
added extra safeguard against non-string function definition, also softened the valueerror to a warnings for potentially bricked agents
> fix: extra safety checks in the token counter for functions

- letta/services/block_manager.py
> fix: Fix block model dump

- letta/orm/sqlalchemy_base.py
Add more log statements to base orm
> chore: Add more log statements to base orm

- letta/server/rest_api/app.py
> fix: update url

- .github/workflows/letta-web-safety.yml
> chore: add record key

- letta/cli/cli.py
Yes, fixing #2127 
Use the CLI, create an agent, then chat. Do /exit ... do letta run again, choose the same agent, send one chat message again (error appears)
Yes, but testing was showing many errors from other scripts not related.
#2127 
If so, please break up …
> fix: Fixed Issue #2127

- letta/local_llm/utils.py
- letta/metadata.py
- letta/services/tool_execution_sandbox.py
Current status of `letta run` is pretty messy in the CLI. This PR cleans it up.
> fix: cleanup CLI tool prints

- README.md
> docs: remove dollar prefix, make it convenient to copy

- letta/server/rest_api/routers/v1/agents.py
- letta/server/server.py
- letta/services/per_agent_lock_manager.py
- letta/utils.py
- tests/helpers/endpoints_helper.py
- tests/test_cli.py
- tests/test_client.py
Add lock around loading agents. Also, persist the agent after loading it.
Rely on existing tests, such as `test_send_message_parallel`.
> feat: Add lock around loading agent 

- letta/schemas/tool.py
- letta/server/rest_api/routers/v1/tools.py
> fix: patch bug in pydantic request model for `/v1/tools/run`

- .github/workflows/check_for_new_prints.yml
- letta/cli/cli.py
> chore: added new test to flag stray prints in new PRs

- letta/cli/cli.py
- letta/schemas/block.py
> fix: fix core memory limits hardcoded (draw from constant instead)

- letta/agent.py
- letta/schemas/agent.py
- letta/server/server.py
- tests/test_client.py
- tests/test_client_legacy.py
> fix: support initializing with custom message sequences 

- letta/server/rest_api/routers/v1/sources.py
> feat: return 404 if source not exists

- letta/server/rest_api/app.py
- poetry.lock
- pyproject.toml
> feat: add sentry logging (optional)

- .github/workflows/close_stale_issues.yml
- .github/workflows/manually_clear_old_issues.yml
https://docs.github.com/en/actions/use-cases-and-examples/project-management/closing-inactive-issues
> chore: add workflow files for closing stale issues

- .github/workflows/manually_clear_old_issues.yml
> chore: update workflow

- letta/server/rest_api/routers/v1/agents.py
- letta/server/rest_api/routers/v1/blocks.py
Some warnings I was noticing while debugging the docker image
> fix: fix runtime warnings with the server

- letta/cli/cli.py
- letta/server/rest_api/app.py
> chore: drop ade flag

- letta/client/client.py
- letta/llm_api/openai.py
- letta/schemas/tool.py
- tests/helpers/endpoints_helper.py
- tests/test_client_legacy.py
Patch dummy message and fix streaming test. Also, disable default composio tools.
> fix: Patch dummy message and fix test

- alembic/versions/d27a33843feb_migrate_messages_to_the_orm.py
- letta/agent.py
- letta/client/client.py
- letta/orm/message.py
- letta/schemas/message.py
- letta/server/rest_api/routers/v1/agents.py
- letta/server/server.py
- letta/services/message_manager.py
- tests/test_client_legacy.py
- tests/test_managers.py
Moving messages to the original way of updating s.t. the metadata fields are correctly populated
> fix: Updating messages

- letta/orm/sqlalchemy_base.py
- tests/test_client.py
> fix: bad print in common cli

- letta/client/client.py
> fix: bug in get_tool_id

- letta/offline_memory_agent.py
- tests/test_offline_memory_agent.py
Fix bug where calling rethink multiple times creates duplicate messages
> fix: remove dedup messages

- letta/client/client.py
- letta/server/rest_api/routers/v1/agents.py
- tests/test_client.py
Example response in metadata:
```
Job status: completed
Job completed in 5.097556114196777 seconds, job=created_by_id='user-00000000-0000-4000-8000-000000000000' last_updated_by_id='user-00000000-0000-4000-8000-000000000000' created_at=datetime.datetime(2024, 12, 10, 2, 1, 45) updated_at=datetime.datetime(2024, 12, 10, 2, 1, 45) status=<JobStatus.completed: 'completed'> completed_at=datetime.datetime(2024, 12, 10, 2, 1, 49, 529202) metadata_={'result': {'messages': [{'id': 'message-9567ea9a-b46c-45d7-a9b6-2a53c52fcc4c', 'date': '2024-12-10T02:01:49+00:00', 'message_type': 'internal_monologue', 'internal_monologue': 'User logged in and sent a message. Test passed successfully. Next, we should explore more of our capabilities. Maybe, we can start by emulating a conversation.'}, {'id': …
```
> feat: add an async messages route (`/agent/{agent_id}/messages/async`)

- letta/server/rest_api/routers/v1/agents.py
> fix: re-enable streaming tokens

- Dockerfile
> Revert "chore: set `Dockerfile` to use Python 3.12 "

- letta/orm/passage.py
- letta/server/server.py
- letta/services/passage_manager.py
- tests/test_managers.py
- tests/test_server.py
> chore: raising errors for passages, adding new passage test

- letta/server/server.py
- letta/services/tool_execution_sandbox.py
Small change to decrease the number of branches in the sandbox logic
> fix: make sandboxrunresult rv not optional

- letta/prompts/system/memgpt_modified_chat.txt
- letta/prompts/system/memgpt_modified_o1.txt
This fixes typo in prompt file.
Nothing to be tested, just doc update.
Nothing to be tested, just doc update.
**Additional …
> docs: fix typo in prompt

- letta/server/rest_api/utils.py
> fix: add error logging on stream fails

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- examples/docs/rest_client.py
- examples/notebooks/Customizing memory management.ipynb
- examples/personal_assistant_demo/README.md
- examples/resend_example/README.md
- letta/agent.py
- letta/local_llm/function_parser.py
- letta/server/server.py
- letta/server/ws_api/server.py
- letta/settings.py
- tests/test_client.py
Fixed broken links in docs, and fixed typos.
Check the links I updated. Grammarly.
NA
NA
NA
Add any other …
> docs: Feature/update docs

- letta/schemas/embedding_config.py
Make `embedding_endpoint_type` an enum
> fix: Make `embedding_endpoint_type` an enum

- letta/server/server.py
- tests/test_server.py
Fix update agent with added tools. This is just a patch, we will more carefully inspect the in-memory agent operations to see if they are necessary, and if so, remove it so everything reflects the state of the db.
> fix: Fix update agent

- letta/agent.py
- letta/llm_api/anthropic.py
- tests/helpers/endpoints_helper.py
- tests/integration_test_agent_tool_graph.py
> fix: Allow `ChildToolRule` to work without support for structured outputs

- poetry.lock
- pyproject.toml
Bump composio packages to fix app enum versioning issues.
> chore: bump composio packages

- letta/server/rest_api/routers/v1/agents.py
- letta/server/server.py
Finished debugging slow `list_messages`, removing temporary verbose debug logs.
> chore: Remove debugging logs

- letta/providers.py
Include all gemini models, including the flash models. The recent gemini flash 2.0 performs very well. So, including even the flash models would be good.
Add/Improve existing feature
> Add support for non pro models

- letta/services/message_manager.py
Fix the limit. Currently the limit is the default, which is 50.
> fix: Fix limit for get_messages_by_ids

- letta/server/rest_api/routers/v1/agents.py
> fix: hotfix

- letta/server/rest_api/routers/v1/tools.py
Asked composio folks for a run down of the new exceptions from Composio - adjust our API endpoint to catch these and report more detailed messages for now.
(Can make these messages more user friendly once Composio is more stable)
> feat: Make composio error catching more verbose and granular

- letta/agent.py
- letta/llm_api/helpers.py
- letta/llm_api/llm_api_tools.py
- letta/services/agent_manager.py
- tests/helpers/endpoints_helper.py
- tests/integration_test_agent_tool_graph.py
> fix: patch bug in inner thoughts unpacker

- letta/schemas/letta_response.py
Bugfix
get a response from the agent and show it in the Jupyter Notebook.
Yes.
N/A
No. It's a one-liner.
> Bugfix: fix attribute error in `_repr_html_` method for `LettaResponse`

- fact_edit_experiments/run_gsm8k.py
- letta/agent.py
- letta/llm_api/helpers.py
- letta/llm_api/llm_api_tools.py
- letta/schemas/llm_config.py
There was a bug with certain results returning None, I applied the changes from [this PR](https://github.com/letta-ai/letta/pull/2311/files) to Kevin's branch.
> fix null bug

- development.compose.yml
This PR exists only to trigger a webhook and test the syncing mechanism between repositories
> Test GitHub Sync

- development.compose.yml
This PR exists only to test syncing letta and letta-cloud
> Test-gh-sync

- .github/workflows/letta-code-sync.yml
> chore: update workflows

- letta/__init__.py
- pyproject.toml
> chore: bump version 0.6.13

- letta/__init__.py
- pyproject.toml
> chore: bump version

- letta/__init__.py
- poetry.lock
- pyproject.toml
- tests/test_tool_sandbox/restaurant_management_system/adjust_menu_prices.py
> chore: bump version to 0.6.22

- letta/__init__.py
- poetry.lock
- pyproject.toml
> chore: bump version 6.23

- letta/__init__.py
- letta/llm_api/llm_api_tools.py
- pyproject.toml
> fix: Fix VLLM usage

- letta/functions/schema_generator.py
This PR fixes the issue that occurs when nested pedantic model input is used as an argument. See the test section for an example.
https://github.com/letta-ai/letta/blob/a42a1979a6f449d44001800aac0905c957e8263a/tests/test_tool_schema_parsing_files/nested_pydantic_as_arg_example.py#L21-L25
Change the `steps` variable annotation to `Step`, and then run `pydantic_model_to_json_schema(Steps)` without this fix, we would get the following error:
```
>>> pydantic_model_to_json_schema(Steps)
File "<python-input-16>", line 1, in <module>
pydantic_model_to_json_schema(Steps)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
File "/Users/clannad/Dev/GitHub/letta/letta/functions/schema_generator.py", line 301, …
```
> fix: handle nested pydantic model args in schema generation

- pyproject.toml
> chore: bump poetry version

- letta/llm_api/aws_bedrock.py
Use letta logger instead of print statements.
More logs.
Nope!
> Use logging in bedrock

- examples/mcp_example.py
Adds comments to the MCP example to explain the workflow.
No code changes.
Added some MCP servers and figured it out so yes.
> Add comments to the MCP example

- letta/llm_api/aws_bedrock.py
Fix a bug where the check returns bool but the check is against str | None.
Set environment variables.
Nope!
> Fix the credentials check to use bool

- letta/llm_api/google_vertex_client.py
- letta/schemas/llm_config.py
> Use reasoning tokens for gemini flash

- letta/llm_api/google_ai_client.py
The current `convert_tools_to_google_ai_format` method in `google_ai_client.py` uses a non-existent method.
https://github.com/letta-ai/letta/blob/de7637c6fdf8f45a5d58a1dad5ec30cc04b715aa/letta/llm_api/google_ai_client.py#L326-L332
The `_clean_google_ai_schema_properties` helper method was introduced in commit ec95703, which aimed at removing unsupported params in the tool schema. However, this method has been accidentally deleted, and it has been missing in the current main branch since 546996e (can be checked via `git bisect`).
This PR brings it back. So `convert_tools_to_google_ai_format` can still use it!
Fixes #2590
> revert: reapply changes from commit ec95703 to fix GoogleAIClient

- dev-compose.yaml
- letta/server/rest_api/app.py
- letta/server/rest_api/routers/openai/chat_completions/chat_completions.py
- letta/server/rest_api/routers/v1/agents.py
- letta/server/rest_api/routers/v1/voice.py
a bug in openapi the `LettaMessageUnion` is missing
the polyfill openapi method is not triggered on app startup
- run letta server
- visit open `/openapi.json`
- observe missing `LettaMessageUnion` schema
yes, it's fixed
none
no
> fix(openapi): run openapi polyfill

- letta/interfaces/anthropic_streaming_interface.py
- letta/schemas/llm_config.py
- tests/integration_test_sleeptime_agent.py
Bug fix for anthropic thinking tag.  This only shows up when an xml tag is split across events.
Create two events that have a closing `</thinking>` tag split across them.
Not yet.
> Add fix for anthropic streaming </thinking tag

- letta/orm/sqlalchemy_base.py
> fix: size async bug

- letta/__init__.py
- pyproject.toml
> chore: bump version 0.7.18

- Dockerfile
> feat: include Node.js to support node-based MCPs

- letta/server/db.py
> fix: patch db init bug

- letta/__init__.py
- pyproject.toml
> chore: bump version 0.7.25

- letta/__init__.py
- letta/agents/letta_agent_batch.py
- pyproject.toml
> fix: asyncify batch sandbox creation

- letta/__init__.py
- pyproject.toml
> chore: bump version 0.7.28

- letta/jobs/llm_batch_job_polling.py
- letta/services/llm_batch_manager.py
- letta/settings.py
> feat: add configurable batch size and lookback

- .github/workflows/test-pip-install.yml
> chore: remove python 3.10 support and testing

- letta/agents/letta_agent_v2.py
Refactor step tracking by moving writes to the step object into the checkpoint helper functions. This consolidates step tracking logic into the appropriate abstraction layer rather than having it scattered throughout the agent loop.
**Notes:**
While this change improves encapsulation, not loving the current helper function approach. Ideally, we would create a dedicated checkpoint class with methods for each checkpoint type - this would have the main benefit of not needing to pass around all the objects that need to be updated at each checkpoint step. 
However, I'm hesitant to make this larger change now because if we eventually want to migrate to Temporal or another workflow engine, we'd want the logic to be as stateless as possible. Creating a stateful …
> refactor: move step logging into checkpoint helpers

- letta/agents/letta_agent_v2.py
Rename an existing method to be exposed as a public method for summarizing conversation history. This change ensures API parity with the old agent loop for internal usage within Letta.
**Notes:**
This probably isn't the right place for this method since it doesn't use anything else related to the agent loop, but for parity, going to make this change. After this, the old agent loop and new agent loop should have full parity. This will be used in the standalone summarization endpoint that is exposed on the agents routes.
The Agent Loop Refactor is a project to redesign the core execution engine of our agents. It aims to create a more modular, testable, and extensible architecture that can better accommodate complex features like human-in-the-loop …
> refactor: add public summarize_conversation_history method for parity

- letta/server/rest_api/routers/v1/messages.py
Update the pagination parameters of the `list_batch_messages` endpoint to follow our standard pagination pattern. Replace the current parameters with the consistent set: `before`, `after`, `limit`, and `order`.
**Notes:**
This change aligns the `list_batch_messages` endpoint with our standardized pagination approach, creating consistency across all list endpoints in the SDK. Using the same parameter names (`before`, `after`, `limit`, `order`) for pagination across all endpoints makes the API more intuitive and reduces the learning curve for developers. This standardization is especially important as users often need to paginate across multiple resource types when building applications. While this is a breaking change for this specific endpoint, making it now …
> feat: update pagination params for batch messages endpoint

- letta/server/rest_api/routers/v1/messages.py
This is a purely aesthetic change to make the headings on our docs page more consistent
> chore: rename create batch operation id

- letta/agents/agent_loop.py
- letta/server/rest_api/routers/v1/agents.py
Complete the cutover to the new agent loop architecture in production. This change switches all production traffic from the old agent loop implementation to the refactored version after extensive testing and feature parity validation.
**Testing:**
Full test suite, but especially:
```
(letta) caren@caren-mac letta % poetry run pytest -s -vv tests/integration_test_send_message.py                                                                      
(letta) caren@caren-mac letta % poetry run pytest -s -vv tests/integration_test_human_in_the_loop.py                                                                      
(letta) caren@caren-mac letta % poetry run pytest -s -vv tests/integration_test_sleeptime_agent.py …
```
> feat: cutover to new refactored agent loop

- tests/test_provider_trace.py
Testing:
```
(letta) caren@mac letta % uv run pytest -s -vv tests/test_provider_trace.py                  
```
> test: update provider trace tests to use sdk client

- letta/server/rest_api/routers/v1/messages.py
Update titles and docstrings for all batches routes to ensure consistency.
**Notes:**
Since these are actually returning run objects under the hood, wonder if they should be more tightly coupled with jobs/runs endpoint? Need to rethink the structure more broadly.
3. Strengthening error handling with predictable error codes and …
> feat: update docstring and titles for batch routes

- letta/server/rest_api/routers/v1/providers.py
Update all docstrings in the providers endpoints to ensure consistency.
4. Finalizing type definitions to ensure accurate developer tooling support
5. Documenting clear compatibility guarantees and deprecation policies
This work represents the critical …
> feat: make docstrings consistent for providers routes

- letta/server/rest_api/routers/v1/health.py
Rename health check endpoint to check health.
**Notes:**
This is a small nit that makes the provider check and health check endpoints match and look better together.
4. Finalizing type definitions to ensure accurate developer tooling support
5. …
> feat: rename health check title in docs

- letta/server/rest_api/routers/v1/agents.py
Drop "serialized" from the titles of the import and export routes.
3. Strengthening error handling with predictable error codes and u
> feat: drop serialized from export/import docs

- letta/server/rest_api/routers/v1/internal_templates.py
Some changes to some template routes, allowing
> feat: allow searching by entites+project_id

- letta/functions/function_sets/multi_agent.py
- letta/functions/helpers.py
- letta/server/rest_api/dependencies.py
- letta/server/rest_api/routers/openai/chat_completions/chat_completions.py
- letta/server/rest_api/routers/v1/agents.py
- letta/server/rest_api/routers/v1/blocks.py
- letta/server/rest_api/routers/v1/embeddings.py
- letta/server/rest_api/routers/v1/folders.py
- letta/server/rest_api/routers/v1/groups.py
- letta/server/rest_api/routers/v1/identities.py
- letta/server/rest_api/routers/v1/internal_templates.py
- letta/server/rest_api/routers/v1/jobs.py
- letta/server/rest_api/routers/v1/llms.py
- letta/server/rest_api/routers/v1/messages.py
- letta/server/rest_api/routers/v1/organizations.py
- letta/server/rest_api/routers/v1/providers.py
- letta/server/rest_api/routers/v1/runs.py
- letta/server/rest_api/routers/v1/sandbox_configs.py
- letta/server/rest_api/routers/v1/sources.py
- letta/server/rest_api/routers/v1/steps.py
- letta/server/rest_api/routers/v1/tags.py
- letta/server/rest_api/routers/v1/telemetry.py
- letta/server/rest_api/routers/v1/tools.py
- letta/server/rest_api/routers/v1/users.py
- letta/server/rest_api/routers/v1/voice.py
- letta/server/rest_api/utils.py
Hook up the new header parameter dependency injection added in https://github.com/letta-ai/letta/pull/2903 to all FastAPI routes.
**Notes:**
This should not change the OpenAPI spec if everything is configured correctly.
4. Finalizing type definitions …
> feat: add new header dependency in all routes

- letta/server/rest_api/routers/v1/groups.py
Add pagination to the `client.groups.messages.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:**
3. Strengthening error handling with predictable error codes and …
> feat: add pagination to list groups messages endpoint

- letta/server/rest_api/routers/v1/blocks.py
Add pagination to the `client.blocks.agents.list` endpoint with `before`, `after`, `limit`, `order`, and `order_by` parameters.
**Notes:** …
> feat: add pagination to blocks agents endpoint

- letta/server/rest_api/routers/v1/__init__.py
- letta/server/rest_api/routers/v1/archives.py
Adds archive router and create path
> feat: Add create archive route

- fern/docs.yml
- fern/pages/tutorials/telegram_bot.mdx
- Add comprehensive documentation for the Letta Telegram Bot (@letta_ai_bot)
- Create new "Integrations" section in main docs tab for consumer-facing interfaces
- Document all bot commands, features, and usage patterns
This PR adds documentation for the Letta Telegram Bot, which provides a consumer-friendly way to interact with Letta agents through Telegram. The bot supports features like memory management, agent templates, tool configuration, and proactive notifications.
The documentation is positioned in a new "Integrations" section under the main Documentation tab, separate from developer-focused tutorials, to better reflect its consumer-facing nature.
> docs: add Telegram bot integration guide
